### ISSUE TITLE
Why you use Magisk Canary ?

### ISSUE THREAD

**Issue by YT-Advanced** [MustardChef/WSABuilds#10]
As the title, why you use Magisk Canary instead of use Magisk beta/stable version. Because I think the canary version may cause some issues to my experience

**Comment by MustardChef** [comment]
Hmm, a very good question. I use Magisk Canary as it is more frequently updated then the Beta and Stable Channel. I am currently thinking about changing it back to Stable, but there have been no reported issued with Canary so far.

**Comment by ggfong** [comment]
> Hmm, a very good question. I use Magisk Canary as it is more frequently updated then the Beta and Stable Channel. I am currently thinking about changing it back to Stable, but there have been no reported issued with Canary so far. Are you experiencing any issues? Is there a chance that problems may occur? If so, do tell me.

Why not use Magisk alpha（https://t.me/magiskalpha）

**Comment by MustardChef** [comment]
> > Hmm, a very good question. I use Magisk Canary as it is more frequently updated then the Beta and Stable Channel. I am currently thinking about changing it back to Stable, but there have been no reported issued with Canary so far. Are you experiencing any issues? Is there a chance that problems may occur? If so, do tell me.
> 
> Why not use Magisk alpha（https://t.me/magiskalpha）

Magisk Alpha? Could you tell me what new features there are compared to the normal Magisk?
