### ISSUE TITLE
Guide: Camera Not Working on WSA

### ISSUE THREAD

**Issue by MustardChef** [MustardChef/WSABuilds#100]
Observation: 
- Go to start > run > wsa://com.android.camera2, the camera start0ed working on all apps.
- Remove all Virtual Cams and make sure that there are none interfering

**Comment by S-ed** [comment]
Hello.
The start of the Camera app does not resolve the lack of camera for me. It just stays blank. In addition, Google Translate asking for Update of the GApp.

![image](https://github.com/MustardChef/WSABuilds/assets/3008353/3c721d50-9978-486c-9fdd-af7757982304)

![image](https://github.com/MustardChef/WSABuilds/assets/3008353/57d1bf81-a151-495b-a53a-70cc4fd44084)

**Comment by MustardChef** [comment]
> Hello. The start of the Camera app does not resolve the lack of camera for me. It just stays blank. In addition, Google Translate asking for Update of the GApp.
> 
> ![image](https://user-images.githubusercontent.com/3008353/246665568-3c721d50-9978-486c-9fdd-af7757982304.png)
> 
> ![image](https://user-images.githubusercontent.com/3008353/246665552-57d1bf81-a151-495b-a53a-70cc4fd44084.png)

So the camera is not working on WSA right, but it is working on Windows?

**Comment by MustardChef** [comment]
@S-ed I would check if the camera is working on the Official Builds of WSA. It will help me determine whether this is an issue with the MagiskOnWSA builds or WSA itself.

**Comment by S-ed** [comment]
@MustardChef Sorry, You've answered before I've retracted my message.
I have some virtual cams on my system, and seems those are not accessible by android. Hardware one turned on after I've restarted the WSA.

**Comment by MustardChef** [comment]
> @MustardChef Sorry, You've answered before I've retracted my message. I have some virtual cams on my system, and seems those are not accessible by android. Hardware one turned on after I've restarted the WSA.

@S-ed Ah, so the issue has been fix?

**Comment by S-ed** [comment]
@MustardChef Yes.
And after restart GApps also found some updates, so Google translate not showing an error anymore.

**Comment by MustardChef** [comment]
> @MustardChef Yes. And after restart GApps also found some updates, so Google translate not showing an error anymore.

I am glad to here.

**Comment by S-ed** [comment]
Hm. Someone claimed that Virtual Cameras also should work. It doesn't for me. I'm on Win10.

https://github.com/microsoft/WSA/issues/77

**Comment by OpokuKoduah** [comment]
> Hm. Someone claimed that Virtual Cameras also should work. It doesn't for me. I'm on Win10.
> 
> [microsoft/WSA#77](https://github.com/microsoft/WSA/issues/77)
has the issue been fixed? I'm asking because I want to this version of WSA

**Comment by MustardChef** [comment]
@OpokuKoduah You should test it as there is no definitive answer to whether Virtual Cameras will work with WSA on Windows 10. If it does not work for someone else, it might work for you. So its worth a shot.
