### ISSUE TITLE
[BUG] Magisk root status N/A

### ISSUE THREAD

**Issue by deckyfx** [MustardChef/WSABuilds#102]
### Describe the bug | 描述一下这个错误

Magisk root status N/A, 
Tried to reinstall/update still not rooted
![image](https://github.com/MustardChef/WSABuilds/assets/1076192/4bf341d5-2731-4444-a4fb-cf36c52a9c34)

### Steps to reproduce the issue | 重现该问题的步骤

Just update/install following the guide here

### Expected behaviour | 预期的行为

Should be rooted with Magisk installed

### Downloaded Build Of WSA | 已下载的WSA版本

https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2305.40000.3.0/WSA_2305.40000.3.0_x64_Release-Nightly-with-magisk-47d2d4e3.26102.-canary-MindTheGapps-13.0-RemovedAmazon.zip

### Windows build number | Windows构建号

22H2 2261.1778

### PC Specification | 个人电脑规格

Not relevant

### Additional context | 额外的背景

-

**Comment by MustardChef** [comment]
@deckyfx Have you tried restarting WSA and checking if it shows as installed?

**Comment by MustardChef** [comment]
I have just tested it and it seems to be working just fine for me and shows as installed.

**Comment by deckyfx** [comment]
just to make it clear, did you mean to turn off wsa? yeah

maybe I need to clean reinstall my wsa? how to do it?

**Comment by MustardChef** [comment]
> just to make it clear, did you mean to turn off wsa? yeah
> 
> maybe I need to clean reinstall my wsa? how to do it?

Just find the WSA Settings app in the Start Menu and right click and press uninstall.

**Comment by deckyfx** [comment]
OK I success clean installed it, this bug may be closed, 

btw, I have one other issue and I don't know where to ask, so I might ask here, with this newly installed wsa, the resolution is not adaptive, so some application is clipped, with my previous wsa, there is a way to show a reload icon to make the screen resolution adaptive, but i forgot how, do you have any idea?

Clipped
![image](https://github.com/MustardChef/WSABuilds/assets/1076192/4977d729-2d8d-4b0f-8f0a-e03a2949aab7)

Full view, but i have to maximize it
![image](https://github.com/MustardChef/WSABuilds/assets/1076192/f4a25cab-8de9-4e0b-86b0-0bc9c85ab54c)

There is a way to show a reload icon like this to make the screen adaptive
![Screenshot 2023-06-10 171542 b](https://github.com/MustardChef/WSABuilds/assets/1076192/19138689-c31e-4af8-8936-874dd09c0138)

But i forgot how
