### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 20101009** [MustardChef/WSABuilds#107]
### Describe the bug | 描述一下这个错误

Play Store won't start after installing WSA

### Steps to reproduce the issue | 重现该问题的步骤

1.Double-click Run.bat to install
2. Play Store should start, but it doesn't

### Expected behaviour | 预期的行为

zip re-downloaded, wsa re-installed, Windows restarted, but no improvement

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2305.40000.4.0_x64_Release-Nightly-with-magisk-47d2d4e3.26102.-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip

https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2305.40000.4.0

### Windows build number | Windows构建号

19045.3031

### PC Specification | 个人电脑规格

OS Name Microsoft Windows 10 home
Version 10.0.19045.3031 22H2
Device VAIO
CPU Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz   2.20 GHz
RAM 12GB
System Type x64
BIOS mode UEFI

**Comment by MustardChef** [comment]
Solution: Try on another PC that has at least a 6th Gen Intel Processor/ Ryzen 1st Gen or newer CPU.
