### ISSUE TITLE
[BUG]提示不兼容-无法安装

### ISSUE THREAD

**Issue by neverp** [MustardChef/WSABuilds#114]
### Describe the bug | 描述一下这个错误

![5)DF8ON34T 9U@`D(@REN C](https://github.com/MustardChef/WSABuilds/assets/89000973/8e704174-dce3-44e2-b7c8-e8bb337b6801)

### Steps to reproduce the issue | 重现该问题的步骤

运行Run.bat然后报错

### Expected behaviour | 预期的行为

正常安装

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2305.40000.6.0_x64_Release-Nightly-with-magisk-47d2d4e3(26102)-canary-MindTheGapps-13.0-RemovedAmazon

### Windows build number | Windows构建号

版本22H2(操作系统内部版本19045.3086)

### PC Specification | 个人电脑规格

操作系统名称	Microsoft Windows 10 专业版
版本	10.0.19045 版本 19045
其他操作系统描述 	没有资料
操作系统制造商	Microsoft Corporation
系统名称	DESKTOP-SSMAD95
系统制造商	LENOVO
系统型号	21A2
系统类型	基于 x64 的电脑
系统 SKU	LENOVO_MT_21A2_BU_idea_FM_ThinkBook 14 G3 ACL
处理器	AMD Ryzen 5 5600U with Radeon Graphics，2301 Mhz，6 个内核，12 个逻辑处理器
BIOS 版本/日期	LENOVO GQCN36WW(V1.22), 2022/10/21
SMBIOS 版本	3.3
嵌入式控制器版本	1.35
BIOS 模式	UEFI
主板制造商	LENOVO
主板产品	LNVNB161216
主板版本	SDK0L77769 WIN
平台角色	移动
安全启动状态	启用
PCR7 配置	需要提升才能查看
Windows 目录	C:\Windows
系统目录	C:\Windows\system32
启动设备	\Device\HarddiskVolume1
区域设置	中国
硬件抽象层	版本 = "10.0.19041.2728"
用户名	DESKTOP-SSMAD95\Never7
时区	中国标准时间
已安装的物理内存(RAM)	16.0 GB
总的物理内存	13.8 GB
可用物理内存	8.61 GB
总的虚拟内存	16.5 GB
可用虚拟内存	7.42 GB
页面文件空间	2.63 GB
页面文件	C:\pagefile.sys
内核 DMA 保护	启用
基于虚拟化的安全性	未启用
设备加密支持	需要提升才能查看
Hyper-V - 虚拟机监视模式扩展	是
Hyper-V - 第二级地址转换扩展	是
Hyper-V - 固件中启用的虚拟化	是
Hyper-V - 数据扩展保护	是

**Comment by MustardChef** [comment]
@neverp 亲爱的用户，你正试图在Windows 10上运行WSA的Windows 11版本。请下载正确的版本，它适用于Windows 10。

链接到Windows 10版本（请使用此链接）：https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2305.40000.6.0

如果你在安装或运行WSA时仍有问题，请随时在这个Github问题中提问。

**Comment by neverp** [comment]
感谢，已解决！
完美运行
