### ISSUE TITLE
[BUG] How to clear app cache/data?

### ISSUE THREAD

**Issue by NebularNerd** [MustardChef/WSABuilds#115]
### Describe the bug | 描述一下这个错误

Hi there, I've got an issue with Chrome running on WSA. It used to be fine but now the pages are not showing at or or if they do it corrupts. I can't find where I would empty the apps cache to see if that cures the issue, normally on the phone it would be settings->apps->app name->Clear Cache. Can anyone help point me in the right direction. All other apps behave as they should, just Chrome being a pain.

![image](https://github.com/MustardChef/WSABuilds/assets/8470449/c59e78aa-b730-4a4e-bab1-3d8e0c25eeec)

### Steps to reproduce the issue | 重现该问题的步骤

Try running Chrome on Win 10 WSA builds

### Expected behaviour | 预期的行为

Chrome not breaking

### Downloaded Build Of WSA | 已下载的WSA版本

Latest Win 10 Build

### Windows build number | Windows构建号

Win 10 22H2 plus all recent updates

### PC Specification | 个人电脑规格

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	Z490 VISION G
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 3792 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F20, 19/04/2021
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	Z490 VISION G
BaseBoard Version	x.x
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume6
Locale	United Kingdom
Hardware Abstraction Layer	Version = "10.0.19041.2728"
Username	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Time Zone	GMT Summer Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	7.48 GB
Total Virtual Memory	73.9 GB
Available Virtual Memory	28.0 GB
Page File Space	42.0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualisation-based security	Running
Virtualisation-based security required security properties	
Virtualisation-based security available security properties	Base Virtualisation Support, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualisation
Virtualisation-based security services configured	
Virtualisation-based security services running	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by MustardChef** [comment]
> ### Describe the bug | 描述一下这个错误
> 
> Hi there, I've got an issue with Chrome running on WSA. It used to be fine but now the pages are not showing at or or if they do it corrupts. I can't find where I would empty the apps cache to see if that cures the issue, normally on the phone it would be settings->apps->app name->Clear Cache. Can anyone help point me in the right direction. All other apps behave as they should, just Chrome being a pain.
> 
> ![image](https://github.com/MustardChef/WSABuilds/assets/8470449/c59e78aa-b730-4a4e-bab1-3d8e0c25eeec)
> 
> 
> ### Steps to reproduce the issue | 重现该问题的步骤
> 
> Try running Chrome on Win 10 WSA builds
> 
> ### Expected behaviour | 预期的行为
> 
> Chrome not breaking
> 
> ### Downloaded Build Of WSA | 已下载的WSA版本
> 
> Latest Win 10 Build
> 
> ### Windows build number | Windows构建号
> 
> Win 10 22H2 plus all recent updates
> 
> ### PC Specification | 个人电脑规格
> 
> OS Name	Microsoft Windows 10 Pro
> Version	10.0.19045 Build 19045
> Other OS Description 	Not Available
> OS Manufacturer	Microsoft Corporation
> System Name	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> System Manufacturer	Gigabyte Technology Co., Ltd.
> System Model	Z490 VISION G
> System Type	x64-based PC
> System SKU	Default string
> Processor	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 3792 Mhz, 8 Core(s), 16 Logical Processor(s)
> BIOS Version/Date	American Megatrends Inc. F20, 19/04/2021
> SMBIOS Version	3.2
> Embedded Controller Version	255.255
> BIOS Mode	UEFI
> BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
> BaseBoard Product	Z490 VISION G
> BaseBoard Version	x.x
> Platform Role	Desktop
> Secure Boot State	Off
> PCR7 Configuration	Binding Not Possible
> Windows Directory	C:\Windows
> System Directory	C:\Windows\system32
> Boot Device	\Device\HarddiskVolume6
> Locale	United Kingdom
> Hardware Abstraction Layer	Version = "10.0.19041.2728"
> Username	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Time Zone	GMT Summer Time
> Installed Physical Memory (RAM)	32.0 GB
> Total Physical Memory	31.9 GB
> Available Physical Memory	7.48 GB
> Total Virtual Memory	73.9 GB
> Available Virtual Memory	28.0 GB
> Page File Space	42.0 GB
> Page File	C:\pagefile.sys
> Kernel DMA Protection	On
> Virtualisation-based security	Running
> Virtualisation-based security required security properties	
> Virtualisation-based security available security properties	Base Virtualisation Support, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualisation
> Virtualisation-based security services configured	
> Virtualisation-based security services running	
> Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected, TPM is not usable
> A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
> 
> 
> ### Additional context | 额外的背景
> 
> _No response_

To get to the Android Settings, (on your keyboard) press the Windows Key + R. The Run box should open. In the box type: wsa://com.android.settings. From here we can now go to the Apps section and clear data and (or) cache.

**Comment by MustardChef** [comment]
If you still need help, please let me know!

**Comment by NebularNerd** [comment]
@MustardChef That seemed to do the trick, a quick `FORCE STOP` and a `CLEAR CACHE` and we're back in business. 😁
![image](https://github.com/MustardChef/WSABuilds/assets/8470449/9a8e5b4e-0179-422b-aeb5-f86748e048e6)


Chrome is such a rubbish browser at times 🤣
