### ISSUE TITLE
[BUG] [2305.40000.6.0] Windows 11 x64 resources.pri error

### ISSUE THREAD

**Issue by dovahkrid** [MustardChef/WSABuilds#116]
### Describe the bug | 描述一下这个错误

The resources.pri in the WSA_2305.40000.6.0_x64_Release-Nightly-with-magisk-47d2d4e3.26102.-canary-MindTheGapps-13.0-RemovedAmazon.zip file is only 1KB (which should be about ~90KB). Can be replaced with others' resources.pri file.

### Steps to reproduce the issue | 重现该问题的步骤

Install with Run.bat

### Expected behaviour | 预期的行为

The resources.pri should be okay

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2305.40000.6.0_x64_Release-Nightly-with-magisk-47d2d4e3.26102.-canary-MindTheGapps-13.0-RemovedAmazon

### Windows build number | Windows构建号

Windows 11 22H2 22621.1848

### PC Specification | 个人电脑规格

OS Name	Microsoft Windows 11 Education
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-S3FD246
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	Z490 GAMING X
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz, 2904 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F2, 25/03/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	Z490 GAMING X
BaseBoard Version	x.x
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.1413"
User Name	DESKTOP-S3FD246\Phu
Time Zone	SE Asia Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	19.6 GB
Total Virtual Memory	36.7 GB
Available Virtual Memory	19.6 GB
Page File Space	4.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	
Virtualization-based security Services Running	Credential Guard
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by YT-Advanced** [comment]
Can you test this build, it have prebuilt `make.pri` file
https://github.com/YT-Advanced/WSA-Script/releases/tag/WSA-Insider-Version

**Comment by MustardChef** [comment]
@dovahkrid Hello. I have had a little look at this on my end and I think that the 1KB Resources.pri file is due to an extraction error/ issue or corruption during download. The reason that I have come to this conclusion is that it shows the file size of Resource.pri as ~90KB. 

Please redownload the build and extract using 7zip and not the built-in Windows .zip extractor.

See below: 
![image](https://github.com/MustardChef/WSABuilds/assets/68516357/3c7797ea-80ec-4674-b570-94b2d77c1c7b)
![image](https://github.com/MustardChef/WSABuilds/assets/68516357/bd261bff-b9ee-4636-86e0-db206b059a76)

**Comment by dovahkrid** [comment]
Hmmm seems to be a mistake at my end. Thank you guys for the replies
