### ISSUE TITLE
[BUG] Downloaded game not working

### ISSUE THREAD

**Issue by guicamarotto** [MustardChef/WSABuilds#117]
### Describe the bug | 描述一下这个错误

Play store and subsystem working properly.

but when try to start an application, its not working. keep white screen

![image](https://github.com/MustardChef/WSABuilds/assets/10661352/f65da6c2-8691-4848-bd82-328963ae47a6)

### Steps to reproduce the issue | 重现该问题的步骤

Open Play Store
Download a game
Execute the game

### Expected behaviour | 预期的行为

application wokring

### Downloaded Build Of WSA | 已下载的WSA版本

[WSA_2305.40000.6.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2305.40000.6.0/WSA_2305.40000.6.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip)

### Windows build number | Windows构建号

19045.3086

### PC Specification | 个人电脑规格

Nome do Sistema Operacional	Microsoft Windows 10 Pro
Versão	10.0.19045 Compilação 19045
Processador	AMD Ryzen 5 1600 Six-Core Processor, 3200 Mhz, 6 Núcleo(s), 12 Processador(es) Lógico(s)
Memória Física (RAM) Instalada	16.0 GB

**Comment by guicamarotto** [comment]
enablw hyper-v and worked

**Comment by MustardChef** [comment]
> enablw hyper-v and worked

@guicamarotto So it is fixed now? I will close this issue. If the same issue occurs then feel free to reopen.
