### ISSUE TITLE
[REQUEST]Wish a build like "dm-verity disabled"

### ISSUE THREAD

**Issue by Pittow** [MustardChef/WSABuilds#118]
### Describe your request | 描述您的要求

Magisk is still limited a lot in WSA , I cannot mount any ro filesystem to rw . I wish there is a "dm-verity disabled" build , it will let me enjoy Android .

If I can modify the kernel command line in the new version , I'll be so appreciative to your help .

**Comment by YT-Advanced** [comment]
For mount filesystem, use [MagiskOverlayFS](https://github.com/HuskyDG/magic_overlayfs/) module

**Comment by Pittow** [comment]
Thanks for your tips , I'll try it now .

**Comment by Pittow** [comment]
Ooops , it may not work in my computer . I've install MagiskOverlayFS successful , but when I try to mount / rw , WSA suddenly get crashed and reboot .

[persist.sys.boot.reason.history]: [reboot,1687763011

**Comment by MustardChef** [comment]
Check this out:

https://forum.xda-developers.com/t/wsabuilds-latest-windows-subsystem-for-android-wsa-builds-for-windows-10-and-11-with-magisk-and-google-play-store.4545087/post-88642923

**Comment by Pittow** [comment]
Thank you , I'll try again .

**Comment by MustardChef** [comment]
Might make a detail guide if it works.

**Comment by Pittow** [comment]
Finally it works , I'm appreciative to your help .

**Comment by Pittow** [comment]
I am still wondering , where is the boot.img ? I can't find it .

**Comment by MustardChef** [comment]
> I am still wondering , where is the boot.img ? I can't find it .

Not sure if a boot.img file even exists.

**Comment by Pittow** [comment]
Hmmmm,, but where does kernel cmdline lie on ?

**Comment by MustardChef** [comment]
> Hmmmm,, but where does kernel cmdline lie on ?

I am not qualified on this matter, but perhaps [this](https://stackoverflow.com/questions/42719488/obtaining-kernel-command-line-parameters-of-android-linux-kernel) might help.

**Comment by Pittow** [comment]
Thanks for your help , but it does not tell the way to edit it .

**Comment by MustardChef** [comment]
> Thanks for your help , but it does not tell the way to edit it .

I guess you would have to make the changes that you would like to make to the [source](https://github.com/microsoft/WSA-Linux-Kernel) and build it.

**Comment by MustardChef** [comment]
I am closing this issue, since I cannot assist you further in this matter. If you do have any questions or further things to add, or if you think this issue should not be closed: Feel free to reopen this issue.
