### ISSUE TITLE
[BUG] Game apps are very slow

### ISSUE THREAD

**Issue by guicamarotto** [MustardChef/WSABuilds#120]
### Describe the bug | 描述一下这个错误

Game applications are very slow.

Games tested:
- BrownDust 2 is very slow to load and it is lagging all the gameplay (more than in my phone)
- Artery Gear (freezes evertime when try do download new updates)

### Steps to reproduce the issue | 重现该问题的步骤

Download a game
Try to play

### Expected behaviour | 预期的行为

Play smooth 

### Downloaded Build Of WSA | 已下载的WSA版本

[WSA_2305.40000.6.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2305.40000.6.0/WSA_2305.40000.6.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip)

### Windows build number | Windows构建号

19045.3086

### PC Specification | 个人电脑规格

Nome do Sistema Operacional	Microsoft Windows 10 Pro
Versão	10.0.19045 Compilação 19045
Outra Descrição do Sistema Operacional 	Não disponível
Fabricante do Sistema Operacional	Microsoft Corporation
Nome do sistema	DESKTOP-4E8VNNQ
Fabricante do sistema	To Be Filled By O.E.M.
Modelo do sistema	To Be Filled By O.E.M.
Tipo do sistema	PC baseado em X64
SKU do sistema	To Be Filled By O.E.M.
Processador	AMD Ryzen 5 1600 Six-Core Processor, 3200 Mhz, 6 Núcleo(s), 12 Processador(es) Lógico(s)
Versão/data do BIOS	American Megatrends Inc. P5.20, 06/03/2019
Versão do SMBIOS	3.2
Versão do Controlador Incorporado	255.255
Modo da BIOS	Herdado
Fabricante da BaseBoard	ASRock
Produto BaseBoard	A320M-HD
Versão da BaseBoard	
Função da Plataforma	Área de Trabalho
Estado da Inicialização Segura	Sem suporte
Configuração PCR7	Ligação Impossível
Pasta do Windows	C:\WINDOWS
Pasta do sistema	C:\WINDOWS\system32
Dispositivo de inicialização	\Device\HarddiskVolume2
Localidade	Brasil
Camada de Abstração de Hardware	Versão = "10.0.19041.2728"
Nome de usuário	DESKTOP-4E8VNNQ\guica
Fuso horário	Hora oficial do Brasil
Memória Física (RAM) Instalada	16.0 GB
Memória física total	15.9 GB
Memória física disponível	5.45 GB
Memória virtual total	24.9 GB
Memória virtual disponível	10.1 GB
Espaço do arquivo de paginação	9.00 GB
Arquivo de paginação	C:\pagefile.sys
Proteção de DMA de Kernel	Desativado
Segurança baseada em virtualização	Em Execução
Propriedades de Segurança Obrigatórias da segurança baseada em virtualização	
Propriedades de Segurança Disponíveis da segurança baseada em virtualização	Suporte para Virtualização de Base, Proteção DMA, SMM Security Mitigations 1.0
Serviços de segurança baseada em virtualização configurados	
Serviços de segurança baseada em virtualização em execução	
Suporte à Criptografia de Dispositivo	Motivos da falha da criptografia de dispositivo automática: TPM não utilizável, Associação PCR7 não compatível, Falha na Interface de Teste de Segurança de Hardware, e o dispositivo não está em Espera Moderna, Barramento/dispositivos compatíveis com DMA não permitidos detectados, TPM não utilizável
Um hipervisor foi detectado. Recursos necessários para o Hyper-V não serão exibidos.

**Comment by MustardChef** [comment]
@guicamarotto Hello. I am sorry to hear that you are having issues with game applications being very slow. The reality is that I cannot do anything to fix this. All I do is provide WSA builds and have no involvement in the development of WSA. These slowdowns are due to WSA and therefore I will have to close this issue.

If you think this is a mistake, feel free to reopen this issue.
