### ISSUE TITLE
userdata.vhdx not shrinking after uninstalling apps [BUG]

### ISSUE THREAD

**Issue by Astra060** [MustardChef/WSABuilds#132]
### Describe the bug | 描述一下这个错误

I tested this today with installing and uninstalling a 300MB application, the size increases once, but after uninstalling the userdata.vhdx size does not decrease to before the program installation. It's like program remains as cache. because after reinstalling the program again the size of the file does not change.

### Steps to reproduce the issue | 重现该问题的步骤

install any APK once - PacMan was used for the installtion
check userdata.vhdx

### Expected behaviour | 预期的行为

the file should change size as this wastes a lot of space

### Downloaded Build Of WSA | 已下载的WSA版本

[WSA_2305.40000.6.0_arm64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.zip](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2305.40000.6.0_arm64/WSA_2305.40000.6.0_arm64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.zip)
806 M

### Windows build number | Windows构建号

21h2 19044.2965

### PC Specification | 个人电脑规格

Ryzen 4800h
2060m
NVMe

**Comment by MustardChef** [comment]
@Astra060 Hello, thank you for your issue.

This is a known scenario and whether it or not it is intended to be like this (by design) is not known. Unfortunately, I know of no method to reduce the file size of Userdata.vhdx.

**Comment by YT-Advanced** [comment]
You can compact VHDX by run `Compaxt-VHDX Path\to\file` command in Powershell

**Comment by Mitia99** [comment]
> You can compact VHDX by run `Compaxt-VHDX` command in Powershell

Is it safe?

**Comment by Snowlights2022** [comment]
Now the issue complexed. The WSA `userdata.2.vhdx` is encrypted and I cannot use cmdlet `Optimize-vhd` (A advanced command of cmdlet above). Is there any more ways? And, can we bypass this by backup under the [instructions](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/Backup%20and%20Restore.md) from README?
