### ISSUE TITLE
[REQUEST] pass safetynet

### ISSUE THREAD

**Issue by xAffan** [MustardChef/WSABuilds#133]
### Describe your request | 描述您的要求

brunch framework with debugging off can pass safetynet. safetynet without hardware attestation is crackable. Why not do something?

**Comment by MustardChef** [comment]
@xAffan Hello, thank you for opening an issue.

Unfortunately, it is impossible for me (as I do not have the expertise) to attempt to crack safetynet. Nor do I know of any Windows Android emulators, that are able to bypass Safetynet. FYI, this is not the best place to ask. It may be possible, however I cannot do anything to achieve it.

Sorry if this is not the answer you are looking for.
