### ISSUE TITLE
[BUG] Wifi connection speed is set to 1Mbps, slow internet.

### ISSUE THREAD

**Issue by nDman** [MustardChef/WSABuilds#134]
### Describe the bug | 描述一下这个错误

The speed of **VirtWifi** is 1Mbps and network connection works very slowly.

### Steps to reproduce the issue | 重现该问题的步骤

Just installed OS freshly.

### Expected behaviour | 预期的行为

It should work with system network speed.

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2305.40000.6.0_x64_Release-Nightly-with-kernelsu-v0.6.2-MindTheGapps-13.0-RemovedAmazon

### Windows build number | Windows构建号

Version 22H2 Build 22621.1992

### PC Specification | 个人电脑规格

OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	ASUS
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz, 2501 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 0820, 27/04/2021
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	ROG STRIX B560-F GAMING WIFI
BaseBoard Version	Rev 1.xx
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.1413"
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	61.3 GB
Available Physical Memory	43.9 GB
Total Virtual Memory	77.0 GB
Available Virtual Memory	52.9 GB
Page File Space	15.6 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
Virtualization-based security Services Running	Credential Guard, Hypervisor enforced Code Integrity
Device Encryption Support	Elevation Required to View

**Comment by MustardChef** [comment]
@nDman 
- What internet speed do you get on Windows 11?
- Do you have another firewall, other than Windows Firewall?
- Does the same issue happen with the official versions of WSA (from the Microsoft Store or [WSAPackages](https://github.com/MustardChef/WSAPackages)?

**Comment by nDman** [comment]
@MustardChef 

- My windows internet speed is 16Mbps
- If use Kaspersky firewall, but it is slow with windows firewall too.
- No, official was fine and now I use version **WSA_2304.40000.10.0_x64_Release-Nightly-with-magisk-47d2d4e3(26102)-canary-MindTheGapps-13.0-RemovedAmazon** of your's and it is  fine.

[Screenshot of VirtWifi info](https://i.imgur.com/9wQ86ZF.jpg)

**Comment by guicaiyue** [comment]
I am also very stuck, I just uninstall the official and then install Windows_11_WSA_2306.40000.4.0_x64 version, but the browser or app loading is very stuck, wifi is also 1Mbps. But using the SendTest app, you can get speeds of 40-70Mbps. However, this does not affect the slow loading and even timeout of abnormal details when I access other apps

**Comment by guicaiyue** [comment]
Replenishment
![动画](https://github.com/MustardChef/WSABuilds/assets/43875377/b3f77936-8c76-430d-824e-1bbe8aebf21f)
![测速](https://github.com/MustardChef/WSABuilds/assets/43875377/d241f251-3767-48fa-810a-717cee922603)
![image](https://github.com/MustardChef/WSABuilds/assets/43875377/a2e69fe0-2583-496a-88e4-6cbafce13d13)

**Comment by MustardChef** [comment]
@guicaiyue 
- So, the internet on the official version works fine?
- Also, have to tried changing the Private DNS on WSA to "dns.google"?
- Have your tried disconnecting and reconnecting to Virtwifi?

---

FYI: It also shows the "Transmit Link Speed" as "1 Mbps", which means that this is normal on WSA
However, I am getting the full speed when running a speed test in the Firefox Browser on WSA. 

_See below:_

### **Transmit Speed for Virtwifi:**

![image](https://github.com/MustardChef/WSABuilds/assets/68516357/7e7f860a-e089-43c7-8fb2-8ece1653b7da)

### **Speed Test (Firefox Android (On WSA)):**

![image](https://github.com/MustardChef/WSABuilds/assets/68516357/dfb1d3d3-9880-435c-9d6c-f608b2858c48)

### **Speed Test (Firefox for Windows 11 x86)**

![image](https://github.com/MustardChef/WSABuilds/assets/68516357/01e8cf10-51dc-43c8-af4b-b69b8e509442)

**Comment by guicaiyue** [comment]
@MustardChef 
The official version is fine
I've been running tests today and it seems to have something to do with agency
I do need to proxy the network using the Burp Sutie tool, and when I use adb commands or manually configure the proxy on VirtWifi, the network goes down
![代理](https://github.com/MustardChef/WSABuilds/assets/43875377/a5d8df44-7b1b-4068-91cf-f56754b7e3d4)

**Comment by jiuqianyuan** [comment]
> @MustardChef The official version is fine I've been running tests today and it seems to have something to do with agency I do need to proxy the network using the Burp Sutie tool, and when I use adb commands or manually configure the proxy on VirtWifi, the network goes down ![代理](https://user-images.githubusercontent.com/43875377/255396067-a5d8df44-7b1b-4068-91cf-f56754b7e3d4.gif)

I also encountered the same problem, how did you solve it in the end?
![1](https://github.com/MustardChef/WSABuilds/assets/39406781/5fd67bd1-7aad-46a8-8111-1322ed38b3f4)

**Comment by MustardChef** [comment]
> I also encountered the same problem, how did you solve it in the end? WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10
> 
> ![1](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)

WSA showing "1 Mbps" for the Transmit Speed in settings, is normal, by the looks of it.

What speed are you getting in a browser on WSA.

**Comment by jiuqianyuan** [comment]
> > 我也遇到了同样的问题，请问最后是怎么解决的呢？WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-已删除Amazon_Windows_10
> > ![1](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> >       
> >         [
> >           
> >         
> >             ![1](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> >           ](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> 
> 从外观上看，WSA 在设置中显示传输速度为“1 Mbps”，这是正常的。
> 
> 您在 WSA 上的浏览​​器的速度是多少？



> > 我也遇到了同样的问题，请问最后怎么解决的呢？WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-已删除Amazon_Windows_10
> > ![1](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> >       
> >         [
> >           
> >         
> >             ![1](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> >           ](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/39406781/261413481-5fd67bd1-7aad-46a8-8111-1322ed38b3f4.gif)
> 
> 从外观上看，WSA在设置中显示传输速度为“1 Mbps”，这是正常的。
> 
> 您在WSA上的浏览器的速度是多少？

Only 20Mbps, but I actually have 300Mbps

**Comment by jiuqianyuan** [comment]
> WSA showing "1 Mbps" for the Transmit Speed in settings, is normal, by the looks of it.
> 
> What speed are you getting in a browser on WSA?

There seems to be a problem with the dns. Every time I disconnect, it returns to 172.28.32.1. After I changed to the available dns, the speed measurement of Firefox is only 20mbps, but the speed of Chrome is 300. Different applications have different network speeds and delays, which is very confusing.

**Comment by jiuqianyuan** [comment]
> WSA showing "1 Mbps" for the Transmit Speed in settings, is normal, by the looks of it.
> 
> What speed are you getting in a browser on WSA?

There seems to be a problem with the dns. Every time I disconnect, it returns to 172.28.32.1. After I changed to the available dns, the speed measurement of Firefox is only 20mbps, but the speed of Chrome is 300. Different applications have different network speeds and delays, which is very confusing.
