### ISSUE TITLE
[BUG] not work on windows 10 Version 22H2 (OS Build 19045.3208)

### ISSUE THREAD

**Issue by MesterPerfect** [MustardChef/WSABuilds#140]
### Describe the bug | 描述一下这个错误

I have downloaded this project
I installed it but it didn't work for me
After completing the installation and trying to open any of the services
The loading screen appears and then disappears

### Steps to reproduce the issue | 重现该问题的步骤

1. Download this file: WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip
2. Extract the content of the zip file to the wsa folder in C drive:
3. Run the run.bat file as administrator
4. Launch Windows Subsystem for Android™ from the start menu
5. Click on the open File button
6. The loading screen appears for a few seconds and then disappears

### Expected behaviour | 预期的行为

Run service WSA and view files

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip
https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2306.40000.4.0

### Windows build number | Windows构建号

Version 22H2 (OS Build 19045.3208)

### PC Specification | 个人电脑规格
* OS Name	Microsoft Windows 10 Pro
* Version	10.0.19045 Build 19045
* Other OS Description 	Not Available
* OS Manufacturer	Microsoft Corporation
* System Name	DESKTOP-7H44AN3
* System Manufacturer	HP
* System Model	HP EliteDesk 800 G2 TWR
* System Type	x64-based PC
* System SKU	L1G77AV
* Processor	Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, 3192 Mhz, 4 Core(s), 4 Logical Processor(s)
* BIOS Version/Date	HP N01 Ver. 02.58, 28/07/2022
* SMBIOS Version	2.7
* Embedded Controller Version	5.57
* BIOS Mode	UEFI
* BaseBoard Manufacturer	HP
* BaseBoard Product	8053
* BaseBoard Version	KBC Version 05.39
* Platform Role	Desktop
* Secure Boot State	Off
* PCR7 Configuration	Elevation Required to View
* Windows Directory	C:\windows
* System Directory	C:\windows\system32
* Boot Device	\Device\HarddiskVolume7
* Locale	Egypt
* Hardware Abstraction Layer	Version = "10.0.19041.2728"
* User Name	DESKTOP-7H44AN3\MesterPerfect
* Time Zone	Egypt Daylight Time
* Installed Physical Memory (RAM)	8.00 GB
* Total Physical Memory	7.88 GB
* Available Physical Memory	3.73 GB
* Total Virtual Memory	8.38 GB
* Available Virtual Memory	4.10 GB
* Page File Space	512 MB
* Page File	C:\pagefile.sys
* Kernel DMA Protection	Off
* Virtualization-based security	Running
* Virtualization-based security Required Security Properties	
* Virtualization-based security Available Security Properties	Base Virtualization Support
* Virtualization-based security Services Configured	
* Virtualization-based security Services Running	
* Device Encryption Support	Elevation Required to View

[PCinfo.txt](https://github.com/MustardChef/WSABuilds/files/12131027/PCinfo.txt)

### Additional context | 额外的背景

subsystem for android works very well for me on Windows 11 and on the same computer

**Comment by rexlManu** [comment]
I have the same version like the issue Author and receive a error that is related to it.

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_2307.40000.3.0_x64__8wekyb3d8bbwe
because this package is not compatible with the device. The package requires OS version 10.0.22000.120 or higher on
the Windows.Desktop device family. The device is currently running OS version 10.0.19045.3208.
NOTE: For additional information, look for [ActivityId] 7c29d057-c9b2-000f-1af3-2b7cb2c9d901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 7c29d057-c9b2-000f-1af3-2b7cb2c9d901
At C:\Users\rexlManu\WSA\Install.ps1:170 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\rexlManu\WSA\AppxManifest.xml:String) [Add-AppxPackage], Excepti
   on
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

```

**Comment by MustardChef** [comment]
> I have the same version like the issue Author and receive a error that is related to it.
> 
> ```
> Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
> Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_2307.40000.3.0_x64__8wekyb3d8bbwe
> because this package is not compatible with the device. The package requires OS version 10.0.22000.120 or higher on
> the Windows.Desktop device family. The device is currently running OS version 10.0.19045.3208.
> NOTE: For additional information, look for [ActivityId] 7c29d057-c9b2-000f-1af3-2b7cb2c9d901 in the Event Log or use
> the command line Get-AppPackageLog -ActivityID 7c29d057-c9b2-000f-1af3-2b7cb2c9d901
> At C:\Users\rexlManu\WSA\Install.ps1:170 char:1
> + Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (C:\Users\rexlManu\WSA\AppxManifest.xml:String) [Add-AppxPackage], Excepti
>    on
>     + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
> ```
> 
> Activitylog is empty

@rexlManu Make sure you download the correct build of WSA for Windows 10. Currently, it seems that you have downloaded a build that is for Windows 11 only.

**Comment by MustardChef** [comment]
> up

@MesterPerfect Sorry for the really late reply. Please try the latest WSA Builds: 
https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2307.40000.3.0

**Comment by MesterPerfect** [comment]
> > up
> 
> @MesterPerfect Sorry for the really late reply. Please try the latest WSA Builds: https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2307.40000.3.0

I downloaded the latest build, but it doesn't work either. Is there a bug log so I can track problems from it?

**Comment by MustardChef** [comment]
> > > up
> > 
> > 
> > @MesterPerfect Sorry for the really late reply. Please try the latest WSA Builds: https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2307.40000.3.0
> 
> I downloaded the latest build, but it doesn't work either. Is there a bug log so I can track problems from it?

Check for any logcat logs in %LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalState\diagnostics\logcat

**Comment by rexlManu** [comment]
I found out how to solve my problem:

When running the `run.bat` it starts powershell 7 (what for me is default set up) but with that `Import-Module Appx` is unsupported. Instead try to launch `Windows Powershell` as admin and run the `Install.ps1`
