### ISSUE TITLE
need virtual camera (screen capture replace on camera)

### ISSUE THREAD

**Issue by cptalireza** [MustardChef/WSABuilds#142]
### Describe your request | 描述您的要求

need virtual camera (screen capture replace on camera) To scan login codes like WhatsApp code

**Comment by MustardChef** [comment]
@cptalireza 
#### Please refer to:

https://www.reddit.com/r/WSA/comments/14v88wc/comment/jreum6e/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by MustardChef** [comment]
I cannot do anything.

Best course of action:
File a Feedback Hub Report:
![image](https://github.com/MustardChef/WSABuilds/assets/68516357/30993ccd-8a2c-4288-bae8-15f8528f864e)
