### ISSUE TITLE
[BUG] Windows 10 22H2 play store not showing/installing on recently added apps.

### ISSUE THREAD

**Issue by rhyancm** [MustardChef/WSABuilds#143]
### Describe the bug | 描述一下这个错误

On my Windows 10 22H2 the play store is not appearing/installing in the recently added applications, I don't know exactly what's wrong, if it was my mistake or it's really a bug. 

### Steps to reproduce the issue | 重现该问题的步骤

default installation, according to tips from people on youtube

### Expected behaviour | 预期的行为

The play store appears for me to start

### Downloaded Build Of WSA | 已下载的WSA版本

[WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2306.40000.4.0/WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip)

### Windows build number | Windows构建号

22h2

### PC Specification | 个人电脑规格

10.0.19041.746

**Comment by MustardChef** [comment]
@rhyancm 
Hello, thank you for your issue.

From what I can see, you are not running 22H2 (based on the build number provided). I would recommend updating to the latest build of Windows 10 (via Windows 10 Updates or Update Assistant) then trying.

Also please provide me with your full PC specifications, as opposed to not providing any.

**Comment by MustardChef** [comment]
> I also recently installed the latest release and didn't found any Google Apps or services i think the release doesn't contain the Google apps and services please let me know if you found any solution for it.

@Leedeigo5 
- What are your system specs? 
- Does renaming the folder that contains the files (Run.bat etc.) to "WSA" fix the issue?
- What build did you download? Full name?
- Windows 10 build number (use winver)?
- Have you used WSA before?

**Comment by Lakshayrocks** [comment]
i have also the same issue....this WSA intalled but no Playstore was found ...my LAPTOP is Ryzen 3 3200u with WINDOWS 10 Single home VERSION 22H2

**Comment by SDThePsFan** [comment]
the same thing is happening to me

**Comment by Lakshayrocks** [comment]
> the same thing is happening to me

 Bro Wsa ended sapport to windoes 10....it will work only in windows 11
