### ISSUE TITLE
Relocating WSA folder

### ISSUE THREAD

**Issue by robbely** [MustardChef/WSABuilds#145]
### Describe the bug | 描述一下这个错误

-

### Steps to reproduce the issue | 重现该问题的步骤

-

### Expected behaviour | 预期的行为

-

### Downloaded Build Of WSA | 已下载的WSA版本

 WSA_2306.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0_Windows_10

### Windows build number | Windows构建号

Windows 10 19045.3208

### PC Specification | 个人电脑规格

-

### Additional context | 额外的背景

I have the WSA package installed in the default "My Documents" folder. If I wish to move it to somewhere else, do I need to uninstall/reinstall anything, simply run the bat file again, or is there something else would I need to do for WSA to work correctly from the new location?

**Comment by MustardChef** [comment]
@robbely You can turn off WSA via the settings, move the folder to a new location and run the "Run.bat" file. I would backup the Userdata.vhdx file just in case anything goes wrong.

**Comment by robbely** [comment]
Many thanks for the quick and helpful response :)

**Comment by robbely** [comment]
Just to add - I followed the instructions and it worked perfectly. Many thanks again :)
