### ISSUE TITLE
2301在我的电脑上无法启动

### ISSUE THREAD

**Issue by bzkmsjy** [MustardChef/WSABuilds#15]
我有两台电脑，一台是9900k+GTX1660TI的台式机，另一台是赛扬N5100+英特尔集成显卡的轻薄本，两台电脑是同时安装的Win11 22H2 22621.1194，各种运行库等软件环境完全一样，WSAbuild 2301.40000.4.0在9900k的电脑上正常启动，在N5100上无法启动，run.bat安装后play商店和magisk的启动画面会持续很久，然后退出，手动打开也无法启动，N5100的电脑覆盖安装2211.40000.11.0后可以正常使用

**Comment by MustardChef** [comment]
你好
这是一个非常不寻常的问题。请你在微软WSA官方Github上开一个问题，因为很多人都面临这个问题，我不知道是什么原因造成的。这样问题会更快得到解决

(Machine Translated)
