### ISSUE TITLE
[BUG] can't run android system webview properly

### ISSUE THREAD

**Issue by Ben-md5** [MustardChef/WSABuilds#153]
### Describe the bug | 描述一下这个错误

在系统内安装android system webview后，在google应用内使用“在应用内打开网页”功能，网页加载错误

### Steps to reproduce the issue | 重现该问题的步骤

1.安装Android system webview
2.安装chrome，在google内使用在应用内打开网页功能
3.在google内开启任意网页，网页无法加载

### Expected behaviour | 预期的行为

网页正常加载

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2306.40000.4.0_x64_Release-Nightly-with-magisk-d390ca2f(26104)-canary-MindTheGapps-13.0-RemovedAmazon

### Windows build number | Windows构建号

22621.2134

### PC Specification | 个人电脑规格

处理器	13th Gen Intel(R) Core(TM) i9-13900HX   2.20 GHz
机带 RAM	16.0 GB (15.7 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
legion Y9000P IRX8

**Comment by hunanflyer** [comment]
the same with mine
