### ISSUE TITLE
About the VPN Dialogs [REQUEST]

### ISSUE THREAD

**Issue by g1246035176** [MustardChef/WSABuilds#155]
### Describe your request | 描述您的要求

The WSA Builds does not contain the vpndialogs that the LSPOSED team built to fix the vpn issue.
It is now not able to open vpn like clash or v2rayNG‘s dialogs.

**Comment by MustardChef** [comment]
@g1246035176 Thank you for your issue, I will add this in the next update of WSA. I will inform you when builds are uploaded.

**Comment by g1246035176** [comment]
Many thanks to you!

**Comment by MustardChef** [comment]
@g1246035176 I know it has been two weeks since your last comment, but VPNDialogs has been readded in the v2307.40000.6.0.

**Comment by pedrocacintra** [comment]
Hello, ive downloaded the most recent build, but couldnt get VPN to work, any ideas?
