### ISSUE TITLE
[BUG] Backup and restore userdata.vhdx not working

### ISSUE THREAD

**Issue by Mitia99** [MustardChef/WSABuilds#156]
### Describe the bug | 描述一下这个错误

Backup an restore `userdata.vhdx` not working on latest stable WSA and latest stable Windows 11 X64
![Backup not working](https://github.com/MustardChef/WSABuilds/assets/56766778/d01a440e-96bb-480a-99e2-e44427d431cf)

### Steps to reproduce the issue | 重现该问题的步骤

Follow the [guide in readme](https://github.com/MustardChef/WSABuilds#--backup-and-restore-userdata)
1.  Uninstall WSA
2. Remove lines in `install.ps1` (Android Settings, Official Magisk, Google Play Store)
3. Run `Run.bat` as administrator
4. Don't run WSA
5. Paste userdata.vhdx to `%localappdata%\...`
6. Run WSA and open `Files`

### Expected behaviour | 预期的行为

WSA Working with data restored

### Downloaded Build Of WSA | 已下载的WSA版本

[WSA_2306.40000.4.0_x64_Release-Nightly-with-magisk-ee34f775.26105.-canary-MindTheGapps-13.0-RemovedAmazon](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2306.40000.4.0/WSA_2306.40000.4.0_x64_Release-Nightly-with-magisk-ee34f775.26105.-canary-MindTheGapps-13.0-RemovedAmazon.7z)

### Windows build number | Windows构建号

Windows 11 Pro 22H2  22621.2134

### PC Specification | 个人电脑规格

CPU: i5 1130G7
RAM: 16 Go
SSD: M2 NVME 512 Go

### Additional context | 额外的背景

Same issue with [WSA_2307.40000.5.0_x64_Release-Nightly-with-magisk-ee34f775.26105.-canary-MindTheGapps-13.0-RemovedAmazon](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2307.40000.5.0/WSA_2307.40000.5.0_x64_Release-Nightly-with-magisk-ee34f775.26105.-canary-MindTheGapps-13.0-RemovedAmazon.7z)
WSA works if I don't restore `userdata.vhdx`

### Logcat
--------- beginning of main
08-17 05:57:01.600    26    26 I lowmemorykiller: Using psi monitors for memory pressure detection
08-17 05:57:01.600    26    26 I lowmemorykiller: Process polling is supported
08-17 05:57:01.602    26    26 I lowmemorykiller: Process reaper initialized with 2 threads in the pool
--------- beginning of events
08-17 05:57:01.607    27    27 I snet_event_log: [121035042,-1,]
08-17 05:57:01.611    27    27 W SELinux : Multiple same specifications for android.hardware.camera.provider.ICameraProvider/internal/0.
08-17 05:57:01.611    27    27 I auditd  : Multiple same specifications for android.hardware.camera.provider.ICameraProvider/internal/0.
08-17 05:57:01.611    27    27 I SELinux : SELinux: Loaded service_contexts from:
08-17 05:57:01.611    27    27 I auditd  : SELinux: Loaded service_contexts from:
08-17 05:57:01.611    27    27 I SELinux :     /system/etc/selinux/plat_service_contexts
08-17 05:57:01.611    27    27 I auditd  :     /system/etc/selinux/plat_service_contexts
08-17 05:57:01.611    27    27 I SELinux :     /system_ext/etc/selinux/system_ext_service_contexts
08-17 05:57:01.611    27    27 I auditd  :     /system_ext/etc/selinux/system_ext_service_contexts
08-17 05:57:01.611    27    27 I SELinux :     /product/etc/selinux/product_service_contexts
08-17 05:57:01.611    27    27 I auditd  :     /product/etc/selinux/product_service_contexts
08-17 05:57:01.611    27    27 I SELinux :     /vendor/etc/selinux/vendor_service_contexts
08-17 05:57:01.611    27    27 I auditd  :     /vendor/etc/selinux/vendor_service_contexts
08-17 05:56:59.020    25    25 I auditd  : type=2000 audit(0.0:1): state=initialized audit_enabled=0 res=1
08-17 05:56:59.020    25    25 W auditd  : type=2000 audit(0.0:1): state=initialized audit_enabled=0 res=1
08-17 05:57:00.717    25    25 I auditd  : type=1403 audit(0.0:2): auid=4294967295 ses=4294967295 lsm=selinux res=1
08-17 05:57:00.717    25    25 W auditd  : type=1403 audit(0.0:2): auid=4294967295 ses=4294967295 lsm=selinux res=1
08-17 05:57:00.727    25    25 I auditd  : type=1404 audit(0.0:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295 enabled=1 old-enabled=1 lsm=selinux res=1
08-17 05:57:00.727    25    25 W auditd  : type=1404 audit(0.0:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295 enabled=1 old-enabled=1 lsm=selinux res=1
08-17 05:57:01.617    28    28 I hwservicemanager: getFrameworkHalManifest: Reading VINTF information.
08-17 05:57:01.622    28    28 I hwservicemanager: getDeviceHalManifest: Reading VINTF information.
08-17 05:57:01.628    28    28 I hwservicemanager: getDeviceHalManifest: Successfully processed VINTF information
08-17 05:57:01.628    28    28 I hwservicemanager: getFrameworkHalManifest: Successfully processed VINTF information
08-17 05:57:01.628    28    28 I hwservicemanager: hwservicemanager is ready now.
--------- beginning of system
08-17 05:57:01.748    38    38 I vold    : Vold 3.0 (the awakening) firing up
08-17 05:57:01.753    38    42 I Checkpoint: Validating checkpoint on /dev/block/sde
08-17 05:57:01.753    38    42 E Checkpoint: No magic
08-17 05:57:01.767    28    28 E cutils-trace: Error opening trace file: No such file or directory (2)
08-17 05:57:01.767    28    28 I hwservicemanager: getTransport: Cannot find entry android.hardware.boot@1.0::IBootControl/default in either framework or device VINTF manifest.
08-17 05:57:02.534    45    45 I virtio_ports_create_links: Completed successfully.
08-17 05:57:02.667    27    27 I servicemanager: getDeviceHalManifest: Reading VINTF information.
08-17 05:57:02.668    27    27 I servicemanager: getDeviceHalManifest: Successfully processed VINTF information
08-17 05:57:02.668    27    27 I servicemanager: getFrameworkHalManifest: Reading VINTF information.
08-17 05:57:02.668    27    27 I servicemanager: getFrameworkHalManifest: Successfully processed VINTF information
08-17 05:57:02.668    27    27 I servicemanager: Found android.system.suspend.ISystemSuspend/default in framework VINTF manifest.
08-17 05:57:02.669    28    28 I hwservicemanager: getTransport: Cannot find entry android.system.suspend@1.0::ISystemSuspend/default in either framework or device VINTF manifest.
08-17 05:57:02.669    47    47 E HidlServiceManagement: Service android.system.suspend@1.0::ISystemSuspend/default must be in VINTF manifest in order to register/get.
08-17 05:57:02.669    47    47 I android.system.suspend@1.0-service: system-suspend HIDL hal not supported, use the AIDL suspend hal for requesting wakelocks
08-17 05:57:02.686    55    55 I fsverity_init: LoadKeyFromFile path=/system/etc/security/fsverity/fsverity-release.x509.der keyname=fsv_system_0
08-17 05:57:02.688    55    55 I fsverity_init: LoadKeyFromFile path=/product/etc/security/fsverity/play_store_fsi_cert.der keyname=fsv_product_0
08-17 05:57:02.688    52    52 I GSKServerConnection: GSKServerConnection service is starting
08-17 05:57:02.688    53    53 I RemoteConnectionManager: RemoteConnectionManager service is starting for instance default
08-17 05:57:02.689    27    27 I servicemanager: Found windows.services.graphics.IGSKServerConnection/default in device VINTF manifest.
08-17 05:57:02.689    52    52 I GSKServerConnection: Service default is ready
08-17 05:57:02.689    55    55 I fsverity_init: LoadKeyFromFile path=/product/etc/security/fsverity/gms_fsverity_cert.der keyname=fsv_product_1
08-17 05:57:02.690    27    27 I servicemanager: Found windows.services.rcm.IRemoteConnectionManager/default in device VINTF manifest.
08-17 05:57:02.690    53    53 I RemoteConnectionManager: Service default is ready
08-17 05:57:02.698    49    49 I keymaster:  patchlevel string does not match expected format.  Using patchlevel 0
08-17 05:57:02.699    49    49 I HidlServiceManagement: Registered android.hardware.keymaster@4.1::IKeymasterDevice/default
08-17 05:57:02.700    49    49 I HidlServiceManagement: Removing namespace from process name android.hardware.keymaster@4.1-service to keymaster@4.1-service.
08-17 05:57:02.713    60    60 I provision_apex: Provisioning apex
08-17 05:57:02.715    60    60 I provision_apex: Not opening /mnt/shared_tmp/apex (No such file or directory)
08-17 05:57:02.730    48    48 I keystore2: keystore2_main: Keystore2 is starting.
08-17 05:57:02.730    48    48 I keystore2: keystore2_main: Setting up sqlite logging for keystore2
08-17 05:57:02.733    48    48 W keystore2: keystore2::metrics_store: In update_keystore_crash_sysprop: Failed to read the existing system property due to: In read_keystore_crash_count: Property not set..Therefore, keystore crashes will not be logged.
08-17 05:57:02.735    48    48 I keystore2: keystore2_main: Starting thread pool now.
08-17 05:57:02.736    48    48 I keystore2: getDeviceHalManifest: Reading VINTF information.
08-17 05:57:02.737    38    38 I Checkpoint: cp_prepareCheckpoint called
08-17 05:57:02.738    48    48 I keystore2: getDeviceHalManifest: Successfully processed VINTF information
08-17 05:57:02.743    48    48 I keystore2: found android.hardware.keymaster@4.0::IKeymasterDevice with interface name default and seclevel SOFTWARE
08-17 05:57:02.744    28    28 I hwservicemanager: getTransport: Cannot find entry android.hardware.keymaster@3.0::IKeymasterDevice/default in either framework or device VINTF manifest.
08-17 05:57:02.744    48    48 W keystore2: No secure Keymaster implementation found, but device offers insecure Keymaster HAL. Using as default.
08-17 05:57:02.745    48    48 I keymaster:  patchlevel string does not match expected format.  Using patchlevel 0
08-17 05:57:02.745    48    48 I keystore2: keystore2::globals: Add emulation wrapper around Keymaster device for security level: SecurityLevel(1)
08-17 05:57:02.745    48    48 I keymaster:  patchlevel string does not match expected format.  Using patchlevel 0
08-17 05:57:02.745    48    62 I keystore2: keystore2::shared_secret_negotiation: Shared secret negotiation concluded successfully.
08-17 05:57:02.746    27    27 I servicemanager: Found android.system.keystore2.IKeystoreService/default in framework VINTF manifest.
08-17 05:57:02.746    48    62 I keystore2: keystore2::shared_secret_negotiation: No StrongBox Keymint available, so no RoT transfer
08-17 05:57:02.747    48    48 I keystore2: keystore2_main: Not publishing IRemotelyProvisionedKeyPool service: In new_native_binder: Failed to get TEE Remote Provisioner instance.
08-17 05:57:02.747    48    48 I keystore2: 
08-17 05:57:02.747    48    48 I keystore2: Caused by:
08-17 05:57:02.747    48    48 I keystore2:     0: In get_remotely_provisioned_component.
08-17 05:57:02.747    48    48 I keystore2:     1: In connect_remotely_provisioned_component.
08-17 05:57:02.747    48    48 I keystore2:     2: Error::Km(ErrorCode(-68))
08-17 05:57:02.747    48    48 I keystore2: keystore2_main: Successfully registered Keystore 2.0 service.
08-17 05:57:02.747    48    48 I keystore2: keystore2_main: Joining thread pool now.
08-17 05:57:02.758    38    38 I vold    : fscrypt_initialize_systemwide_keys
08-17 05:57:02.767    48    48 I SELinux : SELinux: Loaded keystore2_key_contexts from:
08-17 05:57:02.767    48    48 I auditd  : SELinux: Loaded keystore2_key_contexts from:
08-17 05:57:02.767    48    48 I SELinux :     /system/etc/selinux/plat_keystore2_key_contexts
08-17 05:57:02.767    48    48 I auditd  :     /system/etc/selinux/plat_keystore2_key_contexts
08-17 05:57:02.770    38    38 I vold    : Upgrading key: /data/unencrypted/key/keymaster_key_blob
08-17 05:57:02.770    38    38 E vold    : Failed to open /data/unencrypted/key/keymaster_key_blob_upgraded: Permission denied
08-17 05:57:02.776    38    38 E vold    : decryptWithKeystoreKey failed

**Comment by coocv** [comment]
不知道你是否和我遇到相同的[问题](https://github.com/MustardChef/WSABuilds/issues/154#issuecomment-1679869203)，在我电脑中它叫userdata.2.vhdx而不是userdata.vhdx

**Comment by Mitia99** [comment]
> I don't know if you have the same [problem](https://github.com/MustardChef/WSABuilds/issues/154#issuecomment-1679869203) as me, but on my computer it is called userdata.2.vhdx instead of userdata.vhdx

My data is called `userdata.vhdx`

**Comment by MustardChef** [comment]
> > I don't know if you have the same [problem](https://github.com/MustardChef/WSABuilds/issues/154#issuecomment-1679869203) as me, but on my computer it is called userdata.2.vhdx instead of userdata.vhdx
> 
> My data name is `userdata.vhdx`

**Comment by Mitia99** [comment]
I tried with older version [WSA_2305.40000.6.0_x64_Release-Nightly-with-magisk-a8c4a33e.26103.-canary-MindTheGapps-13.0-RemovedAmazon](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2305.40000.6.0/WSA_2305.40000.6.0_x64_Release-Nightly-with-magisk-a8c4a33e.26103.-canary-MindTheGapps-13.0-RemovedAmazon.zip) but still not working.

Maybe it has something to do with latest windows 11 update, I don't know.
I hope that the logcat I provided can help you investigate

**Comment by Mitia99** [comment]
Still not working with Windows 11 22H2 22621.2215 and [WSA 2307.40000.6.0 x64](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2307.40000.6.0/WSA_2307.40000.6.0_x64_Release-Nightly-with-magisk-de00f1d5.26202.-canary-MindTheGapps-13.0-RemovedAmazon.7z)

**Logcat**
--------- beginning of main
09-01 05:18:15.970    26    26 I lowmemorykiller: Using psi monitors for memory pressure detection
09-01 05:18:15.970    26    26 I lowmemorykiller: Process polling is supported
09-01 05:18:15.971    26    26 I lowmemorykiller: Process reaper initialized with 2 threads in the pool
--------- beginning of events
09-01 05:18:15.974    27    27 I snet_event_log: [121035042,-1,]
09-01 05:18:15.976    27    27 W SELinux : Multiple same specifications for android.hardware.camera.provider.ICameraProvider/internal/0.
09-01 05:18:15.976    27    27 I auditd  : Multiple same specifications for android.hardware.camera.provider.ICameraProvider/internal/0.
09-01 05:18:15.977    27    27 I SELinux : SELinux: Loaded service_contexts from:
09-01 05:18:15.977    27    27 I auditd  : SELinux: Loaded service_contexts from:
09-01 05:18:15.977    27    27 I SELinux :     /system/etc/selinux/plat_service_contexts
09-01 05:18:15.977    27    27 I auditd  :     /system/etc/selinux/plat_service_contexts
09-01 05:18:15.977    27    27 I SELinux :     /system_ext/etc/selinux/system_ext_service_contexts
09-01 05:18:15.977    27    27 I auditd  :     /system_ext/etc/selinux/system_ext_service_contexts
09-01 05:18:15.977    27    27 I SELinux :     /product/etc/selinux/product_service_contexts
09-01 05:18:15.977    27    27 I auditd  :     /product/etc/selinux/product_service_contexts
09-01 05:18:15.977    27    27 I SELinux :     /vendor/etc/selinux/vendor_service_contexts
09-01 05:18:15.977    27    27 I auditd  :     /vendor/etc/selinux/vendor_service_contexts
09-01 05:18:15.981    28    28 I hwservicemanager: getFrameworkHalManifest: Reading VINTF information.
09-01 05:18:10.020    25    25 I auditd  : type=2000 audit(0.0:1): state=initialized audit_enabled=0 res=1
09-01 05:18:10.020    25    25 W auditd  : type=2000 audit(0.0:1): state=initialized audit_enabled=0 res=1
09-01 05:18:14.979    25    25 I auditd  : type=1403 audit(0.0:2): auid=4294967295 ses=4294967295 lsm=selinux res=1
09-01 05:18:14.979    25    25 W auditd  : type=1403 audit(0.0:2): auid=4294967295 ses=4294967295 lsm=selinux res=1
09-01 05:18:14.989    25    25 I auditd  : type=1404 audit(0.0:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295 enabled=1 old-enabled=1 lsm=selinux res=1
09-01 05:18:14.989    25    25 W auditd  : type=1404 audit(0.0:3): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295 enabled=1 old-enabled=1 lsm=selinux res=1
09-01 05:18:15.989    28    28 I hwservicemanager: getDeviceHalManifest: Reading VINTF information.
09-01 05:18:15.998    28    28 I hwservicemanager: getDeviceHalManifest: Successfully processed VINTF information
09-01 05:18:15.998    28    28 I hwservicemanager: getFrameworkHalManifest: Successfully processed VINTF information
09-01 05:18:15.999    28    28 I hwservicemanager: hwservicemanager is ready now.
--------- beginning of system
09-01 05:18:16.131    38    38 I vold    : Vold 3.0 (the awakening) firing up
09-01 05:18:16.138    38    40 I Checkpoint: Validating checkpoint on /dev/block/sde
09-01 05:18:16.138    38    40 E Checkpoint: No magic
09-01 05:18:16.158    28    28 E cutils-trace: Error opening trace file: No such file or directory (2)
09-01 05:18:16.158    28    28 I hwservicemanager: getTransport: Cannot find entry android.hardware.boot@1.0::IBootControl/default in either framework or device VINTF manifest.
09-01 05:18:16.532    46    46 I virtio_ports_create_links: Completed successfully.
09-01 05:18:16.602    27    27 I servicemanager: getDeviceHalManifest: Reading VINTF information.
09-01 05:18:16.604    27    27 I servicemanager: getDeviceHalManifest: Successfully processed VINTF information
09-01 05:18:16.604    27    27 I servicemanager: getFrameworkHalManifest: Reading VINTF information.
09-01 05:18:16.604    27    27 I servicemanager: getFrameworkHalManifest: Successfully processed VINTF information
09-01 05:18:16.604    27    27 I servicemanager: Found android.system.suspend.ISystemSuspend/default in framework VINTF manifest.
09-01 05:18:16.605    28    28 I hwservicemanager: getTransport: Cannot find entry android.system.suspend@1.0::ISystemSuspend/default in either framework or device VINTF manifest.
09-01 05:18:16.605    48    48 E HidlServiceManagement: Service android.system.suspend@1.0::ISystemSuspend/default must be in VINTF manifest in order to register/get.
09-01 05:18:16.605    48    48 I android.system.suspend@1.0-service: system-suspend HIDL hal not supported, use the AIDL suspend hal for requesting wakelocks
09-01 05:18:16.610    56    56 I fsverity_init: LoadKeyFromFile path=/system/etc/security/fsverity/fsverity-release.x509.der keyname=fsv_system_0
09-01 05:18:16.612    56    56 I fsverity_init: LoadKeyFromFile path=/product/etc/security/fsverity/play_store_fsi_cert.der keyname=fsv_product_0
09-01 05:18:16.613    56    56 I fsverity_init: LoadKeyFromFile path=/product/etc/security/fsverity/gms_fsverity_cert.der keyname=fsv_product_1
09-01 05:18:16.614    51    51 I GSKServerConnection: GSKServerConnection service is starting
09-01 05:18:16.614    52    52 I RemoteConnectionManager: RemoteConnectionManager service is starting for instance default
09-01 05:18:16.614    27    27 I servicemanager: Found windows.services.graphics.IGSKServerConnection/default in device VINTF manifest.
09-01 05:18:16.614    51    51 I GSKServerConnection: Service default is ready
09-01 05:18:16.617    27    27 I servicemanager: Found windows.services.rcm.IRemoteConnectionManager/default in device VINTF manifest.
09-01 05:18:16.617    52    52 I RemoteConnectionManager: Service default is ready
09-01 05:18:16.620    50    50 I keymaster:  patchlevel string does not match expected format.  Using patchlevel 0
09-01 05:18:16.621    50    50 I HidlServiceManagement: Registered android.hardware.keymaster@4.1::IKeymasterDevice/default
09-01 05:18:16.621    50    50 I HidlServiceManagement: Removing namespace from process name android.hardware.keymaster@4.1-service to keymaster@4.1-service.
09-01 05:18:16.634    61    61 I provision_apex: Provisioning apex
09-01 05:18:16.635    61    61 I provision_apex: Not opening /mnt/shared_tmp/apex (No such file or directory)
09-01 05:18:16.642    49    49 I keystore2: keystore2_main: Keystore2 is starting.
09-01 05:18:16.642    49    49 I keystore2: keystore2_main: Setting up sqlite logging for keystore2
09-01 05:18:16.644    49    49 W keystore2: keystore2::metrics_store: In update_keystore_crash_sysprop: Failed to read the existing system property due to: In read_keystore_crash_count: Property not set..Therefore, keystore crashes will not be logged.
09-01 05:18:16.645    49    49 I keystore2: keystore2_main: Starting thread pool now.
09-01 05:18:16.645    49    49 I keystore2: getDeviceHalManifest: Reading VINTF information.
09-01 05:18:16.646    49    49 I keystore2: getDeviceHalManifest: Successfully processed VINTF information
09-01 05:18:16.648    38    40 I Checkpoint: cp_prepareCheckpoint called
09-01 05:18:16.649    49    63 I keystore2: found android.hardware.keymaster@4.0::IKeymasterDevice with interface name default and seclevel SOFTWARE
09-01 05:18:16.649    28    28 I hwservicemanager: getTransport: Cannot find entry android.hardware.keymaster@3.0::IKeymasterDevice/default in either framework or device VINTF manifest.
09-01 05:18:16.649    49    63 W keystore2: No secure Keymaster implementation found, but device offers insecure Keymaster HAL. Using as default.
09-01 05:18:16.650    49    49 I keymaster:  patchlevel string does not match expected format.  Using patchlevel 0
09-01 05:18:16.650    49    49 I keystore2: keystore2::globals: Add emulation wrapper around Keymaster device for security level: SecurityLevel(1)
09-01 05:18:16.650    49    49 I keymaster:  patchlevel string does not match expected format.  Using patchlevel 0
09-01 05:18:16.650    49    63 I keystore2: keystore2::shared_secret_negotiation: Shared secret negotiation concluded successfully.
09-01 05:18:16.651    27    27 I servicemanager: Found android.system.keystore2.IKeystoreService/default in framework VINTF manifest.
09-01 05:18:16.651    49    63 I keystore2: keystore2::shared_secret_negotiation: No StrongBox Keymint available, so no RoT transfer
09-01 05:18:16.652    49    49 I keystore2: keystore2_main: Not publishing IRemotelyProvisionedKeyPool service: In new_native_binder: Failed to get TEE Remote Provisioner instance.
09-01 05:18:16.652    49    49 I keystore2: 
09-01 05:18:16.652    49    49 I keystore2: Caused by:
09-01 05:18:16.652    49    49 I keystore2:     0: In get_remotely_provisioned_component.
09-01 05:18:16.652    49    49 I keystore2:     1: In connect_remotely_provisioned_component.
09-01 05:18:16.652    49    49 I keystore2:     2: Error::Km(ErrorCode(-68))
09-01 05:18:16.652    49    49 I keystore2: keystore2_main: Successfully registered Keystore 2.0 service.
09-01 05:18:16.652    49    49 I keystore2: keystore2_main: Joining thread pool now.
09-01 05:18:16.661    38    40 I vold    : fscrypt_initialize_systemwide_keys
09-01 05:18:16.666    49    49 I SELinux : SELinux: Loaded keystore2_key_contexts from:
09-01 05:18:16.666    49    49 I auditd  : SELinux: Loaded keystore2_key_contexts from:
09-01 05:18:16.666    49    49 I SELinux :     /system/etc/selinux/plat_keystore2_key_contexts
09-01 05:18:16.666    49    49 I auditd  :     /system/etc/selinux/plat_keystore2_key_contexts
09-01 05:18:16.668    38    40 I vold    : Upgrading key: /data/unencrypted/key/keymaster_key_blob
09-01 05:18:16.668    38    40 E vold    : Failed to open /data/unencrypted/key/keymaster_key_blob_upgraded: Permission denied
09-01 05:18:16.673    38    40 E vold    : decryptWithKeystoreKey failed

**Comment by Mitia99** [comment]
@MustardChef Fortunately, Apps restore are working well with [Neo Backup](https://github.com/NeoApplications/Neo-Backup)
Maybe it will be great to mention it in [Guide](https://github.com/MustardChef/WSABuilds#--backup-and-restore-userdata) cause restore userdata.vhdx isn't really reliable
