### ISSUE TITLE
[BUG]There is no wifi option in v2307.40000.5.0

### ISSUE THREAD

**Issue by chencl0214** [MustardChef/WSABuilds#159]
### Describe the bug | 描述一下这个错误

![Screenshot 2023-08-18 112050](https://github.com/MustardChef/WSABuilds/assets/24311314/88796758-34a1-4f0c-b3cb-d8ad9da24f42)

### Steps to reproduce the issue | 重现该问题的步骤

Advanced setting->Manage developer setting->click search->search WIFI->click WIFI->See the picture above

### Expected behaviour | 预期的行为

![Screenshot 2023-08-18 112743](https://github.com/MustardChef/WSABuilds/assets/24311314/852d8075-69aa-45f1-9ca6-57cff0eefa73)

### Downloaded Build Of WSA | 已下载的WSA版本

v2307.40000.5.0

### Windows build number | Windows构建号

22621.2213

### PC Specification | 个人电脑规格

![Screenshot 2023-08-18 112858](https://github.com/MustardChef/WSABuilds/assets/24311314/2ee5d4a3-eda1-4481-8d15-0a537da53345)

**Comment by MustardChef** [comment]
Thank you for opening an issue. Please can you try the fixes listed in this guide: https://github.com/MustardChef/WSABuilds/blob/master/Fixes/FixInternet.md.

**Comment by Snowlights2022** [comment]
> > @chencl0214感谢您提出问题。请尝试本指南中列出的修复：https://github.com/MustardChef/WSABuilds/blob/master/Fixes/FixInternet.md。
> 
> 我已经尝试过这些方法，但仍然没有效果。我将回滚到 v2307.40000.3.0。v2307.40000.3.0没有问题


Hello, I got it when I was trying to solve #165 . It is a problem of official WSA.(https://github.com/microsoft/WSA/issues/393)

**Comment by gy6221** [comment]
Similar issue found on 2307.40000.6.0, network is available on the first time to start WSA after host reboot. But if you stop WSA, and  start it again, network become unavailable.
