### ISSUE TITLE
[REQUEST] Clash of Clans Compatibility Issue Report for WSA_2307.40000.5.0_x64_Release-Nightly

### ISSUE THREAD

**Issue by tester2024** [MustardChef/WSABuilds#162]
### Describe your request | 描述您的要求

Hello,

I hope this message finds you well. I am reaching out to report a compatibility issue that I encountered while using the WSA_2307.40000.5.0_x64_Release-Nightly build on my device. The issue seems to be affecting the functionality of Clash of Clans, preventing it from opening successfully. I have collected relevant logs using logcat that I believe could provide valuable insights for troubleshooting and resolving this problem.

**Issue Summary:**
Upon attempting to open Clash of Clans, the application fails to launch due to an error related to file access. It appears that Clash of Clans is unable to access the following files, which are essential for its operation:

1. `/system/etc/cpuinfo.arm64.txt`
2. `/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/`

The logs indicate that there might be problems with file access and missing files, leading to the application's failure to start.

**Logcat:**
```log
<<< log_count = 28 >>>
[08-24 20:19:36.637 11119:11119 W/nativebridge]
Failed to bind-mount /system/etc/cpuinfo.arm64.txt as /proc/cpuinfo: No such file or directory

[08-24 20:19:36.641 11119:11119 D/houdini]
[11119] Houdini now in android app mode

[08-24 20:19:36.641 11119:11119 D/houdini]
[11119] Intel Bridge Technology for Microsoft Windows Subsystem for Android(TM), Copyright(C) Intel Corp. 2012-2023.

[08-24 20:19:36.641 11119:11119 D/houdini]
[11119] Use permitted only under a valid commercial software license agreement - all other rights reserved.

[08-24 20:19:36.641 11119:11119 D/houdini]
[11119] Initialize library(version: 13.0.0a_z.39168.m RELEASE)... successfully.

[08-24 20:19:36.642 11119:11119 E/ll.clashofclans]
Not starting debugger since process cannot load the jdwp agent.

[08-24 20:19:36.645 11119:11119 D/CompatibilityChangeReporter]
Compat change id reported: 171979766; UID 10088; state: ENABLED

[08-24 20:19:36.649 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.arm64_v8a.dm': No such file or directory

[08-24 20:19:36.649 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.arm64_v8a.dm': No such file or directory

[08-24 20:19:36.649 11119:11119 W/ll.clashofclans]
Entry not found

[08-24 20:19:36.649 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.de.dm': No such file or directory

[08-24 20:19:36.649 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.de.dm': No such file or directory

[08-24 20:19:36.649 11119:11119 W/ll.clashofclans]
Entry not found

[08-24 20:19:36.649 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.en.dm': No such file or directory

[08-24 20:19:36.649 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.en.dm': No such file or directory

[08-24 20:19:36.649 11119:11119 W/ll.clashofclans]
Entry not found

[08-24 20:19:36.650 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.fa.dm': No such file or directory

[08-24 20:19:36.650 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.fa.dm': No such file or directory

[08-24 20:19:36.650 11119:11119 W/ll.clashofclans]
Entry not found

[08-24 20:19:36.650 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.mdpi.dm': No such file or directory

[08-24 20:19:36.650 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_config.mdpi.dm': No such file or directory

[08-24 20:19:36.650 11119:11119 W/ll.clashofclans]
Entry not found

[08-24 20:19:36.650 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_googleplay_asset_pack.dm': No such file or directory

[08-24 20:19:36.650 11119:11119 W/ziparchive]
Unable to open '/data/app/~~CeYq4nMe60DT3M8KWqZCZg==/com.supercell.clashofclans-LGvg2xRNdpnWY9MwpNAVfQ==/split_googleplay_asset_pack.dm': No such file or directory

[08-24 20:19:36.650 11119:11119 W/ll.clashofclans]
Entry not found

[08-24 20:19:37.025 11119:11119 F/libc]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdead0000 in tid 11119 (ogle.android.gm), pid 11119 (ogle.android.gm)

[08-24 20:19:37.030 11119:11119 F/libc]
crash_dump helper failed to exec, or was killed

[08-24 20:19:37.030 11119:11119 F/libc]
failed to wait for crash_dump helper: No child processes


```

**Request:**
I kindly request your assistance in investigating and addressing this compatibility issue. I believe that once this issue is resolved, Clash of Clans players using the WSA_2307.40000.5.0_x64_Release-Nightly build will be able to enjoy the game without any hindrances.

If there are any additional steps, logs, or information you require from my end to further diagnose and resolve this issue, please do not hesitate to reach out. I am eager to contribute to the improvement of the software and ensure a better user experience for everyone.

Thank you for your attention to this matter. I look forward to your response and the potential resolution of this issue.

**Comment by MustardChef** [comment]
@tester2024 
Thank you for the issue.

Unfortunately, I am unable to help. 
I do not develop, nor do I maintain Windows Subsystem for Android. 

Thus, I am only able to provide limited support to issues that are not within my scope of knowledge and expertise.
 
Opening an issue regarding "Clash of Clans Compatibility" in this repo, is counterintuitive (in my opinion). 
You can look at the possibilities of filing a "Compatibility Issue Report"  through the Feedback Hub using an official build of WSA.

Thank you,
MustardChef

**Comment by nutzboi** [comment]
this is an issue with many split-package apps and especially react native apps, even on the latest wsa build.

installing the app through a third-party app with root (e.g., lucky patcher) does not fix it either. the filesystem permissions of the app's packages seem to be the same as every other normal package. the ziparchive warnings are normal and happen to all apps, including ones that work properly. can't pinpoint the problem :(.
your best bet for now is to find a single-package build of the app you want to use.
