### ISSUE TITLE
[BUG] Final Fantasy VII Ever Crisis cannot be installed due to limitation caused by Google Pixel 5

### ISSUE THREAD

**Issue by VolkovChitzkoi** [MustardChef/WSABuilds#175]
### Describe the bug | 描述一下这个错误

I have not tried (for obvious reasons) the game-app related to this ticket, for it is not possible to install it, due to the fact that the last WSA build 2307.40000.6.0  get identified as Google Pixel 5, that is not supported by the app itself, even if the PC performance where WSA is installed could substain it.

### Steps to reproduce the issue | 重现该问题的步骤

If you try to search the app through Google Play, it doesn't appear. If you try to check the app through web, Google Play inform you that Google Pixel 5 is not supported. Downloading the file manually and trying to install it hang the APK installer.

### Expected behaviour | 预期的行为

Considering that the PC specification are largely above the specifications needed for the game-app to run, it should be executed without any problem through WSA.

### Downloaded Build Of WSA | 已下载的WSA版本

2307.40000.6.0 (31/08/2023)

### Windows build number | Windows构建号

Windows 11 Pro 22H2 22621.2215

### PC Specification | 个人电脑规格

Nome SO	Microsoft Windows 11 Pro
Versione	10.0.22621 build 22621
Modello sistema	MS-7D32
Tipo sistema	PC basato su x64
Processore	12th Gen Intel(R) Core(TM) i9-12900K, 3200 Mhz, 16 core, 24 processori logici
Memoria fisica installata (RAM)	32,0 GB
Nome	NVIDIA GeForce RTX 3080

**Comment by MustardChef** [comment]
Thank you for opening an issue.

Unfortunately, as has been pointed out, this is a WSA related issue. Therefore there is nothing we can do to help.
Hence, I will close this issue.

If you feel that this issue should not be closed, please reopen the issue and provide a reason.
