### ISSUE TITLE
[BUG] The Simpsons: Tapped Out

### ISSUE THREAD

**Issue by AwesomeKalin** [MustardChef/WSABuilds#178]
### Describe the bug | 描述一下这个错误

The Simpsons: Tapped Out is unable to open, it shows its splash screen and then opens a new window showing the app icon. If launched through the Google Play, the app crashes after a short time and if opened through the start menu, it doesn't crash.

### Steps to reproduce the issue | 重现该问题的步骤

Install and open The Simpsons: Tapped Out

### Expected behaviour | 预期的行为

The app starts downloading additional content.

### Downloaded Build Of WSA | 已下载的WSA版本

[https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2308.40000.1.0(https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2308.40000.1.0)
No Root No Amazon, Google Play

### Windows build number | Windows构建号

Windows 11 22H2 22621.2215

### PC Specification | 个人电脑规格

CPU: Intel Core i3-10105
GPU: UHD 630
Storage: 2TB HDD
RAM: 8GB, 4GB to WSL

**Comment by MustardChef** [comment]
@AwesomeKalin 

Thank you for opening an issue.

Unfortunately, I am unable to help.
I do not develop, nor do I maintain Windows Subsystem for Android.

Thus, I am only able to provide limited support to issues that are not within my scope of knowledge and expertise.

Opening an issue regarding "Clash of Clans Compatibility" in this repo, is counterintuitive (in my opinion).
You can look at the possibilities of filing a "Compatibility Issue Report" through the Feedback Hub using an official build of WSA.

Thank you,
MustardChef
