### ISSUE TITLE
WSA Does Not Load After Install + No Splashscreen [BUG]

### ISSUE THREAD

**Issue by ShlomiPorush** [MustardChef/WSABuilds#189]
### Describe the bug | 描述一下这个错误

i have the Exactly the problem as described in this link.
https://github.com/MustardChef/WSABuilds/blob/master/Fixes/Post-Install%20Issues/WSA%20Does%20Not%20Load%20After%20Install%20%2B%20No%20Splashscreen.md

The solution of changing the folder name did not solve it for me.

### Steps to reproduce the issue | 重现该问题的步骤

As described on this page https://github.com/MustardChef/WSABuilds/blob/master/Fixes/Post-Install%20Issues/WSA%20Does%20Not%20Load%20After%20Install%20%2B%20No%20Splashscreen.md.

### Expected behaviour | 预期的行为

Open the files and install an application

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2307.40000.6.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10

### Windows build number | Windows构建号

22H2 10.0.19045

### PC Specification | 个人电脑规格

Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz‏, ‎2904 Mhz
RAM 32GB

Need something more specific?

**Comment by MustardChef** [comment]
@ShlomiPorush Make sure that you have installed the latest Windows Updates and try the latest version, 2308.40000.3.0.
