### ISSUE TITLE
WSA with BusyBox and Xposed Framework

### ISSUE THREAD

**Issue by phantom485x** [MustardChef/WSABuilds#19]
Hy, can you make a build with Busybox and Xposed framework already installed, I tried to install busybox normaly but the WSA crashes when i press the Install button, also tried to manualy create the xbin folder in the system folder using a root explorer and then copy the binaries but the WSA crashes again. It may be related to the way that the system handles the system storage because the root explorer shows 0.00mb  free in the root subfolders and busybox says also that there is no space available for install

**Comment by MustardChef** [comment]
@phantom485x Since Magisk has BusyBox builtin already, you can utilise this [Magisk Module](https://github.com/Magisk-Modules-Alt-Repo/BuiltIn-BusyBox) to install and symlink BusyBox with its applets to the Magisk built-in busybox binary. No need to do it manually.

For Xposed Framework, you can just use the [Lsposed-Zygisk Framework ](https://github.com/LSPosed/LSPosed).

**Comment by phantom485x** [comment]
Thank you! It worked

**Comment by MustardChef** [comment]
> Thank you! It worked
 No problem. Please feel free to open this issue if you have any other issues regarding this.

**Comment by YT-Advanced** [comment]
Hey @MustardChef, what do think if I add it by default ?

**Comment by MustardChef** [comment]
> Hey @MustardChef, what do think if I add it by default ?

Well, I would allow the user to choose whether or not they want to use BusyBox or Xposed, so it would be counterintuitive to add it by default

**Comment by YT-Advanced** [comment]
> @YT-Advanced Well, I would allow the user to choose whether or not they want to use BusyBox or Xposed, so it would be counterintuitive to add it by default
If we add only BusyBox, it will like a feature in WSA and don't take any effect to the root

**Comment by MustardChef** [comment]
> > @YT-Advanced Well, I would allow the user to choose whether or not they want to use BusyBox or Xposed, so it would be counterintuitive to add it by default
> 
> If we add only BusyBox, it will like a feature in WSA and don't take any effect to the root

 @YT-Advanced Sure, you can do that.

**Comment by YT-Advanced** [comment]
Hmm, look that bro, it have added by default
![image](https://user-images.githubusercontent.com/70064328/222904479-01c261bd-bdb4-476c-bf7c-57fac5ba093f.png)
