### ISSUE TITLE
[BUG] Windows 10, WSA IMMEDIATELY crashes whenever started up despite being installed properly.

### ISSUE THREAD

**Issue by FabPhntm** [MustardChef/WSABuilds#190]
### Describe the bug | 描述一下这个错误

After installation and whenever i try to boot up WSA in any shape or form, it IMMEDIATELY crashes, like instantly.
I checked the entire FAQ and tried all workarounds and even disabled and re-enabled stuff in an attempt to imitate the solutions.
I'm on Windows 10 22H2, OS build 19045.2006
Video:
https://github.com/MustardChef/WSABuilds/assets/90190244/80476746-ee1d-4bed-816e-5fdbc59a0e92

### Steps to reproduce the issue | 重现该问题的步骤

Install WSA.

### Expected behaviour | 预期的行为

WSA booting up without crashing.

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2308.40000.3.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10

### Windows build number | Windows构建号

19045.2006

### PC Specification | 个人电脑规格

OS Name: Microsoft Windows 10
Version: 10.19045 Build 19045
System Type: x64-based PC
Processor: Intel Core i7-4790K CPU 4GHz 4 cores 8 logical processors
RAM: 16 GB
Virtualization: Enabled
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by FabPhntm** [comment]
Problem resolved, turns out my WSL was pretty old, and in order to install the latest WSL2 i had to update Windows even further first, that was so weird..

**Comment by MustardChef** [comment]
Great to hear that this issue is solved.
