### ISSUE TITLE
[BUG]WSA with Windows Server 2022 is not working

### ISSUE THREAD

**Issue by merunaaa** [MustardChef/WSABuilds#192]
### Describe the bug | 描述一下这个错误

![image](https://github.com/MustardChef/WSABuilds/assets/102791469/66afab46-ec9c-48fb-b434-d7bd3ab0de96)

I get the error in the image above when I run WSA on windows server 2022. Please let me know if there is a way to deal with this.

The following repository shows Add workaround for Windows Server. but it doesn't actually work.
https://github.com/cinit/WSAPatch/releases/tag/r2023.01.19

### Steps to reproduce the issue | 重现该问题的步骤

When I install a pre-built WSA and try to access the WSA setup screen or the emulator GUI, I get an error.

Wsasettings→System→Files

### Expected behaviour | 预期的行为

Installed built WSA and accessed WSA emulator as normal, expect automatic download of Googleplay.

### Downloaded Build Of WSA | 已下载的WSA版本

any

### Windows build number | Windows构建号

21h2(20348.1970)

### PC Specification | 个人电脑规格

x299desktop

**Comment by MustardChef** [comment]
@merunaaa
I do not work on the WSA patch for Windows 10 (WSAPatch). You should open an issue here: https://github.com/cinit/WSAPatch/.

**Comment by MustardChef** [comment]
This issue will now be closed as WSAPatch (Windows 10 Patch) related issues should be open in the following repo: https://github.com/cinit/WSAPatch/.

If you feel that this issue should not be closed, please reopen and provide your reasoning.

Many Thanks,
MustardChef.
