### ISSUE TITLE
[REQUEST] Ability to Uninstall Only Amazon Appstore

### ISSUE THREAD

**Issue by raaomoka** [MustardChef/WSABuilds#197]
### Describe your request | 描述您的要求

Hi,

Been enjoying the benefits of the Play Store on my Surface Pro 7+ for a while now, thanks to WSABuilds. However, with the recent [v2308.40000.3.0 release](https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2308.40000.3.0), I was looking to install the build with the stable Magisk 26.3.26300 release and the Google Play Store, not knowing that the Amazon Appstore had unusually also been bundled into that package.

Now, attempting to uninstall the Amazon Appstore the regular way also shows the following notification, that it'll uninstall the Play Store and all my other apps, which I've installed from the Play Store (never even opened the Amazon Appstore):
![image](https://github.com/MustardChef/WSABuilds/assets/2476232/e076f7c9-c1b7-4d40-9c7a-518fe097149c)

I tried installing the WSABuild v2308.40000.3.0 with the Canary Magisk and the Amazon Appstore removed, but that didn't uninstall the Amazon Appstore. Please could you provide a separate build/script for uninstalling only the Amazon Appstore, and not our other apps?

**Comment by MustardChef** [comment]
@raaomoka This is known behaviour and that trying to uninstall Amazon Appstore will result it it trying to uninstall all installed apps. Removing Amazon Appstore is not possible without modifying the VHDX files, similar to what the MagiskOnWSALocal script does. 

The easiest method is to have a root build and to use Neo Backup to backup your apps and to then clean install a root build without Amazon Appstore.

Other options are to keep the Amazon Appstore and ignore it, or to clean install WSA.

**Comment by raaomoka** [comment]
Oh, well in that case, guess I'll just delete its shortcut from my start menu and ignore it until I have the time to refresh WSA on my Surface Pro 7+...

**Comment by MustardChef** [comment]
> Oh, well in that case, guess I'll just delete its shortcut from my start menu and ignore it until I have the time to refresh WSA on my Surface Pro 7+...

Sorry if the solutions listed are unsatisfactory.

**Comment by raaomoka** [comment]
Interestingly, when I checked the hidden WSA Settings app, it doesn't list the Amazon Appstore as one of the installed apps:

![image](https://github.com/MustardChef/WSABuilds/assets/2476232/b608134d-848e-45bd-9914-3f21bec5c43e)

But it's shown in the WSA apps list:

![image](https://github.com/MustardChef/WSABuilds/assets/2476232/ab42c339-b7f6-468e-8eea-615ee71335c3)

Also, attempting to launch the Amazon Appstore (via its Start Menu shortcut) or get to its "App settings" screen does nothing. So, it seems like installing the "Amazon Appstore Removed" build did uninstall the Amazon Appstore as expected, it just remains listed in the WSA apps list. No problem with that 😃

**Comment by MustardChef** [comment]
@raaomoka 
Ah, so you downloaded a build without Amazon Appstore and it shows up in the list of installed app? That is an bug that some users experience where Amazon Appstore shows, but is not installed in actual fact.

Now I understand the issue. I was under the impression that you wanted to remove Amazon Appstore for a build with Amazon Appstore included.

**Comment by raaomoka** [comment]
@MustardChef Yes, I did initially install a v2308.40000.3.0 build with Amazon Appstore unexpectedly included. However, I then installed another v2308.40000.3.0 build without the Amazon Appstore, but the Amazon Appstore still remained in the WSA apps list, even though it actually wasn't installed in the WSA system [as shown above](https://github.com/MustardChef/WSABuilds/issues/197#issuecomment-1739591077).

**Comment by MustardChef** [comment]
@raaomoka 

Thank you for the clarification.

I will close this issue and mark it as solved. If you believe that this issue should not be closed, please reopen the issue and state a reason.

**Comment by raaomoka** [comment]
@MustardChef FYI, uninstalling Amazon Appstore without affecting the other installed app is indeed possible as follows:

1. Install a WSA Build without the Amazon Appstore; this should remove any dependencies of WSA on it, and it will no longer show up in the hidden WSA Settings.
2. Using a Win32 uninstaller program like Revo Uninstaller Pro, initiate the uninstall of the Amazon Appstore; this will initially launch the Amazon Appstore's built-in uninstaller, simply click **Cancel** in the built-in uninstaller window.
3. Select the "Moderate" scanning option in Revo Uninstaller's left over scanner, it'll find the registry and files left by the Amazon Appstore uninstaller.
4. Deselect all registry entries, only select branches that have the name **"Amazon"** or **"com.amazon.venezia"** in them, delete them and click **Next**:
![Uninstalling Amazon Appstore via Revo Uninstaller Pro (Registry Files)](https://github.com/MustardChef/WSABuilds/assets/2476232/368a4b37-8d55-4043-9e2a-66da6e31d2af)

5. Deselect all the files entries, only select the files that have the name **"Amazon"** or **"com.amazon.venezia"** in them, delete them and click **Finish**:
![Uninstalling Amazon Appstore via Revo Uninstaller Pro (Files   Folders)](https://github.com/MustardChef/WSABuilds/assets/2476232/e54b3671-c34e-4fed-a6f7-59a5e0caebc8)

6. Vuala, no trace of the Amazon Appstore remains on your system, not even in the WSA app, but all other installed Android apps remain installed and functional as before 🙂:
![Uninstalling Amazon Appstore via Revo Uninstaller Pro (Summary)](https://github.com/MustardChef/WSABuilds/assets/2476232/134cd616-0c73-450b-af84-23e2c0bcb569)
![image](https://github.com/MustardChef/WSABuilds/assets/2476232/5d2e1d10-f87d-4f58-bd60-e4e165537971)

**Comment by Mitia99** [comment]
@raaomoka Not related but as you have a Surface Pro, ty for upvoting this major [right-click context menu touchscreen bug](https://aka.ms/AAmum2r) on Windows 11 in Feedback Hub so that Microsoft fix it asap
![Screenshot_20230928_091108.jpg](https://github.com/MustardChef/WSABuilds/assets/56766778/2ba691f2-31bd-4cc1-9a04-67dd6eea4bbd)

**Comment by raaomoka** [comment]
@Mitia99 It appears Microsoft blocked your feedback on the feedback hub:
![image](https://github.com/MustardChef/WSABuilds/assets/2476232/7eda8a26-3388-4ec1-a34d-3fb753cf69eb)

So much for them being open to feedback. Got a separate link to a forum/reddit post discussing the problem?

**Comment by Mitia99** [comment]
@raaomoka You don't have access to the link cause we're in different region. Feedback Hub is region related. Can you create a Feedback report and share the link?

**Comment by MustardChef** [comment]
Yeah, its quite unfortunate. I am sure that there is a good reason for doing this, but there is nothing we can do.

**Comment by Mitia99** [comment]
> > @raaomoka You don't have access to the link cause we're in different region. I'm UTC +03:00. Feedback Hub is region related.
> 
> Seriously? That's the dumbest restriction I've ever heard of on a software bugs/issues reporting portal. Wonder which genius at microsoft came up with such nonsense...

Yes
![Screenshot_20231012_114602.jpg](https://github.com/MustardChef/WSABuilds/assets/56766778/ed1c7634-a925-4b93-8c70-44cdf2f2b385)
Indeed, it's nonsense

**Comment by raaomoka** [comment]
I've sent this message to a news outlet (Neowin), you should do the same reporting such nonsensical habits of tech giants to tech news outlets, and let them get publicly ridiculed/shamed so that they come back to their senses.
