### ISSUE TITLE
[BUG] Issue Please Resolve it Fast

### ISSUE THREAD

**Issue by LoginForAll** [MustardChef/WSABuilds#198]
### Describe the bug | 描述一下这个错误

Hello
im having a really big issue
MY PC User File Folder is now deleteable i dont know what to do to fix that issue 

All i did was to install your software and then after research im getting User profile as a normal folder which can be deleted.

![image](https://github.com/MustardChef/WSABuilds/assets/146387641/7f20b1ac-2d4f-415e-b3e3-799a44c2b6a8)

### Steps to reproduce the issue | 重现该问题的步骤

i normally formatted my pc 
and installed it.

### Expected behaviour | 预期的行为

User Folder acting like normal one and can be deleted

![image](https://github.com/MustardChef/WSABuilds/assets/146387641/1c8d0d44-4d3d-438d-8b49-262f0b3850dc)

### Downloaded Build Of WSA | 已下载的WSA版本

WSA NO GAPPS Version

### Windows build number | Windows构建号

21h2

### PC Specification | 个人电脑规格

Windows 10 x64

**Comment by MustardChef** [comment]
@LoginForAll I can assure you that the script has not caused this. If you don't believe me, check the Install.ps1 script and scan with antimalware.
