### ISSUE TITLE
video playback error

### ISSUE THREAD

**Issue by zubairalizeebi** [MustardChef/WSABuilds#199]
### Please provide a clear and concise description of the changes you would like to see made to the documentation. | 请清晰简明地描述你希望看到的对文件的修改。

Hi I just recently installed WSA in my laptop and it was working fine but then I installed kinemaster in it and when I was running it it was working fine at first. But Kine Master is not running as it should be in mobile Then I analyzed the device performance of Kine Master and after that when I wanted to play it, all the videos that are in the WSA are not playing properly, now there is an error on them, the playback is error. It's quite confusing what's going on so after that I shut it down and restarted the laptop and again when I ran the same thing it worked fine at first but later when Then I analyzed the kinemaster, after that the same issue started again, now the thumbnail on top of the videos is not showing and when I open the video, there is a playback error on it and Some video plays in it but the video does not play, only the sound play.

**Comment by MustardChef** [comment]
Use the latest version of WSA and enable Vulkan from Advanced Settings in the WSA Settings app.
