### ISSUE TITLE
WSA can run on 20H1 (2004) version

### ISSUE THREAD

**Issue by YT-Advanced** [MustardChef/WSABuilds#20]
As the title, I have tried to install [KB5014032](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5014032) then install [KB5022282](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5014032) and WSA have worked in version 2004. Can you test this in your computer please ?

**Comment by MustardChef** [comment]
Hmm, what was the Windows 10 build number/ version that you installed WSA on?

**Comment by MustardChef** [comment]
I will provided AppxManifest.xml configs for each of the old Windows 10 versions below 22H2 10.0.19045.2311, so that people can try running WSA them. Although limited support would be provided by me or Cinit.

**Comment by MustardChef** [comment]
Support for 20H1 has now been added to the latest prebuilt builds
