### ISSUE TITLE
Mic not working[BUG]

### ISSUE THREAD

**Issue by ahmedsk69** [MustardChef/WSABuilds#200]
### Describe the bug | 描述一下这个错误

Mic not working in any application in WSA

### Steps to reproduce the issue | 重现该问题的步骤

Given the mic permission to WSA in windows. and downloaded mic testing software from playstore and got to know its not working (I was facing mic issue in Team in WSA).

Note: Permission in windows is granted to WSA and in WSA permission is granted to Teams and mic testing Application.

### Expected behaviour | 预期的行为

Mic should work in Teams and mic testing Application

### Downloaded Build Of WSA | 已下载的WSA版本

[WSA_2308.40000.3.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2308.40000.3.0/WSA_2308.40000.3.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z)

### Windows build number | Windows构建号

2308.40000.3.0

### PC Specification | 个人电脑规格

Windows 11, i5 12 Generation

**Comment by Mitia99** [comment]
Check your Audio input settings first. I was facing a similar issue and it was related to WSA
https://github.com/MustardChef/WSABuilds/issues/122#issuecomment-1614238147
