### ISSUE TITLE
[BUG] Tivimate doesn<t open

### ISSUE THREAD

**Issue by jydhthrshrhty** [MustardChef/WSABuilds#205]
### Describe the bug | 描述一下这个错误

you click but it doesn<t open like other apps

### Steps to reproduce the issue | 重现该问题的步骤

download tivimate
try to open

### Expected behaviour | 预期的行为

should open

### Downloaded Build Of WSA | 已下载的WSA版本

latest

### Windows build number | Windows构建号

WSA_2308.40000.3.0_x64

### PC Specification | 个人电脑规格

i9 9th gen
Nvidia 3060ti

**Comment by MustardChef** [comment]
This is an issue with tivimate, the app in question, and not WSA. Please report this to the app developer. This is not the correct place to report an app not working.

Thank you.
