### ISSUE TITLE
[BUG]safetynet-fix-v2.4.0 and Shamiko-v0.7.3(174) install but doesn<t show in module tab

### ISSUE THREAD

**Issue by jydhthrshrhty** [MustardChef/WSABuilds#206]
### Describe the bug | 描述一下这个错误

title

### Steps to reproduce the issue | 重现该问题的步骤

normal steps 

### Expected behaviour | 预期的行为

should show in magisk 

### Downloaded Build Of WSA | 已下载的WSA版本

latest 

### Windows build number | Windows构建号

latest

### PC Specification | 个人电脑规格

i9
nvidia 3060ti

**Comment by MustardChef** [comment]
@jydhthrshrhty Check https://github.com/MustardChef/WSABuilds/issues/154 for the workaround to this issue.
