### ISSUE TITLE
[ADB issue] Restore .ab file extension

### ISSUE THREAD

**Issue by Mitia99** [MustardChef/WSABuilds#21]
Hi,

Thanks for updating the app

Is there a way to restore .ab adb file using WSA?

I always get this error message

"_adb: unable to connect for restore: no devices/emulators found_"
![image](https://user-images.githubusercontent.com/56766778/221368002-4011e6b2-ac07-4930-a5c3-8f0199545072.png)

ADB is enabled on WSA and I can sideload apks through it though.

- WSA version : 2301.40000.7.0 Windows 11 x64
- ADB version : r34.0.0

Thanks,

**Comment by MustardChef** [comment]
To be honest, I have no idea wheter or not you can bacnkup and resotre using ADB. I will test it as soon as I am free and will tell you if it works or not (and make a guide if it does)

**Comment by MustardChef** [comment]
@Mitia99 If you ever want to back up your WSA data, you can copy %LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache\userdata.vhdx before uninstallation and restore it after installation.

**Comment by Mitia99** [comment]
@MustardChef Thanks for the tip but rather that WSA backup, the issue is that I would like to sideload Android apps with ".ab" extension

**Comment by MustardChef** [comment]
As this is probably a problem with WSA itself, I will close this issue. It is better to report this to the Microsoft Github.

**Comment by Mitia99** [comment]
Fyi, here's the [link ](https://github.com/microsoft/WSA/issues/242#issue-1599757181)for reported issue in Microsoft WSA (I was able to connect but got stuck on "_Now unlock your device and confirm the restore operation_" cause there's no way to unlock WSA device)
