### ISSUE TITLE
system proxy 

### ISSUE THREAD

**Issue by mts7777** [MustardChef/WSABuilds#214]
### Describe the bug | 描述一下这个错误

how to set system proxy for wsa ?

### Steps to reproduce the issue | 重现该问题的步骤

.

### Expected behaviour | 预期的行为

.

### Downloaded Build Of WSA | 已下载的WSA版本

.

### Windows build number | Windows构建号

.

### PC Specification | 个人电脑规格

.

### Additional context | 额外的背景

.

**Comment by MustardChef** [comment]
Check https://github.com/MustardChef/WSABuilds/issues/165#issuecomment-1962794928 for a method to achieve this.
