### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HeroRickyGAMES** [MustardChef/WSABuilds#218]
### Describe the bug | 描述一下这个错误

I feel like WSA turns on out of nowhere in Windows 10. Even disabling it in Task Manager

### Steps to reproduce the issue | 重现该问题的步骤

Turning on the system sometimes turns on WSA even when it is turned off in Task Manager

### Expected behaviour | 预期的行为

Does not start at boot when disabled in Task Manager

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2309.40000.2.0_x64_Release-Nightly-MindTheGapps-13.0.7z

### Windows build number | Windows构建号

Windows 10 Pro 22H2 19045.2965

### PC Specification | 个人电脑规格

Processor: Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz   3.19 GHz
RAM: 16,0 GB
GPU: GTX 750 ti.

**Comment by tilsgee** [comment]
there are 2 possible answer:

1. check Windows Setting on Startup category. see if it still enabled in there. or check startup folder by typing "shell:startup" on Run, CMD.....
2. open WSA Settings, go to "Subsystem Resources", choose "as needed"
