### ISSUE TITLE
[BUG] deployment failed with hresult: 080073CFD

### ISSUE THREAD

**Issue by lucianolsouza** [MustardChef/WSABuilds#219]
### Describe the bug | 描述一下这个错误

it´s saying my os version is above 10.0.22000.120

but I use Windows 11 Home Single Language
Version	Dev
Installed on	‎08/‎10/‎2022
OS build	21996.1
Experience	Windows Feature Experience Pack 321.14700.0.3
![Screenshot 2023-11-01 023307](https://github.com/MustardChef/WSABuilds/assets/85614624/f5e6b5db-9be0-45e5-bba9-bf6df9afb0de)

thanks for help

### Steps to reproduce the issue | 重现该问题的步骤

i just did a regular instalation
i didnt have windows android installed previously

### Expected behaviour | 预期的行为

a regular instalation

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2308.40000.3.0_x64_Release-Nightly-MindTheGapps-13.0

### Windows build number | Windows构建号

21996.1

### PC Specification | 个人电脑规格

acer nitro an515-52
Intel core i5 8300h
16g ram
running on ssd

**Comment by tilsgee** [comment]
try update your Windows
