### ISSUE TITLE
[DOC]virus wsa

### ISSUE THREAD

**Issue by ADVABonnie** [MustardChef/WSABuilds#223]
### Please provide a clear and concise description of the changes you would like to see made to the documentation. | 请清晰简明地描述你希望看到的对文件的修改。

I don’t recommend installing WSA because it is dangerous, viral, there may be errors like this, and because you shouldn’t install what the video from Github showed, it’s a virus

**Comment by MustardChef** [comment]
@ADVABonnie 
Ok, first of all, stop making unsubstantiated claims. SHOW EVIDENCE!
No one from the 600k Downloads have reported a virus, nor has any antivirus detected a virus. Clearly you are trying to smear this project.

Again, if you have any legitimate concerns, I would be happy to listen and take action on them.
