### ISSUE TITLE
Cant upadate to latest version

### ISSUE THREAD

**Issue by zulfakar404** [MustardChef/WSABuilds#23]
C:\WSA\Install.ps1 : Failed to update.
Press any key to uninstall existing installation while preserving user data.
                                                                                                                         Deployment operation progress: C:\WSA\AppxManifest.xml                                                                     Processing                                                                                                              [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo  ]       Deployment operation progress: MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.11.0_x64__8wekyb3d8bbwe        Initialized                                                                                                          Deployment operation progress: C:\WSA\AppxManifest.xml                                                                     Processing                                                                                                              [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo  ]                                                                                                                              +     Remove-AppxPackage -PreserveApplicationData -Package $Installed.P ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (MicrosoftCorpor...__8wekyb3d8bbwe:String) [Remove-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.
Deployment operation failed.
NOTE: For additional information, look for [ActivityId] 63f54d38-4a6a-0006-cb7f-f6636a4ad901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 63f54d38-4a6a-0006-cb7f-f6636a4ad901
At C:\WSA\Install.ps1:111 char:5
+     Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVers ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\WSA\AppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by MustardChef** [comment]
@zulfakar404 Could you please send me a screenshot of the issue.

**Comment by 15805658608** [comment]
![image](https://user-images.githubusercontent.com/63145651/222098427-6e80d05d-e14d-4942-91d3-65e1c8fb5ad4.png)

**Comment by 15805658608** [comment]
![image](https://user-images.githubusercontent.com/63145651/222099673-a4dfcf2e-5de8-4e84-9060-43daa3c370a7.png)

**Comment by WellCodeIsDelicious** [comment]
@15805658608 Make sure that the Partition/Drive is NTFS and not FAT32
