### ISSUE TITLE
[BUG] No Google Play Store installed and can't open "Files" or "Manage developer settings"

### ISSUE THREAD

**Issue by yesterdaypun** [MustardChef/WSABuilds#232]
### Describe the bug | 描述一下这个错误

Hi I just installed latest Windows 10 WSA (v2309.40000.2.0) when I open run.bat the program itself seems to work normally, but there's no Google play store installed plus when I try to open "Files" and "Manage developer settings" it shows up "Starting Windows Subsystem for Android" windows for a few second then disappear and nothing happened
I already tried reinstalling or install older versions but it didn't work as well

### Steps to reproduce the issue | 重现该问题的步骤

Reinstall / Click on "FIles" or "Manage developer settings"

### Expected behaviour | 预期的行为

Have a Google play store on "Apps" tab / Open a "Files" and "Manage developer settings" properly

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2309.40000.2.0_x64_Release-Nightly-with-magisk-26.3.26300.-stable-MindTheGapps-13.0_Windows_10.7z

### Windows build number | Windows构建号

Windows 10 22H2 19045.2604

### PC Specification | 个人电脑规格

Processor	Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz, 1800 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.4.2, 7/4/2019
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0PD9KD
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.2251"
User Name	DESKTOP-6N7QGL1\Yesterday Pun
Time Zone	SE Asia Standard Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.85 GB
Available Physical Memory	3.83 GB
Total Virtual Memory	9.10 GB
Available Virtual Memory	5.32 GB
Page File Space	1.25 GB
Page File	E:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

### Additional context | 额外的背景

![Screenshot (142)](https://github.com/MustardChef/WSABuilds/assets/53987885/88a21ac0-6a41-4831-9cee-1ef295bc60d8)
![Screenshot (141)](https://github.com/MustardChef/WSABuilds/assets/53987885/ae1ebe14-da9e-46a6-b850-d0e6689d5dd3)

**Comment by TigerTD21** [comment]
I have the same problem.Have you resolved it?

**Comment by Houssem-Guemer** [comment]
I have the same problem.

**Comment by YesserFA** [comment]
I HAVE google play install but i cant open anything same problem.

**Comment by Houssem-Guemer** [comment]
> I have the same problem.

I fixed my problem, I had a dns service ON which was affecting the WSA, I stopped it restarted the pc and then the install worked perfectly !
