### ISSUE TITLE
[BUG] When playing mp4, there is sound but no image.

### ISSUE THREAD

**Issue by cason-wu** [MustardChef/WSABuilds#235]
### Describe the bug | 描述一下这个错误
Playing MP4 files with GPU Intel UHD Graphics 730

Windows Subsystem for Android Gallery:
Opening an MP4 (HEVC) file shows only sound without video.
Opening an MP4 (AVC) file causes Files to stop responding.

GoPro Quik:
MP4 (HEVC) files are unable to display thumbnails, and when played, there is only sound without video.
MP4 (AVC) files are able to display thumbnails, and when played, Quik stop responding.

VLC Player:
MP4(HEVC) playback is intermittent, displaying large gray areas with high CPU loading.
MP4(AVC) can played without error.

Youtube can paly video without error.

![image](https://github.com/MustardChef/WSABuilds/assets/126079584/4e0115a2-fd4c-40e3-bafb-87d3447532f8)

![image](https://github.com/MustardChef/WSABuilds/assets/126079584/157c4ab5-c7bb-403c-8c64-a1c531ef8fe8)

### Steps to reproduce the issue | 重现该问题的步骤

Play MP4 video.

### Expected behaviour | 预期的行为

Both video and audio play normally.

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2308.40000.3.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon
WSA_2309.40000.2.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon

### Windows build number | Windows构建号

Windows 11 Pro 22H2

### PC Specification | 个人电脑规格

![image](https://github.com/MustardChef/WSABuilds/assets/126079584/12358152-550d-4351-a101-11d6d48606d6)

### Additional context | 额外的背景

GPU Intel UHD Graphics 730

**Comment by MustardChef** [comment]
Use the latest version of WSA and enable Vulkan from Advanced Settings in the WSA Settings app.
