### ISSUE TITLE
[BUG] Android Settings not Saving

### ISSUE THREAD

**Issue by Astra060** [MustardChef/WSABuilds#237]
### Describe the bug | 描述一下这个错误

When I change Smallest Width in Developer settings, each time I restart the service it resets it self to the default value

### Steps to reproduce the issue | 重现该问题的步骤

change the Smallest Width or DPI in settings

### Expected behaviour | 预期的行为

The setting must be saved for the next boot

### Downloaded Build Of WSA | 已下载的WSA版本

Windows_10_2308.40000.3.0/WSA_2308.40000.3.0_x64_Release-Nightly-with-magisk-d4e552d0.26301.-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z

### Windows build number | Windows构建号

19044

### PC Specification | 个人电脑规格

Ryzen 4800H, 16GBs RAM, 2060m

### Additional context | 额外的背景

If I can write a script which fixes this and runs on WSA start up I'll be really happy

**Comment by ewaerp** [comment]
I have the same problem. Cant turn off in Developer options Window animation scale, Transition animatoion scale and Animator duration scale

**Comment by MustardChef** [comment]
This is a known behaviour by WSA. There is no known method to permanently change it so that it persists after the restart of the subsystem. Your best course of action would be to request this via the Feedback Hub or via WSA's GitHub.

**Comment by Spuner** [comment]
@MustardChef, still no solution to this problem? The settings in "Developer Mode" are not saved either. Just... WSA support will be discontinued in a year...
