### ISSUE TITLE
All apps are showing unexpected colors [BUG]

### ISSUE THREAD

**Issue by moha-abdi** [MustardChef/WSABuilds#240]
### Describe the bug | 描述一下这个错误

Hello, I am using WSA the one with the  playstore. I downloaded multiple apps, they are all showing some colors that disappear as I scroll then later they again show up as in the images below. I have tried to uninstall and reinstall it but nothing changed. I am using Windows 10. All other options are operating normally its just this issue.
![Screenshot (3)](https://github.com/MustardChef/WSABuilds/assets/83307623/5268e362-8b62-40c5-b162-eed7898e338f)
![Screenshot (4)](https://github.com/MustardChef/WSABuilds/assets/83307623/94027cdf-ed89-4951-8c1c-abbf0c0bbdad)
![Screenshot (5)](https://github.com/MustardChef/WSABuilds/assets/83307623/060d213a-75d8-4028-878a-b772d567f1de)
![Screenshot (6)](https://github.com/MustardChef/WSABuilds/assets/83307623/e1eb820e-42d4-42e3-850d-7538c8a4de9d)

### Steps to reproduce the issue | 重现该问题的步骤

Opening any app is causing the issue for me.

### Expected behaviour | 预期的行为

I was expecting it would show up normally. it feels like its showing the design boundaries and things like that.

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2308.40000.3.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10_5

### Windows build number | Windows构建号

19045.3693

### PC Specification | 个人电脑规格

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	ADMINISTRATOR
System Manufacturer	LENOVO
System Model	20FRS1G11Q
System Type	x64-based PC
System SKU	LENOVO_MT_20FR_BU_Think_FM_ThinkPad X1 Yoga 1st
Processor	Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 2808 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO N1FET77W (1.51 ), 11/8/2021
SMBIOS Version	2.8
Embedded Controller Version	1.18
BIOS Mode	UEFI
BaseBoard Manufacturer	LENOVO
BaseBoard Product	20FRS1G11Q
BaseBoard Version	SDK0J40697 WIN
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.3636"
User Name	ADMINISTRATOR\lenovo
Time Zone	E. Africa Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	3.76 GB
Total Virtual Memory	32.2 GB
Available Virtual Memory	4.42 GB
Page File Space	16.4 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by Ivan951236** [comment]
Try these methods and their steps:
**Method 1:** Update WSA by following updating guide in the WSABuilds's Updating Guide from README.md (and backup userdata).
**Method 2:** Go to developer settings by enabling developer mode in advanced settings in WSA Settings (Windows App), then check if show layout bounds, show surface updates, show view updates, show hardware layers update, debug GPU Overdraw and debug non-rectangular clip operations are disabled but if one of them, mutilple of them or all of them is enabled then disable them.
**Method 3 (Don't follow it unless all methods failed):** Your GPU might not support much shaders, colors or is prone to artifiacts, buy another gpu and test them by changing in graphics perference to only use specfic gpu (Change GPU to new one then to old one to compare).


If all methods fail then i don't know what will fix, you can also try to follow mutilple methods to make the bug disappear more and more often
One might not work but the other might work, If all methods fail once again i might not know what will fix it but you can also spread your words from this issue post to WSA Communtiny discord server in WSABuilds's own support discord forum to have even more suggestions, my suggestion might not be enough but try all methods to see for yourself for now this is my suggestion
