### ISSUE TITLE
WsaSettings.winmd cannot be unpacked

### ISSUE THREAD

**Issue by traversone** [MustardChef/WSABuilds#245]
### Describe the bug

Dear all,

when unpacking today WSA release, this error comes up. Is it relevant? Does it depend on my unpacker?

Thank you

### Steps to reproduce the issue

during upacking task in 7zip, this error comes up

### Expected behaviour

official released ZIP should be unpacked without errors

### Downloaded Build Of WSA

WSA_2311.40000.4.0_x64_Release-Nightly-with-Magisk-d7750b72-canary-MindTheGapps-13.0-RemovedAmazon.7z

### Windows build number

10.0.19045 Build 19045

### PC Specification

SO Name: Microsoft Windows 10 Enterprise
Version: 	10.0.19045 Build 19045
Processor:Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz, 2208 Mhz, 4 core, 8 processori logici

**Comment by MustardChef** [comment]
Make sure that you redownload it and also make sure that 7zip is up to date.

**Comment by traversone** [comment]
I simply updated the 7zip version, no issue at all now. Issue can be closed.

**Comment by MustardChef** [comment]
Thank you for the information. I have now updated the release notes to include this.
