### ISSUE TITLE
[Request] I just deleted the WSA folder and can not reinstall 

### ISSUE THREAD

**Issue by Alaneeer** [MustardChef/WSABuilds#246]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

Sorry I just deleted the folder without any suggested steps. Then I can not reinstall the Run.bat, it just show error message after it

**Comment by MustardChef** [comment]
Please provide more information. This is not enough for me to help you!

**Comment by Alaneeer** [comment]
thank you for your reply. I did reinstall "Run.bat" but it shows error as attachment.
![error WSA](https://github.com/MustardChef/WSABuilds/assets/153970552/c661e22f-42c6-4653-b7a8-7c86a9008ee5)

**Comment by MoonBunTauri** [comment]
I'm getting the same error, though on my case i got this error while decompressing the files with 7zip. i tried redownloading the archive a couple times but i keep getting the same decompression error
![7zG_FLOFV0G1Tt](https://github.com/MustardChef/WSABuilds/assets/20261270/69f83ae9-f51a-47f6-9423-f0ff4a0d0b66)

**Comment by MustardChef** [comment]
> I'm getting the same error, though on my case i got this error while decompressing the files with 7zip. i tried redownloading the archive a couple times but i keep getting the same decompression error ![7zG_FLOFV0G1Tt](https://private-user-images.githubusercontent.com/20261270/291006681-69f83ae9-f51a-47f6-9423-f0ff4a0d0b66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjM2NDksIm5iZiI6MTcwMjc2MzM0OSwicGF0aCI6Ii8yMDI2MTI3MC8yOTEwMDY2ODEtNjlmODNhZTktZjUxYS00N2Y2LTk0MjMtZjBmZjRhMGQwYjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDIxNDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2OTEzZjY1ZTI3Yjk3MWY2ODc2MzIxZDBjNzVkZTIwODA5MjViNWY0NDVlNDdjMWFkNDZkYTNmZmI1Y2NlZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XnD6TOzP20MMIdNSwABVm7URpZNCLi_JpqiWuY9Y5Fc)

@MoonBunTauri Please update 7-zip and try again.

**Comment by Alaneeer** [comment]
I decompressed successfully but i will meet the errors as my screenshot above.

**Comment by MustardChef** [comment]
> I decompressed successfully but i will meet the errors as my screenshot above.

What did you use to decompress?

**Comment by Alaneeer** [comment]
I think my problem had been solved since I used 7z to do it. Now I’m back. But I feel a little bit slow  when I type in the environment.

**Comment by MustardChef** [comment]
> I think my problem had been solved since I used 7z to do it. Now I’m back. But I feel a little bit slow when I type in the environment.

You can use WinRAR as well.

**Comment by Alaneeer** [comment]
And may I ask do you have any good way to make the system optimizer when I use the android app?

**Comment by syster-0** [comment]
> And may I ask do you have any good way to make the system optimizer when I use the android app?

I deleted the folder where I installed WSA, yes, it was the folder that was unzipped with 7zip, and now there is a problem, I can't delete the current WSA, and I can't install the new WSA. What to do?
