### ISSUE TITLE
[BUG] some files are missing (compression error)

### ISSUE THREAD

**Issue by Alter00Z** [MustardChef/WSABuilds#256]
### Describe the bug

when trying run.bat says some files are missing ..the files are in  WSA_2311.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon\WSA_2311.40000.4.0_x64\WSACrashUploader\arm64
cant extract them tried WinRAR and 7z ..both say unsupported compression method

### Steps to reproduce the issue

extraction 

### Expected behaviour

error

### Downloaded Build Of WSA

WSA_2311.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon\WSA_2311.40000.4.0

### Windows build number

windows 11 latest

### PC Specification

windows 11 HP probook

**Comment by MustardChef** [comment]
@Alter00Z Update WinRAR and 7z to the latest version.

**Comment by HelloMeisn** [comment]
I have the same problem. And I've checked my WinRAR an 7-zip version. Both are the latest, but neither works.

**Comment by rufatagayev** [comment]
Updating 7-zip fixed the issue for me.

**Comment by MustardChef** [comment]
> I have the same problem. And I've checked my WinRAR and 7-zip. Both are the latest, but neither works.

Have you tried using Windows Explorer's built-in 7z extraction tool (on Windows 11).

**Comment by Alter00Z** [comment]
> I have the same problem. And I've checked my WinRAR and 7-zip. Both are the latest, but neither works.
installing latests winRar fixed the problem for me.

**Comment by HelloMeisn** [comment]
I 've fixed it. Thank you all!

**Comment by MustardChef** [comment]
> > I have the same problem. And I've checked my WinRAR and 7-zip. Both are the latest, but neither works.
> > installing latests winRar fixed the problem for me.

@Alter00Z You are still having this issue?

**Comment by MustardChef** [comment]
> I 've fixed it. Thank you all!

@HelloMeisn If you don't mind me asking, how did you fix it?

**Comment by HelloMeisn** [comment]
> > I 've fixed it. Thank you all!
> 
> @HelloMeisn If you don't mind me asking, how did you fix it?

OK. I just reinstalled 7-zip. It worked well. I also checked the decompression log and nothing's wrong. BUT I cannot open the WsaSettings.exe yet. It says not finding VCRUNTIME140_1_APP.dIl, MSVCP140_APP.dll and VCRUNTIME140_APP.dll. I really don't know the reason. Inputting "wsa://com.android.settings" in firefox address bar and clicking entry key can run the exe.

**Comment by Alter00Z** [comment]
> > > I have the same problem. And I've checked my WinRAR and 7-zip. Both are the latest, but neither works.
> > > installing latests winRar fixed the problem for me.
> 
> @Alter00Z You are still having this issue?

no, i installed latest winrRar and the problem was fixed  👍

**Comment by MustardChef** [comment]
> > > I 've fixed it. Thank you all!
> > 
> > 
> > @HelloMeisn If you don't mind me asking, how did you fix it?
> 
> OK. I just reinstalled 7-zip. It worked well. I also checked the decompression log and nothing's wrong. BUT I cannot open the WsaSettings.exe yet. It says not finding VCRUNTIME140_1_APP.dIl, MSVCP140_APP.dll and VCRUNTIME140_APP.dll. I really don't know the reason. Inputting "wsa://com.android.settings" in firefox address bar and clicking entry key can run the exe.

Once you run the "Run.bat" file, WSA should install and there should be an entry created for WSA Settings. Android Settings shortcut is not created, and must be opened via "wsa://com.android.settings".

**Comment by HelloMeisn** [comment]
> > > > I 've fixed it. Thank you all!
> > > 
> > > 
> > > @HelloMeisn If you don't mind me asking, how did you fix it?
> > 
> > 
> > OK. I just reinstalled 7-zip. It worked well. I also checked the decompression log and nothing's wrong. BUT I cannot open the WsaSettings.exe yet. It says not finding VCRUNTIME140_1_APP.dIl, MSVCP140_APP.dll and VCRUNTIME140_APP.dll. I really don't know the reason. Inputting "wsa://com.android.settings" in firefox address bar and clicking entry key can run the exe.
> 
> Once you run the "Run.bat" file, WSA should install and there should be an entry created for WSA Settings. Android Settings shortcut is not created, and must be opened via "wsa://com.android.settings".

I understand, thank you for your explanation!

**Comment by MustardChef** [comment]
I will close this issue now. Please reopen if you have any other questions or issues.
