### ISSUE TITLE
how to uninstall completely

### ISSUE THREAD

**Issue by DGQXP** [MustardChef/WSABuilds#257]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

I am currently able to use it normally, but I want to move the folder to a different location. What should I do? Do I have to reinstall it? How do I uninstall it completely?

**Comment by MustardChef** [comment]
No need to uninstall for this.

1. Turn off WSA from WSA's Settings and make sure that VmemmWSA is not running
2. Move the folder to a new location/ rename it.
3. Open the folder and re-run Run.bat
4. WSA should work as normal

**Comment by DGQXP** [comment]
@MustardChef
Thank you very much, I successfully operated according to the prompts after re-running run.bat, and the application data was not lost. Thanks again!

**Comment by DGQXP** [comment]
@MustardChef
Thank you very much, I successfully operated according to the prompts after re-running run.bat, and the application data was not lost. Thanks again!

**Comment by MustardChef** [comment]
No problem, I will close this issue now.
