### ISSUE TITLE
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073D10, 部署操作失败，因为该程序包针对的是错误的处理器体系结构。[BUG]

### ISSUE THREAD

**Issue by glenlau228** [MustardChef/WSABuilds#258]
### Describe the bug

E:\WSA\WSA_2311.40000.4.0_arm64>PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1
操作成功完成。                                                                                                          Installing MicrosoftCorporationII.WindowsSubsystemForAndroid version: 2311.40000.4.0                                    Dependency package Microsoft.UI.Xaml.2.8 arm64 required minimum version: 8.2208.12001.0. Installing...                  Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073D10, 部署操作失败，因为该程序包针对的是错误的处理器体系结构。        Windows 无法安装程序包 Microsoft.UI.Xaml.2.8，因为此程序包需要体系结构 ARM64，但此计算机具有体系结构 x64。              注意: 有关其他信息，请在事件日志中查找 [ActivityId] 77982cfb-33e2-0000-08c9-b677e233da01，或使用命令行 Get-AppPackageLo g -ActivityID 77982cfb-33e2-0000-08c9-b677e233da01                                                                      所在位置 E:\WSA\WSA_2311.40000.4.0_arm64\Install.ps1:99 字符: 13                                                        +             Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFro ...                                             +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : NotSpecified: (E:\WSA\WSA_2311....2.8_arm64.appx:String) [Add-AppxPackage], Exception         + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand                                                                                                                              Dependency package Microsoft.VCLibs.140.00.UWPDesktop arm64 required minimum version: 14.0.30704.0. Installing...       Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073D10, 部署操作失败，因为该程序包针对的是错误的处理器体系结构。        Windows 无法安装程序包 Microsoft.VCLibs.140.00.UWPDesktop，因为此程序包需要体系结构 ARM64，但此计算机具有体系结构 x64。 注意: 有关其他信息，请在事件日志中查找 [ActivityId] 77982cfb-33e2-0003-6eac-ad77e233da01，或使用命令行 Get-AppPackageLo g -ActivityID 77982cfb-33e2-0003-6eac-ad77e233da01                                                                      所在位置 E:\WSA\WSA_2311.40000.4.0_arm64\Install.ps1:99 字符: 13                                                        +             Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFro ...                                             +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : NotSpecified: (E:\WSA\WSA_2311...ktop_arm64.appx:String) [Add-AppxPackage], Exception         + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand                                                                                                                              Dependency package Microsoft.VCLibs.140.00 arm64 required minimum version: 14.0.30704.0. Installing...                  Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073D10, 部署操作失败，因为该程序包针对的是错误的处理器体系结构。        Windows 无法安装程序包 Microsoft.VCLibs.140.00，因为此程序包需要体系结构 ARM64，但此计算机具有体系结构 x64。            注意: 有关其他信息，请在事件日志中查找 [ActivityId] 77982cfb-33e2-0003-12b4-ad77e233da01，或使用命令行 Get-AppPackageLo g -ActivityID 77982cfb-33e2-0003-12b4-ad77e233da01                                                                      所在位置 E:\WSA\WSA_2311.40000.4.0_arm64\Install.ps1:99 字符: 13                                                        +             Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFro ...                                             +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : NotSpecified: (E:\WSA\WSA_2311...0.00_arm64.appx:String) [Add-AppxPackage], Exception         + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Installing MagiskOnWSA...
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073D10, 部署操作失败，因为该程序包针对的是错误的处理器体系结构。
Windows 无法安装程序包 MicrosoftCorporationII.WindowsSubsystemForAndroid，因为此程序包需要体系结构 ARM64，但此计算机具
有体系结构 x64。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] 77982cfb-33e2-0004-1687-b277e233da01，或使用命令行 Get-AppPackageLo
g -ActivityID 77982cfb-33e2-0004-1687-b277e233da01
所在位置 E:\WSA\WSA_2311.40000.4.0_arm64\Install.ps1:130 字符: 1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (E:\WSA\WSA_2311...ppxManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

### Steps to reproduce the issue

E:\WSA\WSA_2311.40000.4.0_arm64>PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1

### Expected behaviour

 部署失败，原因是 HRESULT: 0x80073D10, 部署操作失败，因为该程序包针对的是错误的处理器体系结构。

### Downloaded Build Of WSA

WSA_2311.40000.4.0_arm64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon

### Windows build number

Windows 11   23H2

### PC Specification

16g

**Comment by TGSAN** [comment]
>
> ...
> ...部署操作失败，因为该程序包针对的是错误的处理器体系结构。 Windows 无法安装程序包 MicrosoftCorporationII.WindowsSubsystemForAndroid，因为此程序包需要体系结构 ARM64，但此计算机具有体系结构 x64。 ...
> ...
> 部署失败，原因是 HRESULT: 0x80073D10, 部署操作失败，因为该程序包针对的是错误的处理器体系结构。
>

**Comment by MustardChef** [comment]
@glenlau228 您好，感谢您提出问题。

请删除此版本并下载 WSA 的 x64 版本。

您正试图安装 arm64 版本的 WSA，但错误显示您的系统使用的是 x64 CPU。

希望这能解决您的问题。

**Comment by MustardChef** [comment]
我现在就结束这个问题。这个问题应该会在 WSA 的最新版本中得到修复。请确保使用最新的存档提取软件。

如果您仍面临此问题，请告诉我。
