### ISSUE TITLE
[BUG] Windows Subsystem For Android™ not uninstall full

### ISSUE THREAD

**Issue by Protey** [MustardChef/WSABuilds#260]
### Describe the bug

After uninstallation, following this instruction [completely uninstall](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/Uninstallation.md) shortcuts to the Google play, Google, Google partner and other Android system applications remain.

### Steps to reproduce the issue

Uninstallation, following this instruction [completely uninstall](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/Uninstallation.md)

### Expected behaviour

It is not known how to remove the tails of a remote Windows Subsystem For Android™

### Downloaded Build Of WSA

[WSA_2310.40000.2.0_x64_Release-Nightly-MindTheGapps-13.0_Windows_10.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2310.40000.2.0/WSA_2310.40000.2.0_x64_Release-Nightly-MindTheGapps-13.0_Windows_10.7z)

### Windows build number

22H2 (19045.3803)

### PC Specification

4 core processor, 16 GB RAM, NVidia 1650 4 GB video card

**Comment by MustardChef** [comment]
@Protey Use this python script (https://github.com/MustardChef/WSABuilds/blob/master/WSABuilds%20Utilities/Uninstall%20Script/Uninstall.py) and run it in Administrator CMD/PowerShell to uninstall WSA completely.

**Comment by Protey** [comment]
> @Protey Use this python script (https://github.com/MustardChef/WSABuilds/blob/master/WSABuilds%20Utilities/Uninstall%20Script/Uninstall.py) and run it in Administrator CMD/PowerShell to uninstall WSA completely.

Ok, thanks for the answer, next time I'll try this python script

**Comment by MustardChef** [comment]
Hopefully it works well. Please report any issues, if they occur.

**Comment by Protey** [comment]
> @Protey Use this python script (https://github.com/MustardChef/WSABuilds/blob/master/WSABuilds%20Utilities/Uninstall%20Script/Uninstall.py) and run it in Administrator CMD/PowerShell to uninstall WSA completely.

Should I use this python script (https://github.com/MustardChef/WSABuilds/blob/master/WSABuilds%20Utilities/Uninstall%20Script/Uninstall.py) after uninstalling it using this [completely uninstall](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/Uninstallation.md) instructions?
Or can this python script be used without these steps that are written in the [completely uninstall](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/Uninstallation.md) instructions for uninstallation?

**Comment by MustardChef** [comment]
You can use the script without following the instructions.

**Comment by MustardChef** [comment]
The script was added yesterday and has not made it into the WSA builds yet, so the instructions have not been updated.

**Comment by Protey** [comment]
> You can use the script without following the instructions.

In this case the script does not work for me, i.e. it does not remove Windows Subsystem For Android™, I had to remove it according to the instructions
Was installed and uninstalled manually WSA_2310.40000.2.0_x64_Release-Nightly-NoGApps-RemovedAmazon_Windows_10.7z

**Comment by Protey** [comment]
Now I'll test the script on WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip

**Comment by Protey** [comment]
> You can use the script without following the "Uninstall" instructions.

Doesn't it matter from which directory to run the script?

**Comment by MustardChef** [comment]
> > You can use the script without following the "Uninstall" instructions.
> 
> Doesn't it matter from which directory to run the script?

Does not matter.
Make sure you delete the WSA folder and .zip files after running the script.

**Comment by MustardChef** [comment]
> > You can use the script without following the instructions.
> 
> In this case the script does not work for me, i.e. it does not remove Windows Subsystem For Android™, I had to remove it according to the instructions Was installed and uninstalled manually WSA_2310.40000.2.0_x64_Release-Nightly-NoGApps-RemovedAmazon_Windows_10.7z

I see. Thank you for telling me. I will need to repo on a another system , since the script is working fine for me.

**Comment by Protey** [comment]
> Now I'll test the script on WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip

Just like with WSA_2310.40000.2.0_x64_Release-Nightly-NoGApps-RemovedAmazon_Windows_10.7z, the script does not work.

**Comment by MustardChef** [comment]
> > Now I'll test the script on WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip
> 
> Just like with WSA_2310.40000.2.0_x64_Release-Nightly-NoGApps-RemovedAmazon_Windows_10.7z, the script does not work.

Could you record yourself running the script.

**Comment by Protey** [comment]
> > > Now I'll test the script on WSA_2303.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.zip
> > 
> > 
> > Just like with WSA_2310.40000.2.0_x64_Release-Nightly-NoGApps-RemovedAmazon_Windows_10.7z, the script does not work.
> 
> @Protey Could you record yourself running the script. This will help me diagnose the issue.

By the way, I don’t understand why, besides the WSA Android folder, you need to delete the ZIP archive before using it.
Since you said that it doesn’t matter in which directory to run the script, but I’ll say right away that I run the script from the directory where the WSA Android folder is located
WSA Android Uninstall Process - https://drive.google.com/file/d/19vpoH1aqjBGAlwybA74zrE9ivJBj5sQ8/view?usp=sharing
Process of checking for the existence of "MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe" - https://drive.google.com/file/d/1TVUS6RlXuoWc2B06DoIEqbgECTFtepvn/view?usp=sharing

And, in order not to create a new topic, when I start WsaSettings.exe it complains about the missing files msvcp140_app.dll, vcruntime140_app.dll, vcruntime140_1_app.dll
But here is confirmation that the files msvcp140_app.dll, vcruntime140_app.dll, vcruntime140_1_app.dll are on my Windows system - https://drive.google.com/file/d/1OpF_ulM7WHVKpRGAr5vcO_BdmTdXxR5x/view?usp=sharing

**Comment by MustardChef** [comment]
Thank you for your contribution. I will improve the script so that it deletes all shortcuts of WSA and it searches all directories to ensure that all files folder related to WSA are removed.

To answer your questions:
1. It is recommended to remove the .zip files and folders extracted after running the uninstall script, if you don't need them anymore. You can keep if you want.
2. The error you are facing is because you cannot run WSA/WSA Settings via that .exe file (WsaSettings.exe). You must run Run.bat and install WSA and then open WSA's settings via the newly created entry.

**Comment by Protey** [comment]
> 2\. You must run Run.bat and install WSA and then open WSA's settings via the newly created entry.
Why did I start talking about errors in dlls, because after installation I could not find a shortcut to launch “Windows Subsystem for Android” in the start menu, to, for example, enter Android Explorer
I don’t know where else this “Windows Subsystem for Android” shortcut might be.
![image](https://github.com/MustardChef/WSABuilds/assets/6497045/cb82770d-dab9-4268-8cdf-b1652f11823a)

**Comment by borlac** [comment]
![image](https://github.com/MustardChef/WSABuilds/assets/133239817/29e3b44c-d538-4282-8107-90a7948a1179)

**Comment by borlac** [comment]
> ![image](https://private-user-images.githubusercontent.com/133239817/309530070-29e3b44c-d538-4282-8107-90a7948a1179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc0MzMsIm5iZiI6MTcwOTQ0NzEzMywicGF0aCI6Ii8xMzMyMzk4MTcvMzA5NTMwMDcwLTI5ZTNiNDRjLWQ1MzgtNDI4Mi04MTA3LTkwYTc5NDhhMTE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwNjI1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODFiMjM2Y2E3ZDYyZDNmNzQwNjE1ZTJhOTQyNGNlM2Q4ZGJjNzI3ZjYzNDgwY2ZjY2Q4YzUzOTBjZDhkOGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B2BNCOvm_czhWdehp0WIN8BkNMrXbfJELjqwiSwgKDY)

idk how what to do with this i just run the wsauninstaller.py

someone help pls

**Comment by borlac** [comment]
> > ![image](https://private-user-images.githubusercontent.com/133239817/309530070-29e3b44c-d538-4282-8107-90a7948a1179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc0MzMsIm5iZiI6MTcwOTQ0NzEzMywicGF0aCI6Ii8xMzMyMzk4MTcvMzA5NTMwMDcwLTI5ZTNiNDRjLWQ1MzgtNDI4Mi04MTA3LTkwYTc5NDhhMTE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwNjI1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODFiMjM2Y2E3ZDYyZDNmNzQwNjE1ZTJhOTQyNGNlM2Q4ZGJjNzI3ZjYzNDgwY2ZjY2Q4YzUzOTBjZDhkOGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B2BNCOvm_czhWdehp0WIN8BkNMrXbfJELjqwiSwgKDY)
> 
> idk how what to do with this i just run the wsauninstaller.py
> 
> someone help pls

just found a way to remove the gapps along side the wsa
i just folled the uninstall steps, then delete everything even the gapps, when you search it on the search bar in the windows (ex. Play Store) when it still show up go to the file location and delete it, then go to the app and features(add or remove program) search the (ex. Play Store)
if its still there go to the registry edition then go to this location
(Computer\HKEY_USERS\S-1-5-21-3977808592-1236551752-4184240237-1002\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall)
find the gapps there and delete the folder

**Comment by MustardChef** [comment]
The WSAUtilities python scripts were for testing only. You were not meant to use them and were instead meant to follow the instructions in Uninstallation.md.

Or, if entries remained after installation:

Run:
```powershell
Get-AppxPackage -Name "MicrosoftCorporationII.WindowsSubsystemForAndroid" -AllUsers | Remove-AppxPackage -AllUsers
```
And then follow this guide to remove any entries that remain:
https://github.com/MustardChef/WSABuilds/blob/master/Documentation/Usage%20Guides/General%20Usage%20Guides/Remove%20Non%20Existent%20Entries.md

**Comment by Kp344** [comment]
so im trying to uninstall magiskonWSA and the jst wsa in general bcus i noticed that it filled up most of my storage, and so i deleted the folders, uninstalled the apps and what not but its still not giving back my old free space on disk
went from 43 gb free to 9gb
idk what to do now, i tried every method i could think of and am wonder if theres a uninstall menu in magisk on WSA.
Pls help
