### ISSUE TITLE
Google Play Store is installed but doesn't launch! [BUG]

### ISSUE THREAD

**Issue by Ivan951236** [MustardChef/WSABuilds#261]
### Describe the bug

Google Play store, when i open it, it doesn't launch, i tried mutilple ways of opening this thing (Mixplore's Apps menu, Solid Explorer's apps menu, com.android.settings app menu, windows shortcut and more), the video attached only shows me opening it in com.android.settings app menu please help me!

### Steps to reproduce the issue

You open it throught the windows shortcut, com.android.settings app menu and more other ways opening a app

### Expected behaviour

It should launch as Google Play services is installed and Google Play store requires that service to launch

### Downloaded Build Of WSA

WSA_2311.40000.4.0_x64_Release-Nightly-with-KernelSU-v0.7.1-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z [And its link](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.4.0/WSA_2311.40000.4.0_x64_Release-Nightly-with-KernelSU-v0.7.1-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z)

### Windows build number

19044.3803 (Windows 10 21H2 from a USB recovery)

### PC Specification

OS Name	Майкрософт Windows 10 Корпоративная LTSC
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	HOME-PC
System Manufacturer	System manufacturer
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz, 3100 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 0605, 5/9/2013
SMBIOS Version	2.6
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	P8H61-M LX2
BaseBoard Version	Rev X.0x
Platform Role	Workstation
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	Russia
Hardware Abstraction Layer	Version = "10.0.19041.3636"
User Name	HOME-PC\VanyaAlexander
Time Zone	Russia TZ 2 Standard Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.98 GB
Available Physical Memory	1.55 GB
Total Virtual Memory	14.5 GB
Available Virtual Memory	5.64 GB
Page File Space	6.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, WinRE is not configured, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

### Additional context

Sure, the video should be uploaded and embed (if it is not embed try to download the video from the link)

https://github.com/MustardChef/WSABuilds/assets/101629412/d4d9c831-2ac0-46c8-b0f7-fd214cdcddf9

**Comment by Ivan951236** [comment]
nvm i think i found the solution

**Comment by Ivan951236** [comment]
nvm i think i found the solution

**Comment by Ivan951236** [comment]
nvm the solution i found doesn't work!

**Comment by MustardChef** [comment]
@Ivan951236 

Oh, what was the solution, if you don't mind me asking?

**Comment by Ivan951236** [comment]
> @Ivan951236
> 
> Oh, what was the solution, if you don't mind me asking?

Turns out the apk of play store was corrupted so i just reinstalled it from lucky patcher's Install modded play store dialog then select orginial play store version (it doesn't matter which version but you can select the newest on the list)

**Comment by yeet-dot-org** [comment]
> > @Ivan951236
> > Oh, what was the solution, if you don't mind me asking?
> 
> Turns out the apk of play store was corrupted so i just reinstalled it from lucky patcher's Install modded play store dialog then select orginial play store version (it doesn't matter which version but you can select the newest on the list)

how do i do that
