### ISSUE TITLE
[REQUEST] Build with MicroG instead of normal GApps

### ISSUE THREAD

**Issue by dabockster** [MustardChef/WSABuilds#262]
### Describe your request

Currently we can't use MicroG instead of regular GApps in WSL when we install it as a user (due to valid security reasons by Microsoft related to app spoofing by malicious actors). So with that option out of the question for the foreseeable future, I was wondering if there's a way to install MicroG at build time so that WSL thinks MicroG is the "real" GApps and Google's is the spoofed one.

**Comment by fillwithjoy1** [comment]
maybe it could be baked into the ROM

**Comment by MichaelZ4714** [comment]
I managed to get it running, though it is not easy. I installed the WSA package with Magisk and without GApps. I installed a file manager with root access. Then I copied /system/framework/services.jar to the pc and patched that so Signature Spoofing is included. A guide is [in this post](https://forum.xda-developers.com/t/android-12-lineageos-19-1-manual-patch-to-services-jar-for-signature-spoofing.4523041/) 
Then I added the Magisk module MinMicroG and added the patched services.jar to the module directory so it replaces the original one. Before booting I installed the migroG apk as user app. I don't know if this is still necessary, but with previous WSA releases the system did not boot. After reboot there is a full working microG.

**Comment by fillwithjoy1** [comment]
> I managed to get it running, though it is not easy. I installed the WSA package with Magisk and without GApps. I installed a file manager with root access. Then I copied /system/framework/services.jar to the pc and patched it so Signature Spoofing is included. A guide is [in this post](https://forum.xda-developers.com/t/android-12-lineageos-19-1-manual-patch-to-services-jar-for-signature-spoofing.4523041/). Then I added the Magisk module MinMicroG and added the patched services.jar to the module directory so it replaces the original one. Before booting I installed the migroG apk as user app. I don't know if this is still necessary, but with previous WSA releases the system did not boot without. After reboot there is a full working microG.
> 
> Edit: I forgot to mention that also services.odex and services.vdex need to be created and put into the Magisk module.

me after seeing the amount of steps required https://media1.tenor.com/m/XIJPpDD7Bc0AAAAC/squidward-squidward-shocked.gif

**Comment by MichaelZ4714** [comment]
If you trust foreign binaries I could post here the files for WSA 1.8.32836.0, 2307.40000.3.0 and 2307.40000.6.0. I don't have a newer WSA running because of a problem with building it with integrated Magisk-Delta.

**Comment by MichaelZ4714** [comment]
Yes, I can imagine that it's possible. From my point of view only the three mentioned files need to be replaced. And for WSA the app SignatureSpoofing.apk needed to be installed. Afaik it only sets a privilege.

**Comment by MustardChef** [comment]
Once my new PC a

**Comment by fillwithjoy1** [comment]
> I don't know if this is still necessary, but with previous WSA releases the system did not boot without. After reboot there is a full working microG.

I'm using March 2023 build because it's "Advanced Networking" is actually able to connect to my phone via wi-fi instead of the newer versions, where it's replaced by a another similar sounding feature that breaks that.

**Comment by MustardChef** [comment]
Scrapped as WSA has been discontinued.
