### ISSUE TITLE
[DOC]the guide for "WSA stopped working" links to the guide for enabling virtualization on win11 labeled as the guide for win10

### ISSUE THREAD

**Issue by ErikTheGrate** [MustardChef/WSABuilds#265]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

on the guide [Issues: WSA Stopped Working!](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/Fix%20Guides/Post-Install%20Issues/WSA%20Stopped%20Working!.md), it links both [enable-virtualization-on-windows-11-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1](https://support.microsoft.com/en-us/windows/enable-virtualization-on-windows-11-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1) and
[enable-virtualization-on-windows-10-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1](https://support.microsoft.com/en-us/windows/enable-virtualization-on-windows-10-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1) however, the microsoft website ignores this change and only looks to the "-c5578302-6e43-4b4b-a449-8ced115f58e1" to find out what guide to look for. you could even go to [this-text-does-not-matter-dummy-c5578302-6e43-4b4b-a449-8ced115f58e1](https://support.microsoft.com/en-us/windows/this-text-does-not-matter-dummy-c5578302-6e43-4b4b-a449-8ced115f58e1) and it will link to the same page. i can confirm that this guide does not work on win10 because i followed this guide on a physical windows 10 PC and saw that The option to boot into recovery was located in a different subfolder and it did not give me the option to boot into bios or uefi once i was in recovery mode.

**Comment by MustardChef** [comment]
Thank you for informing me. I will search for a suitable guide for Windows 10 and update it.

**Comment by ErikTheGrate** [comment]
i do not believe its been fixed.

**Comment by ErikTheGrate** [comment]
i believe that it hasn't been fixed
