### ISSUE TITLE
[BUG]一直显示“正在启动适用于Android™的Windows子系统”

### ISSUE THREAD

**Issue by Onloker** [MustardChef/WSABuilds#266]
### Describe the bug

![image](https://github.com/MustardChef/WSABuilds/assets/63253274/64b64f81-9428-403c-b8a2-afd0432a928c)
安装后，打开文件管理器，一直现在正在启动

WSA工具箱显示如下：
![image](https://github.com/MustardChef/WSABuilds/assets/63253274/bf9c515d-6731-429c-91b7-89bd7de09438)

### Steps to reproduce the issue

下载WSA_2311.40000.4.0_x64_Release-Nightly-with-Magisk-d7750b72-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z后，使用7z进行解压，将解压后的文件夹，复制到了D盘App文件夹
7z版本：23.01(x64)，WSA路径：D:\App\WSA
运行Run.bat，待Windows Powershell运行完成后，会打开3个正在启动的界面，但是一直显示正在启动，等待很久后，3个正在启动的画面会自动关闭，再次从WSA设备打开文件管理，还是会一直显示正在启动
![image](https://github.com/MustardChef/WSABuilds/assets/63253274/ccf452f6-6417-4da2-8231-31b1970824a8)

### Expected behaviour

希望能正常运行

### Downloaded Build Of WSA

WSA_2311.40000.4.0_x64_Release-Nightly-with-Magisk-d7750b72-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z
https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2311.40000.4.0

### Windows build number

19045.3803

### PC Specification

操作系统名称	Microsoft Windows 10 专业版
版本	10.0.19045 内部版本 19045
其他操作系统描述 	没有资料
操作系统制造商	Microsoft Corporation
系统制造商	HP
系统型号	HP ProBook 440 G8 Notebook PC
系统类型	基于 x64 的电脑
系统 SKU	63P18PA#AB2
处理器	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz，2419 Mhz，4 个内核，8 个逻辑处理器
BIOS 版本/日期	HP T88 Ver. 01.14.00, 2023/6/27
SMBIOS 版本	3.3
嵌入式控制器版本	84.24
BIOS 模式	UEFI
主板制造商	HP
主板产品	8A76
主板版本	KBC Version 54.18.00
平台角色	移动
安全启动状态	关闭
PCR7 配置	无法绑定
Windows 目录	C:\Windows
系统目录	C:\Windows\system32
启动设备	\Device\HarddiskVolume1
区域设置	中国
硬件抽象层	版本 = "10.0.19041.3636"
时区	中国标准时间
已安装的物理内存(RAM)	16.0 GB
总的物理内存	15.7 GB
可用物理内存	8.78 GB
总的虚拟内存	25.2 GB
可用虚拟内存	18.3 GB
页面文件空间	9.50 GB
页面文件	C:\pagefile.sys
内核 DMA 保护	关闭
基于虚拟化的安全性	正在运行
基于虚拟化的安全性要求的安全属性	
基于虚拟化的安全性提供的安全属性	基本的虚拟化支持, DMA 保护, 安全内存覆盖, UEFI 代码只读, SMM Security Mitigations 1.0, 基于模式的执行控制, APIC 虚拟化
基于虚拟化的安全服务已配置	
基于虚拟化的安全服务正在运行	
设备加密支持	设备自动加密失败的原因: 不支持 PCR7 绑定, 未配置 WinRE
已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。

**Comment by raaomoka** [comment]
Yeah, I'm experiencing the same issue since I updated from stable build **v2308.40000.3.0** to stable build **v2310.40000.2.0**, both variant were the **x64 Release Nightly with Magisk canary MindTheGapps and RemovedAmazon** builds. What's going on?

BTW, this same issue is occurring on my **1TB SSD, 32GB RAM i7 Surface Pro 7+ with Windows 11 Pro**.
