### ISSUE TITLE
Why the latest release version, magisk version number cannot be obtained, and it prompts to update.

### ISSUE THREAD

**Issue by iseeyo** [MustardChef/WSABuilds#27]
Why the latest release version, magisk version number cannot be obtained, and it prompts to update.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/7778828/222751362-a333136b-b906-48ad-84df-19c30d0e8e07.png">

**Comment by MustardChef** [comment]
There is a Magisk Canary available. I will update the releases with the latest Magisk version

**Comment by MustardChef** [comment]
> Why the latest release version, magisk version number cannot be obtained, and it prompts to update. <img alt="image" width="286" src="https://user-images.githubusercontent.com/7778828/222751362-a333136b-b906-48ad-84df-19c30d0e8e07.png">

@iseeyo Latest Magisk is now avaliable in Releases. Please follow the update guide to update.
