### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Robinson36** [MustardChef/WSABuilds#271]
### Describe the bug

When trying to install wsa in my pc i got the error in powershell:

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Validatie van updates, afhankelijkheid of conflict voor h
et pakket is mislukt.
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_2304.40000.10.0_x64__8wekyb3d8bbwe bec
ause this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.8" publish
ed by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
 architecture and minimum version 8.2208.12001.0, along with this package to install.
NOTE: For additional information, look for [ActivityId] 67287229-41b9-0003-1788-2c67b941da01 in the Event Log or use th
e command line Get-AppPackageLog -ActivityID 67287229-41b9-0003-1788-2c67b941da01
At C:\Users\Robin\Documents\WSA_2304.40000.10.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon\Install.ps1:167 cha
r:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Robin\...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

### Steps to reproduce the issue

Installing on clean win 11 installation with windows hypervisor platform and platform for virtual machine enabled.

### Expected behaviour

Clean and easy installation

### Downloaded Build Of WSA

Happens on any version of wsa from the github page

### Windows build number

Win 11 v22631.2861

### PC Specification

Intel i5 2400
Hd graphics 2000 
12gb ddr3
128gb sata ssd

(hp compaq 8200 elite sff)

**Comment by MustardChef** [comment]
Install "Microsoft.UI.Xaml.2.8" from the WSA folder and retry installation.
