### ISSUE TITLE
KernelSU & APatch

### ISSUE THREAD

**Issue by ManyullynSword** [MustardChef/WSABuilds#274]
### Describe your request

APtach is another root tool that claims to have Magisk compatibility and KernelSU hiddenness, and its code is based on KernelSU. I would expect the new version of the distro to include packages that use APatch.
Also, KernelSU hasn't stopped updating completely. The author will continue to update after the New Year.

APtach是另外一个root工具，它声称拥有Magisk的兼容性和KernelSU的隐藏性，且其代码基于KernelSU。我希望新版本的发行版可以包括使用APatch的包。
还有，KernelSU并没有彻底停更。作者过完年还会继续更新。

**Comment by ManyullynSword** [comment]
https://github.com/bmax121/APatch?ref=akpatch.org

**Comment by MustardChef** [comment]
Thank you for bringing the project to my attention. I will have a look.

**Comment by MustardChef** [comment]
@ManyullynSword Unfortunately, the APatch Project only supports arm64 only. We would need x86_64 support and patched WSA kernels like KernelSU provides at the moment.
