### ISSUE TITLE
[BUG] NOT LET INSTALL

### ISSUE THREAD

**Issue by Keiser04** [MustardChef/WSABuilds#277]
### Describe the bug

I cant install. this is the image
![image](https://github.com/MustardChef/WSABuilds/assets/146493916/e4c2eef0-fa74-473e-a9e7-e859db3fe75f)

### Steps to reproduce the issue

i only run the run.bat

### Expected behaviour

install the wsa

### Downloaded Build Of WSA

WSA_2311.40000.4.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon

### Windows build number

211

### PC Specification

RTX 4050
I5-1200H
32GB

**Comment by MustardChef** [comment]
@Keiser04 First delete the folder that you extracted, update 7zip or WinRAR and then re-extract and re-install.

**Comment by Keiser04** [comment]
> @Keiser04 First delete the folder that you extracted, update 7zip or WinRAR and then re-extract and re-install.

This time it has gone but my question is whether it is possible to disable the debugger mode.

![image](https://github.com/MustardChef/WSABuilds/assets/146493916/1a32c654-134f-4274-b525-b7aed18ad691)

**Comment by V3ntus** [comment]
Can confirm updating from 7zip 19.00 to 23.01 fixes the original issue. Maybe we should be reading the big font in the releases page first.
![image](https://github.com/MustardChef/WSABuilds/assets/29584664/6947ab30-0d1a-4622-a9f2-45afe48286d7)

**Comment by Keiser04** [comment]
> Can confirm updating from 7zip 19.00 to 23.01 fixes the original issue. Maybe we should be reading the big font in the releases page first. ![image](https://private-user-images.githubusercontent.com/29584664/298314701-6947ab30-0d1a-4622-a9f2-45afe48286d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDA2MTksIm5iZiI6MTcwNTk0MDMxOSwicGF0aCI6Ii8yOTU4NDY2NC8yOTgzMTQ3MDEtNjk0N2FiMzAtMGQxYS00NjIyLWE5ZjItNDVhZmU0ODI4NmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE2MTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YWVhZDBmNDRiNjNmYzkzZTM3OGJmMWU4YmZiMjAyYTUxMGUwMjUyZjQzZDRmYTliNTc4ZDkwZDJiNjljYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QZp6mHNCFo5rpnL9ncQHmzX1LpyRykCwSfsMpAF5FNY)

After upgrading or rebooting I did both.

**Comment by cornradio** [comment]
```
C:\Users\kasus\Downloads\WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z
不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\KernelTraceControl.dll
不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msdia140.dll
不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msvcp140.dll
不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\vcruntime140.dll

```
---

```
7zip: 23.01 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

update 7zip have no effect for me

**Comment by cornradio** [comment]
got it 
i have muti versions of 7-zip
i uninstalled the old one and now it's working

**Comment by MustardChef** [comment]
> ```
> C:\Users\kasus\Downloads\WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z
> 不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\KernelTraceControl.dll
> 不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msdia140.dll
> 不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msvcp140.dll
> 不支持的压缩算法 : WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\vcruntime140.dll
> ```
> 
> ```
> 7zip: 23.01 (latest version)
> Latest versions for all apps are installed! For more information try 'scoop status'
> ```
> 
> update 7zip have no effect for me

@V3ntus Try using the latest WinRAR build instead.
