### ISSUE TITLE
[REQUEST] WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-magisk-XXXXX.XXXX.-canary-MindTheGapps-XX.X-RemovedAmazon.7z

### ISSUE THREAD

**Issue by wanzhiyu** [MustardChef/WSABuilds#279]
### Describe your request

Sorry, but I can not find the release named "Release-Nightly-with-Magisk-d7750b72-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10" for latest version "WSA_2311.40000.5.0_x64", is it done on purpose or some other reasons?
![image](https://github.com/MustardChef/WSABuilds/assets/18503895/f5dd7cfe-0ce2-45d8-b2ba-f4a949a4218a)

**Comment by MustardChef** [comment]
@wanzhiyu Some builds have, for some reason been added to the release for v2310.40000.2.0. I have identified the issue.

Until next week, I am on vacation. Hence, due to the lack of time, small issues in the repo has yet to be resolved yet.

Here is the link to the release: https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2310.40000.2.0/WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-65207f96-canary-MindTheGapps-13.0-RemovedAmazon.7z

Sorry for any confusion and inconvenience caused.

**Comment by wanzhiyu** [comment]
@MustardChef Thanks for the reply, I'll go there to download. Also, have a nice vacation!

**Comment by shirooo39** [comment]
could you also please add one to [last week's release](https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2311.40000.5.0)?
![image](https://github.com/MustardChef/WSABuilds/assets/38461122/2ff7d16e-8f05-49ed-837e-e32581250ed0)

**Comment by shirooo39** [comment]
> could you also please add one to [10/01/2024 build's release](https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2311.40000.5.0)? ![image](https://private-user-images.githubusercontent.com/38461122/298286924-2ff7d16e-8f05-49ed-837e-e32581250ed0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjA1OTMsIm5iZiI6MTcwNTc2MDI5MywicGF0aCI6Ii8zODQ2MTEyMi8yOTgyODY5MjQtMmZmN2QxNmUtOGYwNS00OWVkLTgzN2UtZTMyNTgxMjUwZWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE0MTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwY2FjNzM1ODU0Yzc1YjAyZjUxMTE0ZDhmZjYzNzFmNDk2YWY5MWRkMjY2MTI5MjUwMWQ5OTU3ODRkNGQzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8a_DAqPJi-natBnrtTkVwwSg3gxkrhFn-byUf64hVJI)

nevermind, I didn't read properly lol

**Comment by MustardChef** [comment]
> > could you also please add one to [10/01/2024 build's release](https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2311.40000.5.0)?
> 
> nevermind, I didn't read properly lol

No problem. I will have everything fixed by the end of next week.

**Comment by tristanhabibie2013-crypto** [comment]
WSA_2407.40000.4.0_x64_Release-Nightly-MindsTheGapps-13.0-RemovedAmazon_Windows_10.7z

**Comment by tristanhabibie2013-crypto** [comment]
WSA_2407.40000.4.0_x64_Release-Nightly-MindsTheGapps-13.0_Windows_10.7z

**Comment by tristanhabibie2013-crypto** [comment]
WSA_2407.40000.4.0_x64_Release-Nightly-NoApps-RemovedAmazon_Windows_10.7z

**Comment by tristanhabibie2013-crypto** [comment]
WSA_2407.40000.4.0_x64_Release-Nightly-NoApps_Windows_10.7z

**Comment by Aga556456** [comment]
skim
