### ISSUE TITLE
When I run Run.bat to upgrade Magisk, all app shortcuts in the start menu are lost. How to keep app shortcuts?

### ISSUE THREAD

**Issue by iseeyo** [MustardChef/WSABuilds#28]
When I run Run.bat to upgrade Magisk, all app shortcuts in the start menu are lost. How to keep app shortcuts?

**Comment by MustardChef** [comment]
This looks like a bug in the WSA itself  and the icons can be restored by the following steps.
 
1. Backup `userdata.vhdx` from `%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache\userdata.vhdx`

2. [Uninstall WSA](https://github.com/MustardChef/WSABuilds#--uninstallation)
 
3. Remove the two lines in the installation script that automatically launches Magisk and Play Store after the installation is finished

4. Install WSA
 
5. Restore `userdata.vhdx`

6. Start WSA
  
**Do not start WSA before restoring user data.**

**Comment by MustardChef** [comment]
@iseeyo Do tell me if this fixes the issue, so I can add it to the list of fixes

**Comment by MustardChef** [comment]
I will close this issue. But if the issue still persists, feel free to reopen.
