### ISSUE TITLE
is Bluetooth or USB passthrough for gamepads and controllers possible?

### ISSUE THREAD

**Issue by Leggyweggy** [MustardChef/WSABuilds#282]
### Describe your request

from what i can see online, the answer seems to be no, and people were even asking the same thing on Microsoft's official WSA repo to see if it would work. 

i've tried a couple things to get it to work including running DS4 for gamepad emulation on the windows side of things, but Android itself doesn't seem to be able to see anything, which at least for Bluetooth, since the setting is disabled, makes a lot of sense. what's interesting is that it doesn't detect the controller when connected specifically over USB either, even though my external webcam works no problem when playing with WSA. I know nothing about the development of this stuff, but would it be possible for something like this to leverage the Android Debug Bridge for controller communication? just a thought

**Comment by MustardChef** [comment]
USB Passthrough and Keymapping are currently not possible on WSA.

**Comment by MustardChef** [comment]
Controllers should work with WSA
