### ISSUE TITLE
[REQUEST]pixel5

### ISSUE THREAD

**Issue by FinalVar** [MustardChef/WSABuilds#284]
### Describe your request

Dear developers, I would like to ask why the latest image still uses the pixel 5 model, can you update to the latest Google official model, thank you for taking time out of your busy schedule to watch.

**Comment by MustardChef** [comment]
Planned for the next WSA release. Thank you.

**Comment by AnroidTester** [comment]
Dear developers, I am also waiting for this development. some applications are not suitable for this device.e.Can you update to the latest Google official model, thank you.

**Comment by DARK7BEA5T** [comment]
but pixel unlimited storage not working?

**Comment by MustardChef** [comment]
This project is now in Long Term Support (LTS), no more requests will be fulfilled.
Sorry for any inconvenience caused.
