### ISSUE TITLE
[DOC] WSAChangelog.md does not exist

### ISSUE THREAD

**Issue by AndnixSH** [MustardChef/WSABuilds#286]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

What happened to WSAChangelog.md? The releases still provide link to Microsoft's Official Changelog but it doesn't exist anymore
`https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/WSAChangelog.md`

**Comment by MustardChef** [comment]
@AndnixSH Thank you and sorry for the late response. 

Rest assured that this is an area which we are working on and will be fixed in the coming week. Thank you.
