### ISSUE TITLE
[BUG] Question about transferring files (like epubs) to local storage (Pixel 5)

### ISSUE THREAD

**Issue by laovvai** [MustardChef/WSABuilds#290]
### Describe the bug

First of all, thank you for creating such a great tool! 
I think I managed to install it successfully.

Unfortunately, I run into a bit of a problem and I hope this is the right place to ask my question.

I would like to open an epub file using apps from Google PlayStore but I don't seem to be able to copy/paste it directly into directories. 
The only thing I can see is Pixel 5, presumably the name of the virtual device that gives me access to android apps.

![изображение](https://github.com/MustardChef/WSABuilds/assets/144963017/e11522c8-e41f-4398-aee1-b0ab695fdd40)

Is there any way I can transfer this epub file, so that it can be open in an app? 

Thank you in advance!

### Steps to reproduce the issue

The app's name is Pleco. This is a dictionary that allows to read books in Chinese with quick lookups. 

### Expected behaviour

I would like to tranfer files to Pixel 5 and to be able to access them using apps from Google PlayStore.

### Downloaded Build Of WSA

WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-MindTheGapps-XX.X-RemovedAmazon.7z

### Windows build number

Version 23H2 (OS Build 22631.2861)

### PC Specification

Windows 11 Pro

**Comment by MustardChef** [comment]
@laovvai Thank you for opening an issue. 

Rest assured that this is the correct place to ask.

From your query, I assume that the EPUB file is stored on Windows and you want to access these files in WSA/Android in your desired app, correct?

**Comment by laovvai** [comment]
Yes, this is the case, thanks for replying! I managed to solve this issue on my own. 
I had to enable developer mode in WSA advanced settings and navigate to the folder with my file.
