### ISSUE TITLE
[BUG]The software installation failed after running

### ISSUE THREAD

**Issue by badukongjian777** [MustardChef/WSABuilds#292]
### Describe the bug

![Screenshot_20240129_175536_com huawei himovie loc](https://github.com/MustardChef/WSABuilds/assets/158039577/0b7026bc-ff0c-4047-a5ff-292b09ec2b2a)

### Steps to reproduce the issue

![Screenshot_20240129_175536_com huawei himovie loc](https://github.com/MustardChef/WSABuilds/assets/158039577/f3aa6a91-f294-4550-9f45-e4dd86632db6)

### Expected behaviour

..

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64

### Windows build number

Windows 10 家庭中文版

### PC Specification

LAPTOP-L45P8MG3

**Comment by MustardChef** [comment]
@badukongjian777 您下载的版本适用于 Windows 11。您正在安装的系统是 Windows 10。

**Comment by MustardChef** [comment]
@badukongjian777 请下载正确的版本。
