### ISSUE TITLE
WSACrashUploader

### ISSUE THREAD

**Issue by Kumar-vikalp** [MustardChef/WSABuilds#294]
### Describe your request

! C:\Users\vikal\Downloads\Compressed\WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\KernelTraceControl.dll
! C:\Users\vikal\Downloads\Compressed\WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msdia140.dll
! C:\Users\vikal\Downloads\Compressed\WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\vcruntime140.dll
! C:\Users\vikal\Downloads\Compressed\WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msvcp140.dll

**Comment by MustardChef** [comment]
[Follow this fix guide](https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPre-Install%20Issues%2FExtraction%20Errors.md)

**Comment by TribalChief264** [comment]
! C:\Users\a\Desktop\PLAY STORE.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\KernelTraceControl.dll
! C:\Users\a\Desktop\PLAY STORE.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msdia140.dll
! C:\Users\a\Desktop\PLAY STORE.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\msvcp140.dll
! C:\Users\a\Desktop\PLAY STORE.7z: Unknown method in WSA_2311.40000.5.0_x64\WSACrashUploader\arm64\vcruntime140.dll
HOW TO FIX IT?

**Comment by MustardChef** [comment]
@TribalChief264 
 [Follow this fix guide](https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPre-Install%20Issues%2FExtraction%20Errors.md)
