### ISSUE TITLE
Quick Question: i tried to extract but it says some files is corrupted.

### ISSUE THREAD

**Issue by qwq233** [MustardChef/WSABuilds#295]
At first, i thought it was just a network issue so i tried to download 7z file from another release.
but it still failed to extract all files.
then i tried `p7zip` then it shows
```
❯ p7zip -d WSA_2311.40000.4.0_x64_Release-Nightly-with-KernelSU-v0.7.1-MindTheGapps-13.0-RemovedAmazon.7z

7-Zip (a) [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 5800X 8-Core Processor              (A20F10),ASM,AES-NI)

Scanning the drive for archives:
1 file, 681822483 bytes (651 MiB)

Extracting archive: WSA_2311.40000.4.0_x64_Release-Nightly-with-KernelSU-v0.7.1-MindTheGapps-13.0-RemovedAmazon.7z
--
Path = WSA_2311.40000.4.0_x64_Release-Nightly-with-KernelSU-v0.7.1-MindTheGapps-13.0-RemovedAmazon.7z
Type = 7z
Physical Size = 681822483
Headers Size = 3667
Method = 0A LZMA2:25 BCJ
Solid = +
Blocks = 3

ERROR: Unsupported Method : WSA_2311.40000.4.0_x64/WSACrashUploader/arm64/KernelTraceControl.dll
ERROR: Unsupported Method : WSA_2311.40000.4.0_x64/WSACrashUploader/arm64/msdia140.dll
ERROR: Unsupported Method : WSA_2311.40000.4.0_x64/WSACrashUploader/arm64/msvcp140.dll
ERROR: Unsupported Method : WSA_2311.40000.4.0_x64/WSACrashUploader/arm64/vcruntime140.dll

Sub items Errors: 4

Archives with Errors: 1

Sub items Errors: 4
```

Btw I modified the filelist.txt to bypass the integrity verification because i think i am running this thing on amd64 computer and i dont need arm64 lib. And it works.

Also I tried to join the Discord server and it says the invite link is expired

**Comment by MustardChef** [comment]
Please refer to this [fix guide](https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPre-Install%20Issues%2FExtraction%20Errors.md), Thank You!

**Comment by qwq233** [comment]
> Please refer to this [fix guide](https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPre-Install%20Issues%2FExtraction%20Errors.md), Thank You!

So this question is just happened so frequently to push you to make a guide. but why not fix it instead? anyway thanks for answering

**Comment by MustardChef** [comment]
@qwq233 Issue still persists. I have tried every potential solution possible, in order to fix the issue.
