### ISSUE TITLE
Getting error while installing Run.bat file [BUG]

### ISSUE THREAD

**Issue by KshitijBramhecha** [MustardChef/WSABuilds#296]
### Describe the bug

It gives an error - This command cannot be run due to the error: A specified logon session does not exist. It may already
have been terminated.

### Steps to reproduce the issue

I would like instructions on how to fix the error, thank you

### Expected behaviour

I would like instructions on how to fix the error, thank you

![Capture](https://github.com/MustardChef/WSABuilds/assets/148058898/d8565dd0-e697-49bd-b638-4a4f8ebc7702)

### Downloaded Build Of WSA

[WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z)

### Windows build number

19045.3930

### PC Specification

Lenovo G-50 i5-5200u 16gb ram

**Comment by MustardChef** [comment]
@KshitijBramhecha You must install WSA from an Administrator account on Windows.
