### ISSUE TITLE
Cannot install with an unprivileged user on Windows 10

### ISSUE THREAD

**Issue by DarkElve** [MustardChef/WSABuilds#30]
Even when running installer as an administrator.
![2023-03-09 03_17_17](https://user-images.githubusercontent.com/46492655/223890387-af610de3-ffd8-4b3b-a7c1-d4d8eaa5b48d.png)

Installs and works fine if interactively log in into admin, but still isn't visible from any other account.

**Comment by MustardChef** [comment]
@MustardChef Seems like [this is a problem with WSA and WSL itself](https://github.com/microsoft/WSL/issues/9521). If you use an unpriviliedge/other (non admin) account and try to install (even with elevation), it will not work. Hence, you will have to log into your admin account, to install it.

**Comment by DarkElve** [comment]
Well, can't say about WSA, but WSL works just fine, upgraded it to version 2 a couple of days ago. But probably clean install wouldn't work, seems like Microsoft broke something.
Thanks anyway, subscribed to the WSL issue too, maybe someone'll work something out.

**Comment by rom4ster** [comment]
Hello, I got a question from someone about this and was able to reproduce it myself. He claimed that there was no help given on the discord so I thought I would come here and petition for this to be open again. The issue you have linked to only mentions WSL but WSL does not exhibit this behavior on either system. If there is no evidence that this is a WSA issue, then could this be looked at? If however this is a WSA issue, then could we get a link to a thread that actually follows the issue in a WSA context so that people have a place to go to for questions. 

As of current this issue has no solution and no tracking which means it is likely to become forgotten. 

Thank You

**Comment by MustardChef** [comment]
@rom4ster I appreciate the concern, however I believe that the correct place to report this issue [here](https://github.com/LSPosed/MagiskOnWSALocal/issues), to the developer of the MagiskOnWSA installer script. Also, if this issue exists with official versions of WSA, then it would be advised to also open the issue in the [Microsoft Github repo for WSA]

**Comment by MustardChef** [comment]
If you would like, I can open a thread to discuss the issue at hand.

**Comment by rom4ster** [comment]
I appreciate it, this way people will know where to go, if I find any updates, I will mirror here

**Comment by MustardChef** [comment]
> I appreciate it, this way people will know where to go, if I find any updates, I will mirror here

Could you try the fixes shown in this guide, excluding the first one: https://windowsreport.com/specified-logon-session-not-exist/

**Comment by rom4ster** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/issues/276

Found this post on MagiskOnWSA, I have asked them to reopen it because their resolution was garbage

**Comment by MustardChef** [comment]
@rom4ster As mentioned in the issue thread above, the best method is to package up the build and self sign using a your own certificate with tools such as MSIX Hero. Then install the certificate on the admin account and then proceed to install the .msix file that you packaged as normall

**Comment by traversone** [comment]
> This is not applicable to my machine, I do not have microsoft account at all. I have tried with my admin account, and it works, my current solution is simultaneous remoting

hello! can you elaborate this "current solution is simulteneous remoting" ? I have some issue as many other users, thank you

**Comment by MustardChef** [comment]
> > This is not applicable to my machine, I do not have microsoft account at all. I have tried with my admin account, and it works, my current solution is simultaneous remoting
> 
> hello! can you elaborate this "current solution is simulteneous remoting" ? I have some issue as many other users, thank you

Are you referring to the issue being unable to install WSA on non-admin account?

**Comment by traversone** [comment]
yes, I am just referring to the issue being unable to installa WSA on a non-admin account...

**Comment by MustardChef** [comment]
> yes, I am just referring to the issue being unable to installa WSA on a non-admin account...

Well, the only solution is to package and sign the WSA build.

**Comment by traversone** [comment]
thank you MustardChef ! I was also under the impression that rom4ster adopted a simpler (at least for me as very basic user) solution "simultaneous remoting": maybe on the same machine we could access admin account from within non admin one

**Comment by rom4ster** [comment]
> thank you MustardChef ! I was also under the impression that rom4ster adopted a simpler (at least for me as very basic user) solution "simultaneous remoting": maybe on the same machine we could access admin account from within non admin one
> 
> @rom4ster: could you tell us if you do not mind?

Sure, simultaneous remoting is just that. You remote desktop to 127.0.0.2  (you may be familiar with 127.0.0.1 as a localhost but RDP will fail on that ip). I can then just use my android app on my admin account WHILE my normal account is logged in through remote desktop. 

UNFORTUNEATELY, this is not the super simple solution you are looking for as if you try this, you will get access denied (unless you have windows server for some reason). You need to look into the rdpwrapper project and then make sure you get a good update script so windows update does not bork the functionality.
