### ISSUE TITLE
[BUG] Got error msg when update WSA: WsaClient.exe. The application was unable to start correctly 0xc0000142. Click OK to close the application.

### ISSUE THREAD

**Issue by ansonfish** [MustardChef/WSABuilds#303]
### Describe the bug

I updated WSA according to the guideline, I got the error msg when I execute the step 8 'Run the Run.bat file', WsaClient.exe. The application was unable to start correctly 0xc0000142. Click OK to close the application.

I can Launch Windows Subsystem For Android Settings app, and see the WSA version has matched the version number that I want to update to. But I can't really start the WSA because WsaClient.exe error.

### Steps to reproduce the issue

Following the guideline 'Updateing:How do I update without losing any of my apps and data on Windows Subsystem for Android (WSA)';
[Download the latest build](https://github.com/MustardChef/WSABuilds#downloads) (that you want to update to)

Make sure Windows Subsystem For Android is not running (Click on "Turn off" in the WSA Settings and wait for the spinning loader to disappear)

Using 7-Zip, WinRAR or any other tool of choice, open the .7z archive

Within the .7z archive, open the subfolder

Select all the files that are within this subfolder and extract them to the current folder where the file for Windows Subsystem For Android (the folder you extracted, and installed WSA from) are located

When prompted to replace folders, select "Do this for all current items" and click on "Yes"

When prompted to replace files, click on "Replace the files in the destination"

Run the Run.bat file

### Expected behaviour

WSA start correctly.

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0

### Windows build number

Win11, 23620.1000

### PC Specification

Operating system name Microsoft Windows 11 Enterprise Insider Preview
Version 10.0.23620 Version 23620
Other operating system descriptions No information available
Operating system manufacturer Microsoft Corporation
System name YOGA
System manufacturer LENOVO
System model 81TC
System type x64-based computer
System SKU LENOVO_MT_81TC_BU_idea_FM_Yoga C740-14IML
Processor Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, 1608 Mhz, 6 cores, 12 logical processors
BIOS version/date LENOVO BNCN45WW, 2022/7/7
SMBIOS version 3.2
Embedded Controller Version 1.45
BIOS mode UEFI
Motherboard manufacturer LENOVO
Motherboard product LNVNB161216
Motherboard version SDK0L77769 WIN
platform role mobile
Secure boot status off
PCR7 configuration needs to be upgraded to view
Windows directory C:\WINDOWS
System directory C:\WINDOWS\system32
Start device \Device\HarddiskVolume1
Locale China
Hardware Abstraction Layer Version = "10.0.23620.1000"
Username A-B-YOGA\anson
Time Zone China Standard Time
Installed physical memory (RAM) 16.0 GB
Total physical memory 15.8 GB
Available physical memory 1.69 GB
Total virtual memory 31.6 GB
Available virtual memory 13.1 GB
Page file space 15.8 GB
Page file D:\pagefile.sys
Kernel DMA protection off
Virtualization-based security running
Security attributes based on virtualization security requirements
Security attributes provided by virtualization-based security Basic virtualization support, DMA protection, SMM Security Mitigations 1.0, pattern-based execution control
Virtualization-based security services configured
Virtualization-based security service running Credential Guard
Windows Defender Application Control Policy implemented
Windows Defender Application Control User Mode Policy Turn off
Device encryption support requires upgrade to view
Hypervisor detected. Features required by Hyper-V will not be displayed.

**Comment by MustardChef** [comment]
@ansonfish WSA should not be run from "WSAClient.exe". If Run.bat executes successfully, WSA should start automatically after installation. If WSA does not start, please check if the "Windows Subsystem For Android" entry has been created and then run it from there.
