### ISSUE TITLE
[REQUEST] GrapheneOS build

### ISSUE THREAD

**Issue by e-t-l** [MustardChef/WSABuilds#304]
### Describe your request

[GrapheneOS](https://grapheneos.org) is a security-hardened AOSP ROM that could provide some subtle security benefits to a WSA environment.

- Device Model: Pixel 5? (I don't know what difference this would make)
- Root Solution: None (the Graphene community is adamant that rooting is a huge security risk, so a Graphene WSA should be available rootless. Personally, I'm a fan of user choice, so if there could also be a build with KernelSU, that would be great)
- GApps: Shouldn't be necessary, as Graphene has [its own repo](https://github.com/GrapheneOS/Apps) of sandboxed Play Store, Services, and Framework apps (among others)
- Amazon Appstore: No

**Comment by MustardChef** [comment]
Out of the scope of the WSABuilds project.

**Comment by e-t-l** [comment]
Oh ok. In that case it's a little unclear what the custom build request part of the readme is talking about.
