### ISSUE TITLE
[BUG] Can't remove WSA with GApps completely (Win10)

### ISSUE THREAD

**Issue by Drysua** [MustardChef/WSABuilds#305]
### Describe the bug

After manually [uninstall](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/Uninstallation.md) and uninstalling with [this script](https://github.com/MustardChef/WSABuilds/blob/master/WSABuilds%20Utilities/Uninstall%20Script/WSAUninstaller.py) google tails are still in the system, but they are unremovable 
![Gapps unremoved](https://github.com/MustardChef/WSABuilds/assets/44484815/283c7cca-5d3d-4284-9d18-239459e07794)

### Steps to reproduce the issue

Install any WSA build with Gapps from Releases and try to uninstall manually or using script.

### Expected behaviour

WSA should be removed WITH Gapps

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z from [here](https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2311.40000.5.0)

### Windows build number

Windows 10 22H2 (OS Build 19045.3693)

### PC Specification

hp envy x360 13, Ryzen 5 4500u, 16 GB ram 

### Additional context

There is another [open issue](https://github.com/MustardChef/WSABuilds/issues/260) similar to mine, but it's still unresolved

**Comment by MustardChef** [comment]
Run:
```powershell
Get-AppxPackage -Name "MicrosoftCorporationII.WindowsSubsystemForAndroid" -AllUsers | Remove-AppxPackage -AllUsers
```
And then follow this guide to remove any entries that remain:
https://github.com/MustardChef/WSABuilds/blob/master/Documentation/Usage%20Guides/General%20Usage%20Guides/Remove%20Non%20Existent%20Entries.md
