### ISSUE TITLE
[BUG] WSA still not seeing the CPU virualization is enabled 

### ISSUE THREAD

**Issue by REXm4X** [MustardChef/WSABuilds#306]
### Describe the bug

installed with no issues , I tryed to do everything properly 

![PXL_20240209_211251880](https://github.com/MustardChef/WSABuilds/assets/159584107/e77a3cc7-cb44-497e-ad87-80abc9aaa669)

![Screenshot 2024-02-11 135542](https://github.com/MustardChef/WSABuilds/assets/159584107/fdc8fa63-74e4-4dce-a80c-1512d54035c5)

![Screenshot 2024-02-10 010221](https://github.com/MustardChef/WSABuilds/assets/159584107/268b6e3f-e3ee-41c4-a57a-9b3c81f43299)

### Steps to reproduce the issue

but I can't use due to not identifying the CPU's virualization 

### Expected behaviour

![Screenshot 2024-02-10 010036](https://github.com/MustardChef/WSABuilds/assets/159584107/92cf5fd5-e8e1-4ebd-8a89-1fdb2fac6fa4)

### Downloaded Build Of WSA

2311.40000.5.0
--

### Windows build number

OS build      22631.3085 

### PC Specification

CPU: Ryzen 5 5600x
Motherboard: PRIME B550M-K
GPU: RTX 3060 TI

### Additional context

any idea if I missed something ,

**Comment by MustardChef** [comment]
@REXm4X Follow https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPost-Install%20Issues%2FFixVirtError.md
