### ISSUE TITLE
[BUG] WSA with Magisk-Delta Kitsune

### ISSUE THREAD

**Issue by MichaelZ4714** [MustardChef/WSABuilds#309]
### Describe the bug

No app can be started.

### Steps to reproduce the issue

Today I built WSA on WSL Ubuntu 22 using
_sudo git clone https://github.com/WSABuilds/MagiskOnWSALocal.git
cd MagiskOnWSALocal
cd scripts
sudo ./run.sh_
and selected
  _x64
  retail version of WSA
  redfin
  root
  Magisk
  Delta
  No GApps
  No Amazon Store_
There was no build error.
When I start .\Install.ps1 there is no error message and Android Settings is launched. Three other apps are tried to start. But they fail to start and after some time the start messages disappear. 

### Expected behaviour

Android Settings can launch file manager.

### Downloaded Build Of WSA

The release variant is loaded from the script.

### Windows build number

10.0.22631.3007

### PC Specification

Microsoft Windows 11 Enterprise
HP Laptop 15s-fq1xxx

### Additional context

The same approach on 28th December 2023 resulted in working WSA.

**Comment by MustardChef** [comment]
@MichaelZ4714 you made sure that WSA's folder has a short name?

**Comment by MichaelZ4714** [comment]
No, I didn't know that it's necessary now. But same problem with C:\WSA. Magisk-Alpha also doesn't start. The KSU variant is OK. I will try Magisk Canary next.

**Comment by MichaelZ4714** [comment]
WSA with integrated Magisk-Canary works, even in long name directory.

**Comment by MichaelZ4714** [comment]
Here is the screen output of the Magisk-Delta build. Probably you can see whats's going wrong. I don't know if _system_ext: Duplicate or bad block in use!_ is bad.
[download.list.txt](https://github.com/MustardChef/WSABuilds/files/14275772/download.list.txt)
[michael@Michael-NB ~MagiskOnWSALocalscripts.txt](https://github.com/MustardChef/WSABuilds/files/14275777/michael%40Michael-NB.MagiskOnWSALocalscripts.txt)
