### ISSUE TITLE
Virtualisation Error

### ISSUE THREAD

**Issue by Fai1edMit0sis** [MustardChef/WSABuilds#31]
I keep getting this virtualisation error message, even though it's enabled in both BIOS and Windows, and I followed everything in the guide.

![Screenshot 2023-03-09 073800](https://user-images.githubusercontent.com/21115188/223930858-3d5df599-6830-4ad5-9cd7-88a7ffca0295.jpg)

Current Windows build: 19045.2604

**Comment by MustardChef** [comment]
@Fai1edMit0sis Have you tried following this [fix guide](https://github.com/MustardChef/WSABuilds/blob/master/Fixes/FixVirtError.md)

**Comment by Fai1edMit0sis** [comment]
@MustardChef Thanks for the the quick reply but I can't seem to find that Windows Subsystem for Android™ Settings this guide is referring to, either in the extracted folder or through the usual Programs & Features. However there's 'WsaSettings' which is possibly the same thing, but I can't uninstall it with a right click

![Screenshot 2023-03-09 081137](https://user-images.githubusercontent.com/21115188/223936719-e2fa5c6c-1128-4a58-8a9a-13150f468c44.jpg)

**Comment by MustardChef** [comment]
@Fai1edMit0sis Check if you can find it in the Start Menu and in Add and Remove Programs. If not, then feel free to delete  %LOCALAPPDATA%/Packages/MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe and continue to follow the guide

**Comment by Fai1edMit0sis** [comment]
@MustardChef Okay, it's working now. Thanks for the handy guide.

**Comment by MustardChef** [comment]
> @MustardChef Okay, it's working now. Thanks for the handy guide.

Feel free to reopen this issue, if you have any further problems or questions.
