### ISSUE TITLE
Install for all users on device[BUG]

### ISSUE THREAD

**Issue by simsonaubing** [MustardChef/WSABuilds#310]
### Describe the bug

Hi
I am new to APPX and have no Idea to get WSA working for all three users on my system. There is one administrator Account and two kids accounts. 

### Steps to reproduce the issue

I can install it on only one admin account. Even if I try to change a kids account to admin it is not possible to install the Package to a second one.

### Expected behaviour

I would like to  install WSA and Google Play Store to all three accounts

### Downloaded Build Of WSA

most recent

### Windows build number

10.0.22631

### PC Specification

x64

**Comment by MustardChef** [comment]
@simsonaubing

Due to the nature of unpacked MSIX packages, they cannot be installed on non-admin users/accounts without first repacking it back into an MSIX and then signing it with a certificate.

Whilst it is not difficult for us to provide WSA builds in a packed MSIX package (repackaged), the problem herein lies with the certificate that we use to sign the package with.

We can either pay a signing authority for a certificate or the user or I have to create a self signed certificate. Neither of these are ideal.

**Comment by simsonaubing** [comment]
in am stuck with installing the repackaged msix package...

I repackaged it via msix hero.
tried to sign the package per msixhero and via signtool.exe

I always get the HRESULT: 0x80073CF6 error.

Add-AppxPackage : Fehler bei Bereitstellung. HRESULT: 0x80073CF6, Das Paket konnte nicht registriert werden.
Fehler 0x800701C9: Beim Vorbereiten der Verarbeitung der Anforderung konnte die Erweiterung "windows.capability" aufgrund des 
folgenden Fehlers nicht registriert werden: Keines der autorisierten Entitätselemente in der SCCD stimmte mit der 
installierten App überein. Entweder stimmen die PFNs nicht überein, oder der Signaturhash des Elements kann nicht überprüft 
werden.

any hints?

**Comment by OvyDev** [comment]
I am trying to install for another user (UserB) after successfully installing it for the first user (UserA). 
Both users are admins, WSA are extracted in `C:\Users\UserA` for UserA and `C:\Users\UserB` for UserB, both are extracted from the file:  `WSA_2311.40000.5.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z `

I received this errors when executing run.bat for the second user (UserB):

> Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFB, The provided package is already installed, and
> reinstallation of the package was blocked. Check the AppXDeployment-Server event log for details.
> Another user has already installed an unpackaged version of this app. The current user cannot replace this with a
> packaged version. The conflicting package is MicrosoftCorporationII.WindowsSubsystemForAndroid and it was published by
> CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US.
> NOTE: For additional information, look for [ActivityId] 284acd4d-8709-0001-8e59-50280987da01 in the Event Log or use
> the command line Get-AppPackageLog -ActivityID 284acd4d-8709-0001-8e59-50280987da01
> At C:\users\Syifa\WSA\Install.ps1:162 char:1
> + Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceExists: (C:\users\Syifa\WSA\AppxManifest.xml:String) [Add-AppxPackage], PSInvali
>    dOperationException
>     + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Is there anyway I can do to have WSA available for both users ?
