### ISSUE TITLE
[BUG] Affects Edge Browser after turning on feature "Share user folder"

### ISSUE THREAD

**Issue by CharlesLiaoO** [MustardChef/WSABuilds#311]
### Describe the bug

After installing WSABuilds, the Edge browser sometimes can not open webpages. 

### Steps to reproduce the issue

1. Install WSABuilds
2. Open Edge browser, wait for about 30 seconds, open a web page

### Expected behaviour

The web page should be open, actually can not, while FireFox can.

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-NoGApps-RemovedAmazon_Windows_10.7z

### Windows build number

Windows 10 Pro (64bit) Version 22H2 (OS Build 19045.4046)

### PC Specification

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LCH-DELL
System Manufacturer	Dell Inc.
System Model	Inspiron 7570
System Type	x64-based PC
System SKU	07EA
Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 1992 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.25.0, 2022/7/13
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	06K08K
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume3
Locale	China
Hardware Abstraction Layer	Version = "10.0.19041.3636"
User Name	LCH-DELL\82056
Time Zone	China Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.8 GB
Available Physical Memory	8.54 GB
Total Virtual Memory	20.1 GB
Available Virtual Memory	11.1 GB
Page File Space	4.25 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by MustardChef** [comment]
@CharlesLiaoO From all the reports that have been made, we can conclude that Chrome and some Chromium based browsers are broken on WSA.

**Comment by CharlesLiaoO** [comment]
> @CharlesLiaoO From all the reports that have been made, we can conclude that Chrome and some Chromium based browsers are broken on WSA.

The Edge I mentioned is the app in Windows, not the Android app in WSA. 

Will WSABuild change system proxy or something like that? If I switch system proxy enable, reconnect network or/and restart Edge, this problem disappear temporarily but reoccur after about 30s.

**Comment by CharlesLiaoO** [comment]
Finally, I got the key of this issue.

It's the feature "Share user folders" of WSA affects the Edge's error. By the way, Chrome and Firefox don't have this issue.

# Steps to reproduce the issue:

1. Install WSABuilds

2. Open WSA setting, turn on the feature "Share user folders"
![image](https://github.com/MustardChef/WSABuilds/assets/49112356/f2424ec5-41b2-4209-b871-653e2510bf34)

3. Open File in WSA setting to trigger that feature to ON
![image](https://github.com/MustardChef/WSABuilds/assets/49112356/36d0bcb9-58bd-4fb2-beb9-7eaf85d0c7c5)

4. Open Edge browser, open a web page.
 
Now the Edge cannot reach the page. To avoid this issue, you need to turn that feature off AND reboot your PC.

**Comment by MustardChef** [comment]
Unfortunately, without being able to reproduce the issue, I cannot help.
