### ISSUE TITLE
[BUG] Installation error

### ISSUE THREAD

**Issue by fawnyeo** [MustardChef/WSABuilds#312]
### Describe the bug

Tried to download 2 different versions; Release NIghtly- MindtheGapps Amazon removed and the one with Magisk, both had the same error occurring when extracting
![image](https://github.com/MustardChef/WSABuilds/assets/102406279/c55e03e0-0f30-471b-b7c1-83733fdb3cd3)

### Steps to reproduce the issue

install and extract 

### Expected behaviour

successful instal

### Downloaded Build Of WSA

Release NIghtly- MindtheGapps Amazon removed and the one with Magisk

### Windows build number

2261.3155

### PC Specification

Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by MustardChef** [comment]
@fawnyeo Follow this fix: https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPre-Install%20Issues%2FExtraction%20Errors.md

**Comment by virotti** [comment]
Updating 7zip solved the issue.
