### ISSUE TITLE
[BUG]安装WSA后，无法启动子系统

### ISSUE THREAD

**Issue by Avenger233** [MustardChef/WSABuilds#313]
### Describe the bug

运行Run.bat后出现三个窗口
![image](https://github.com/MustardChef/WSABuilds/assets/51845433/f34c688b-a2ac-4ce1-8ca6-ddec8e42c5fe)
点击其中一个后就显示“正在启动适用于Android™的Windows子系统”
![image](https://github.com/MustardChef/WSABuilds/assets/51845433/c68ec5a6-89d4-4114-bcb8-034b76da21f4)
过一会就没了，点击剩余两个依旧是这样

### Steps to reproduce the issue

直接运行Run.bat

### Expected behaviour

无法安装

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0_Windows_10.7z

https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0_Windows_10.7z

### Windows build number

22H2 19045.3693

### PC Specification

![image](https://github.com/MustardChef/WSABuilds/assets/51845433/4ebb8750-f76f-4be5-9733-7148bc23a266)
![image](https://github.com/MustardChef/WSABuilds/assets/51845433/8caf5d14-c2fc-41c2-9c6c-46333915595a)

**Comment by Oxy4en** [comment]
你妈的 都打开子系统设置了不叫安装好了叫啥

**Comment by Avenger233** [comment]
> 你妈的 都打开子系统设置了不叫安装好了叫啥

章口就莱？
