### ISSUE TITLE
[BUG] Couldn't update Magisk 

### ISSUE THREAD

**Issue by rajarshikhatua100** [MustardChef/WSABuilds#314]
### Describe the bug

update failed in magisk

### Steps to reproduce the issue

try to update the magisk app

### Expected behaviour

Successfully updating

### Downloaded Build Of WSA

Latest

### Windows build number

Windows_11_2311.40000.5.0

### PC Specification

11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz   3.11 GHz
16.0 GB (15.8 GB usable)
64-bit operating system, x64-based processor

**Comment by MustardChef** [comment]
It is not possible to update Magisk via the app.

The only way that is possible is via updating WSA itself to a new version with the latest version of Magisk.
