### ISSUE TITLE
[BUG]  ID 709 -  "Rejecting a request to register from AppxBundleManifest.xml"

### ISSUE THREAD

**Issue by RaksitYar** [MustardChef/WSABuilds#315]
### Describe the bug

does not work "Run.bat"

Get-AppPackageLog -ActivityID d032e44a-..........

Time                      ID           Message
----                      --           -------
603          Started deployment Register operation on a package with main parameter AppxManif
                                       est.xml and Options DevelopmentModeOption and 0. See http://go.microsoft.com/fwl
                                       ink/?LinkId=235160 for help diagnosing app deployment issues.
216          App manifest validation warning: Declared namespace http://schemas.microsoft.com
                                       /developer/appx/2015/build is inapplicable, it will be ignored during manifest p
                                       rocessing.
709          Rejecting a request to register from AppxBundleManifest.xml because the manifest
                                        is not in the package root.
404          AppX Deployment operation failed for package  with error 0x80070057. The specifi
                                       c error text for this failure is: Registration request from AppxBundleManifest.xm
                                        l is rejected because the manifest is not in the root of the package.

### Steps to reproduce the issue

Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml

### Expected behaviour

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor. (Exc
eption from HRESULT: 0x80073CF9)
The request for registration from AppxBundleManifest.xml is rejected because the manifest is not in the root of the package.
NOTE: For additional information, look for [ActivityId] d032e44a-688e-000f-0667-33d08e68da01 in the Event Log or use th
e command line Get-AppPackageLog -ActivityID d032e44a-688e-000f-0667-33d08e68da01
At line:1 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0

### Windows build number

23H2 (22631.3155)

### PC Specification

ASUS ROG FLOW 13

**Comment by MustardChef** [comment]
@RaksitYar Update your extraction software (7-Zip/ WinRAR). The delete all your files, redownload the WSA Build and re-extract and try again.

**Comment by RaksitYar** [comment]
> @RaksitYarОновіть програмне забезпечення для видобування (7-Zip/WinRAR). Видаліть усі файли, повторно завантажте збірку WSA, розпакуйте та повторіть спробу.

7zip - 24.01. WinRAR - v6.24. Unzips without errors.
I checked all files of WSA. The files are actually missing.

**Comment by MustardChef** [comment]
@RaksitYar Could you tell me what files are missing?

**Comment by RaksitYar** [comment]
All WSA files deleted.

**Comment by RaksitYar** [comment]
![Run](https://github.com/MustardChef/WSABuilds/assets/33458725/1a961896-d2c7-40b6-99e5-ef42869ef739)
![Folder1](https://github.com/MustardChef/WSABuilds/assets/33458725/4fe62943-b972-4360-b33c-ce99b81bd57d)
![Folder2](https://github.com/MustardChef/WSABuilds/assets/33458725/e85fc0bf-e1e1-497e-ba83-b2c2bdf728f4)
![Folder3](https://github.com/MustardChef/WSABuilds/assets/33458725/ad0f8ce2-e97e-47f2-8591-daf96834a54e)

**Comment by MustardChef** [comment]
> ![Run](https://github.com/MustardChef/WSABuilds/assets/33458725/1a961896-d2c7-40b6-99e5-ef42869ef739)
> ![Folder1](https://github.com/MustardChef/WSABuilds/assets/33458725/fb0186d3-2908-4af9-9d5c-dfb977c0b643)
> ![Folder2](https://github.com/MustardChef/WSABuilds/assets/33458725/e85fc0bf-e1e1-497e-ba83-b2c2bdf728f4)
> ![Folder3](https://github.com/MustardChef/WSABuilds/assets/33458725/ad0f8ce2-e97e-47f2-8591-daf96834a54e)
> 
> 

Could you open the folder in Powershell and run:

```powershell
Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml
```

**Comment by RaksitYar** [comment]
![PS-run](https://github.com/MustardChef/WSABuilds/assets/33458725/1cdf71f1-2374-4b3d-bd4c-9c9f92a0733c)

**Comment by RaksitYar** [comment]
![test](https://github.com/MustardChef/WSABuilds/assets/33458725/10c851d7-a449-4584-9474-f32cf8674858)

**Comment by MustardChef** [comment]
> ![test](https://github.com/MustardChef/WSABuilds/assets/33458725/10c851d7-a449-4584-9474-f32cf8674858)
> 

You ran the command incorrectly.

**Comment by RaksitYar** [comment]
Didn't even pay attention =). A strange error occurred. Copied from the message.
![test2](https://github.com/MustardChef/WSABuilds/assets/33458725/6fb8bfb8-a62e-47b2-bf66-6cb6c12d8e95)

**Comment by MustardChef** [comment]
I was able to download and install the same build successfully.

**Comment by RaksitYar** [comment]
Last time I installed WSA PacMan together with WSA. Can it somehow affect now?

**Comment by akshayrathnavas** [comment]
I can confirm that even I am having the same error with the builds. I have tried the following.

WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0.7z
WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-65207f96-canary-MindTheGapps-13.0-RemovedAmazon.7z
WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-NoGApps-RemovedAmazon.7z
WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z

Windows Specifications:
Version: 23H2
OS Build: 22631.2262
Windows Feature Experience Pack 1000.22674.1000.0

Asus Zephryus G15 AMD Ryzen 9 5900HS

**Comment by akshayrathnavas** [comment]
@MustardChef 
@RaksitYar 
I was able to solve this issue using:

**https://github.com/WSA-Community/WSAGAScript/issues/28#issuecomment-992113337**

**Comment by MustardChef** [comment]
I will close this issue now. This problem should not occur on the latest LTS builds of WSA.
