### ISSUE TITLE
Feb 2024 Builds

### ISSUE THREAD

**Issue by MrJacquers** [MustardChef/WSABuilds#316]
### Describe your request

Just wondering if we'll get an update for February 2024?

**Comment by MustardChef** [comment]
> ### Describe your request
> 
> Just wondering if we'll get an update for February 2024?

Well, no WSA update has been released so far. Do note that we rely on Microsoft for updates.

**Comment by MrJacquers** [comment]
Thanks, makes sense :) I thought I saw a post / changelog somewhere for Feb 2024, but can't find it now.

**Comment by MustardChef** [comment]
> Makes senso to me as well. Maybe the point could be the upgrade to latest Magisk version, couldnt' it?
> 
> thank you

Makes sense. I will add a script that will add magisk updates to releases.

**Comment by MustardChef** [comment]
> > > Makes senso to me as well. Maybe the point could be the upgrade to latest Magisk version, couldnt' it?
> > > thank you
> > 
> > 
> > Makes sense. I will add a script that will replace the WSA builds with Magisk with the latest updated magisk version, every Magisk update.
> 
> I guess you don't have time to add support for magisk 27 yet?

Tomorrow.
