### ISSUE TITLE
[REQUEST]      Powershell script creation

### ISSUE THREAD

**Issue by azurejoga** [MustardChef/WSABuilds#317]
### Describe your request

Hello, I hope everyone is well.
I have one
[fully automated windows optimization program](github.com/azurejoga/Aurora-Windows-Optimizer/)

And I wanted to create a powershell script that would do the following with WSA.
1. asked the user which WSA he wants to download, such as which architecture, OS version, etc...
2. Find the latest github version available for that system, download it, extract it, run run.bat
3. before performing the two operations above, he performed
* powershell execution policy to allow running powershell scripts through github itself using use basic parcing
* Enabled all virtualization features.
1. After that, it would run run.bat and once installed, it would close the script. all of this in an automated way.
After talking a little about my project that will benefit everyone, I wanted to ask the following, the link to download the WSA versions, {all systems} are permanent links or are they dynamic links, that is, they change as soon as a new version is released?
Because if it's a dynamic link, I think it will be quite difficult for me to create a script that does what I'm thinking.
* What are your opinions?

**Comment by MustardChef** [comment]
This is a great idea. Feel free to open a PR and we can work together to get a utility like this setup.

**Comment by azurejoga** [comment]
Hello, yes, I want to implement this idea, but for that I need to know if the WSA links change depending on a new update, or are they static.. one drive

**Comment by MustardChef** [comment]
> Hello, yes, I want to implement this idea, but for that I need to know if the WSA links change depending on a new update, or are they static.. one drive 

We can implement a dynamically updating .json file with all the builds and their links.

**Comment by azurejoga** [comment]
Yes. that seems like a reasonable idea!  and then, the PowerShell script would do the following, consult the JSON file directly from github and behind it I would create a graphical interface using systém.windows.forms.  user would choose a build and it would start downloading then extract and run the rum.bat file.  Before these steps I could enable virtualization and open the policy to run unsigned scripts.

**Comment by azurejoga** [comment]
@MustardChef

**Comment by MustardChef** [comment]
> @MustardChef 

Great. I will start work on implementing this.

**Comment by azurejoga** [comment]
Ok, I'll write my part of the script soon, waiting for its implementation

**Comment by azurejoga** [comment]
I myself created a JSON implementation and a python script that
* automatically downloads the file with a progress bar showing how much time remains to download
* extracts the file and shows a message that the extraction is complete
* wx python graphical interface
* json file included in the repository for better example
# attention
I believe the only thing you will have to do is:
* create a method to extract a 7z file
* create another method to find the extracted folder and run run.bat as administrator, which is not difficult.
* I recommend using GPT if you don't want any work for this.
[Repository link here](https://github.com/azurejoga/luna-script)
# I hope this is done successfully!

**Comment by azurejoga** [comment]
Update me for anything new

**Comment by azurejoga** [comment]
Hello, any news?, were you able to implement it?

**Comment by MustardChef** [comment]
I have abandoned this, since WSA has been discontinued.
