### ISSUE TITLE
7-Zip Extract Error

### ISSUE THREAD

**Issue by Vect-r** [MustardChef/WSABuilds#319]
### Describe the bug

Whenever i try to extract the 7Z file it always gives this error

I downloaded the file again and it always gives the same error

![image](https://github.com/MustardChef/WSABuilds/assets/47442331/78e7ae24-b228-4a8e-b04a-f9a8df6c1bfb)

### Steps to reproduce the issue

1. Download [WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-NoGApps-RemovedAmazon_Windows_10.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-NoGApps-RemovedAmazon_Windows_10.7z)
2. Open it With 7-Zip
3. Click 'Extract'
4. Choose location to Extract
5. Wait for it to Extract.

### Expected behaviour

I thought it would Extract fully. But its not extracting and gives error.

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64

[WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-NoGApps-RemovedAmazon_Windows_10.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-NoGApps-RemovedAmazon_Windows_10.7z)

### Windows build number

Microsoft Windows 10 22H2 (OS Build 19045.4046)

### PC Specification

AMD Ryzen 5 4600H
16GB RAM
1TB NVMe
NVIDIA GTX 1650 Mobile

### Additional context

I want to try the Magisk with No GApps and no Amazon Store. Earlier i've installed G-Apps version and it worked pretty fine.

**Comment by MustardChef** [comment]
@Vect-r, Kindly refer to this [fix guide](https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPre-Install%20Issues%2FExtraction%20Errors.md), Thank You!

**Comment by Vect-r** [comment]
> @Vect-r, Kindly refer to this [fix guide](https://github.com/MustardChef/WSABuilds/blob/master/Documentation%2FFix%20Guides%2FPre-Install%20Issues%2FExtraction%20Errors.md), Thank You!

I Updated 7-Zip and it worked
Thank You
