### ISSUE TITLE
cannot install 8 ball pool beta version

### ISSUE THREAD

**Issue by Vip-ht** [MustardChef/WSABuilds#32]
cannot install and open 8 ball pool 12.0.0 beta 8 version.
apk file link: https://www.apklinker.com/apk/miniclip-com/8-ball-pool/8-ball-pool-5-12-0-beta8-release/8-ball-pool-5-12-0-beta8-android-apk-download/

**Comment by MustardChef** [comment]
@Vip-ht I will test this .apk file later today and report my findings.

**Comment by YT-Advanced** [comment]
@Vip-ht It is apk bundle file, so you need SAI to install it

**Comment by Vip-ht** [comment]
Update: this app has just been updated to 5.12.0 version in play store, but this app will close immediately when i open the newest version while 5.11.2 version is still working
