### ISSUE TITLE
bridge driver left 

### ISSUE THREAD

**Issue by jgsports** [MustardChef/WSABuilds#320]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

When I deleted wsl according to the tutorial, the system left the bridge driver, and the deletion error occurred, prompting 0x80071779 error.
![error](https://github.com/MustardChef/WSABuilds/assets/28648206/eca61bd1-7c1a-42df-8242-a1ce4cc01d70)

**Comment by MustardChef** [comment]
I think that you have been developing a huge misconception.

I would like to ask:
- Are you referring to WSA or WSL?
- What are you attempting to achieve?
