### ISSUE TITLE
[REQUEST] Able to preinstall hevc device manufacturer codec automatically on wsa installation

### ISSUE THREAD

**Issue by proganime1200** [MustardChef/WSABuilds#322]
### Describe your request

Fixes some codec issues  on some games that may used vulkan (blue archive intro goes black game uses vulkan)

The microsoft store that has free hevc codec are not supported anymore : https://apps.microsoft.com/detail/9n4wgh0z6vhq?hl=en-us&gl=us
Can you preinstall this script that install the codec for free i tested this already : https://github.com/Andrew-J-Larson/OS-Scripts/blob/main/Windows/Enable-HEIC-Extension-Feature.ps1

**Comment by MustardChef** [comment]
> ### Describe your request
> 
> Fixes some codec issues  on some games that may used vulkan (blue archive intro goes black game uses vulkan)
> 
> The microsoft store that has free hevc codec are not supported anymore : https://apps.microsoft.com/detail/9n4wgh0z6vhq?hl=en-us&gl=us
> Can you preinstall this script that install the codec for free i tested this already : https://github.com/Andrew-J-Larson/OS-Scripts/blob/main/Windows/Enable-HEIC-Extension-Feature.ps1
> 
> 

Thank you for the link. I will have a look.

**Comment by MustardChef** [comment]
Plan scrapped as WSA has been discontinued.
