### ISSUE TITLE
[DOC] Vulkan games very slow not performing well

### ISSUE THREAD

**Issue by proganime1200** [MustardChef/WSABuilds#324]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

Tried playing blue archive which is running on vulkan and im using the latest wsa the jan build 2024 even on lowest settings it does not performed well if change the vulkan driver from system default to d3d12 it just force closes the game the graphics performance are set to high performance gtx 1650 and memeory allocation to 6gb
My pc specs: 

    Windows 11 Pro
    Intel® Core™ i5-12450H
    8GB DDR4
    512GB NVMe SSD
    NVIDIA® GeForce GTX™ 1650

Games i used: Blue archive version 1.60.260228 not available from playstore

**Comment by MustardChef** [comment]
> ### Please provide a clear and concise description of the changes you would like to see made to the documentation.
> 
> Tried playing blue archive which is running on vulkan and im using the latest wsa the jan build 2024 even on lowest settings it does not performed well if change the vulkan driver from system default to d3d12 it just force closes the game the graphics performance are set to high performance gtx 1650 and memeory allocation to 6gb
> My pc specs: 
> 
>     Windows 11 Pro
>     Intel® Core™ i5-12450H
>     8GB DDR4
>     512GB NVMe SSD
>     NVIDIA® GeForce GTX™ 1650
> 
> Games i used: Blue archive version 1.60.260228 not available from playstore
> 
> 

Although I do not play Blue Archive, I downloaded it to check. From the loading screen to the main menu I am getting around 60fps with a bit of stutter (My GPU is an RX 5700XT.)

**Comment by proganime1200** [comment]
> Although I do not play Blue Archive, I downloaded it to check. From the loading screen to the main menu I am getting around 60fps with a bit of stutter (My GPU is an RX 5700XT and Vulkan is set to "System Default".)
> 
> Is the low performance occuring during gameplay?
Yes during the gameplay
