### ISSUE TITLE
[BUG]GApps report no wlan (when advancing Networking)

### ISSUE THREAD

**Issue by landall** [MustardChef/WSABuilds#327]
### Describe the bug

Other apps are OK.
Only GApps report there is no wlan.
It is the same when I connect my vpn in Windows (after restart WSA)

### Steps to reproduce the issue

run.bat to install the GApps.
This issue does not happen.
Enable Advancing Networking.
The issue happens.

### Expected behaviour

Act as the other apps.

### Downloaded Build Of WSA

2308.40000.3.0 in Windows 10 22H2

### Windows build number

Win10 22H2（19045）

### PC Specification

Asus B550M Wifi Plus
AMD R5 5600X
32GB RAM

**Comment by MustardChef** [comment]
Use the latest build of WSA!
