### ISSUE TITLE
[REQUEST] WSA-MagiskDelta-GApps-RemovedAmazon-Google Pixel Tablet

### ISSUE THREAD

**Issue by muhammadbahaa2001** [MustardChef/WSABuilds#328]
### Describe your request

I want latest version of WSA with root delta magisk + gapps + removed amazon store + model pixel tablet

**Comment by MustardChef** [comment]
This project is now in Long Term Support (LTS), no more requests will be fulfilled.
Sorry for any inconvenience caused.
