### ISSUE TITLE
Runtime errors when attempting to run WSAsettings.exe

### ISSUE THREAD

**Issue by Zorkanne** [MustardChef/WSABuilds#33]
Windows 10 x64, running in the latest version 19045.2604
google play and magisk work. But attempting to launch WSAsettings.exe gives runtimeerrors
VCRUNTIME140_1_APP.dll
VCRUNTIME140_APP.dll
MSVCP140_APP.dll
Things I tried
Installed runtimepack from here https://www.majorgeeks.com/files/details/runtimepack.html (suggested in XDA forums)
reinstalled all Visual Studio runtime manually
updated all the microsoft store apps that I have installed
uninstalled and reinstalled WSA (making sure there to clean up localappdata folder)
moved WSA folder.
tried PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1
tried Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml
Same errors pop up.

**Comment by YT-Advanced** [comment]
where did you run from, the Subsystem for Android on setting or mannual click on WSASetting.exe
If you run by mannual click, you will get this error (because the shorcut from Setting or Start load the DLL before load the file)

**Comment by Zorkanne** [comment]
I manually clicked on it
I couldn't find the "settings"or wsa shortcut after I was done installing
Only windows subsystem for android does show up when I look for it in the "add or remove programs" (but not settings)

**Comment by Zorkanne** [comment]
nevermind, language issue, it was called something in french, this is my bad
