### ISSUE TITLE
WSA Settings and App Windows

### ISSUE THREAD

**Issue by Spuner** [MustardChef/WSABuilds#333]
### Describe the bug

Application titles are black in color, when they should be white. The theme is set to "light" in the OS.

The WSA window cannot be moved + window management icons are not displayed. They are only displayed when you move the cursor over them or if the window is active.

I attach two screenshots

![08-03-2024-07-16-55 PM](https://github.com/MustardChef/WSABuilds/assets/30773815/055ed412-4548-4507-94e8-8bf4481260e1)

![2024-03-09 02_07_46-Greenshot](https://github.com/MustardChef/WSABuilds/assets/30773815/5f151a65-73a5-4007-a9f3-8005fb5246b2)

### Steps to reproduce the issue

It's all described in "Describe the bug".

### Expected behaviour

It's all described in "Describe the bug".

### Downloaded Build Of WSA

[2311.40000.5.0](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon_Windows_10.7z)

### Windows build number

Windows 10 Pro 22H2 (Build 19045.4046)

### PC Specification

[System Summary.txt](https://github.com/MustardChef/WSABuilds/files/14542390/System.Summary.txt)

**Comment by apple8409** [comment]
very Nice thanks

**Comment by MustardChef** [comment]
I cannot reproduce this bug on any of my systems. Since this is a minor bug, I would just ignore it.
