### ISSUE TITLE
Custom WSA Build

### ISSUE THREAD

**Issue by tanmaykahanhai** [MustardChef/WSABuilds#334]
### Describe your request

--arch x64 --release-type latest --root-sol kernelsu --magisk-ver stable --gapps-brand MindTheGapps --custom-model tangorpro --compress-format zip --remove-amazon

**Comment by MustardChef** [comment]
This project is now in Long Term Support (LTS), no more requests will be fulfilled.
Sorry for any inconvenience caused.
