### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shubham3173** [MustardChef/WSABuilds#340]
### Describe the bug

im not able to extrack files
![WhatsApp Image 2024-03-18 at 3 54 30 PM](https://github.com/MustardChef/WSABuilds/assets/96432028/4e72d520-7c54-48cc-a3a5-69120a64a2a5)

### Steps to reproduce the issue

whenever im trying to extract downloaded wsa file it shows error

### Expected behaviour

i want to extact file

### Downloaded Build Of WSA

[WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z)

### Windows build number

22635.3350

### PC Specification

![WhatsApp Image 2024-03-18 at 3 57 23 PM](https://github.com/MustardChef/WSABuilds/assets/96432028/4e5171c7-3d08-4ab2-a65c-c27e3b964df1)

Device name	shubham
Processor	AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
Installed RAM	8.00 GB (7.34 GB usable)
Device ID	5D3B6D92-D9E5-4EE8-92E6-36F569177BB3
Product ID	00327-30000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎18-‎01-‎2023
OS build	22635.3350
Experience	Windows Feature Experience Pack 1000.22688.1001.0

**Comment by MustardChef** [comment]
@shubham3173 Follow this guide: https://github.com/MustardChef/WSABuilds/blob/master/Documentation/Fix%20Guides/Pre-Install%20Issues/Extraction%20Errors.md
