### ISSUE TITLE
[BUG] WSA reinstalled but apps are still showing on the old install

### ISSUE THREAD

**Issue by MuhammedEmirArtan** [MustardChef/WSABuilds#346]
### Describe the bug

I installed this while ago and installed some apps. I removed WSA but not apps. Now i reinstalled WSA and old apps still show in the apps section.

### Steps to reproduce the issue

uninstall wsa not apps
install wsa again

### Expected behaviour

not showing old apps

### Downloaded Build Of WSA

it happens on all of them

### Windows build number

19045.4170

### PC Specification

intel i5-2310
4gb ddr3
amd radeon hd 5450 ,
enough storage

**Comment by MustardChef** [comment]
Reopen this issue if you are still faced the same problem.
