### ISSUE TITLE
[BUG] KernelSU was missing after deployed Nightly-with-KernelSU.

### ISSUE THREAD

**Issue by HumanMus1c** [MustardChef/WSABuilds#347]
### Describe the bug

KernelSU was not installed after deployed 
`WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v0.7.5-MindTheGapps-13.0-RemovedAmazon.7z.`
![image](https://github.com/MustardChef/WSABuilds/assets/46023154/299cb60a-4fa5-4444-8f05-934abd668391)

### Steps to reproduce the issue

1. Complete deploy.
2. Boot WSA.
3. Using WSA Toolbox to check status.
4. KernelSU was missing.

### Expected behaviour

KernelSU shouldn't be missing.

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v0.7.5-MindTheGapps-13.0-RemovedAmazon.7z

### Windows build number

Windows 11 23H2  22631.3374

### PC Specification

![PixPin_2024-03-30_15-59-53](https://github.com/MustardChef/WSABuilds/assets/46023154/810b4b24-2808-409c-9005-951a1a0a7ef5)

### Additional context

![image](https://github.com/MustardChef/WSABuilds/assets/46023154/02e5b4a2-9ae3-4571-87b3-9a59cb1ffd7a)

**Comment by MustardChef** [comment]
@HumanMus1c You will need to sideload the KernelSU Manager.

**Comment by HumanMus1c** [comment]
thanks, it's worked.
