### ISSUE TITLE
[BUG]KernelSU not working on newest nightly build

### ISSUE THREAD

**Issue by AvZ77** [MustardChef/WSABuilds#355]
### Describe the bug

![WSA KernelSU](https://github.com/MustardChef/WSABuilds/assets/74259662/5c331fa4-a9ad-40cc-8c34-f4e4e5df8861)

### Steps to reproduce the issue

Sideload KernelSU.apk and launch it after that.

### Expected behaviour

Working KernelSU without the red "Not Installed" part.

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v0.9.2-MindTheGapps-13.0-RemovedAmazon

### Windows build number

22631.3374

### PC Specification

No issues with my system.
Current gen CPU, last gen GPU. 
32GB ram and a SSD.
Windows 11 Pro.

**Comment by AvZ77** [comment]
the kernel files of KernelSU v9.0 I found working.. but not v9.2.
So it may be an issue on the KernelSU side of things.

**Comment by MustardChef** [comment]
I will take a look.

**Comment by ManyullynSword** [comment]
The 0.9.2 Release version of KernelSU really doesn't work properly on WSA, you can go to Actions to download the latest version of the kernel, those do work.

**Comment by MustardChef** [comment]
> The 0.9.2 Release version of KernelSU really doesn't work properly on WSA, you can go to Actions to download the latest version of the kernel, those do work.

Thank you for the information.

**Comment by AvZ77** [comment]
> The 0.9.2 Release version of KernelSU really doesn't work properly on WSA, you can go to Actions to download the latest version of the kernel, those do work.

Thanks, I didn't think of looking through there in Actions tab.
Now in KernelSU app it says: 
Working < GKI>
Version: 11756

So newer version number and it works.
I'll add a direct link here aswell:
[https://github.com/tiann/KernelSU/actions/runs/8534287672#artifacts](url)

**Comment by Schefflin** [comment]
> The 0.9.2 Release version of KernelSU really doesn't work properly on WSA, you can go to Actions to download the latest version of the kernel, those do work.

install boot.img failed……how to fix it?

**Comment by Schefflin** [comment]
> > The 0.9.2 Release version of KernelSU really doesn't work properly on WSA, you can go to Actions to download the latest version of the kernel, those do work.
> 
> Thank you for the information. I will update the builds promptly.

so should I build it by myself manually, or you will fix it?

**Comment by AvZ77** [comment]
> > The 0.9.2 Release version of KernelSU really doesn't work properly on WSA, you can go to Actions to download the latest version of the kernel, those do work.
> 
> install boot.img failed……how to fix it?

Download one of those kernel-WSA-x86_64-5.15.104.x.zip, I picked the one that ended with 4 but they all probably work so pick one.
Extract the zip.
Rename bzimage to kernel.
Move it to replace kernel in WSA\Tools folder.
WSA needs to be inactive for you to be able to replace kernel.

**Comment by MustardChef** [comment]
> > > The 0.9.2 Release version of KernelSU really doesn't work properly on WSA, you can go to Actions to download the latest version of the kernel, those do work.
> > 
> > 
> > Thank you for the information. I will update the builds promptly.
> 
> so should I build it by myself manually, or you will fix it?

I will fix it tomorrow, or you can follow the guide above.
