### ISSUE TITLE
How to customize the device model of WSA

### ISSUE THREAD

**Issue by zyleon1982** [MustardChef/WSABuilds#358]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

Device Model: Samsung SM-F9000
Root Solution: KernelSU
Magisk: Yes
GApps: Yes
Amazon Appstore: No

**Comment by MustardChef** [comment]
@zyleon1982 The WSABuilds repo has entered LTS. No Custom Builds request will be fulfilled anymore.
