### ISSUE TITLE
Sound doesn't work

### ISSUE THREAD

**Issue by B-u-r-a-G** [MustardChef/WSABuilds#36]
I tried changing my sound device, unplugging everything and some other stuff but I can't get sound in anything running via WSA. It doesn't matter what it is, nothing has sound.
Running Windows 10

**Comment by MustardChef** [comment]
@B-u-r-a-G What version of WSA are you running

**Comment by B-u-r-a-G** [comment]
2302.40000.6.0

**Comment by MustardChef** [comment]
Can you please join the Discord, so we can diagnose the issue

**Comment by B-u-r-a-G** [comment]
I did

**Comment by MustardChef** [comment]
@B-u-r-a-G After extensive testing, I was unable to reproduce the issue. Could you check if th issue persists with the latest version

**Comment by B-u-r-a-G** [comment]
The newest version works so I have no idea what was the problem

**Comment by MustardChef** [comment]
> The newest version works so I have no idea what was the problem

@B-u-r-a-G So the issue is fixed now?

**Comment by B-u-r-a-G** [comment]
Yes

**Comment by MustardChef** [comment]
Thank you, I will close this issue now. Feel free to open, if the issue occurs again or if you have any updates regarding this matter
