### ISSUE TITLE
[BUG] Magisk_Overlayfs

### ISSUE THREAD

**Issue by Schefflin** [MustardChef/WSABuilds#360]
### Describe the bug

On WSA with 27.0 and above 27.0 version Magisk, if install module "Magisk_Overlayfs", root will be gone!
Besides, this module can work on 26.4-stable Magisk, but canary Magisk.
I think this is a well-known problem, but I don't find any way to fix it on 27.0 Magisk.
Please let me know how to fix it, thanks.

### Steps to reproduce the issue

install module "Magisk_Overlayfs"
reboot WSA
open Magisk and check root state

### Expected behaviour

"Magisk_Overlayfs" normally works on 27.0 Magisk

### Downloaded Build Of WSA

WSA_LTS1
WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-65207f96-canary-MindTheGapps-13.0-RemovedAmazon.7z

### Windows build number

Windows 11 x64

### PC Specification

laptop
Intel gen10 i5
Memory 32G

### Additional context

someone say “27.0 does work, you just need to compile it first since the release is broken on 27.0”
but no more details, so I don't have tried it yet.

**Comment by MustardChef** [comment]
Yes, Overlay_FS from Github releases is broken. If you build it yourself, it will work fine.

**Comment by Schefflin** [comment]
> Yes, Overlay_FS from the Github releases is broken. If you build it yourself, it will work fine.

@MustardChef not clear…Does it just git clone and run build.sh, no more modifications?
Then what packages do I need to install to build it on WSL? There are some commands do not find…

**Comment by MustardChef** [comment]
Clone the OverlayFS repo and use GitHub Actions to build.

**Comment by Schefflin** [comment]
> Clone the OverlayFS repo and use GitHub Actions to build.

Thank you, I've learned a lot……year, it works

**Comment by Schefflin** [comment]
> 克隆 OverlayFS 存储库并使用 GitHub Actions 进行构建。

Well, root is fine now, but module doesn't work……cannot mount as rw

**Comment by MustardChef** [comment]
> > 克隆 OverlayFS 存储库并使用 GitHub Actions 进行构建。
> 
> Well, root is fine now, but module doesn't work……cannot mount as rw

Which module?

**Comment by Schefflin** [comment]
> > > 克隆 OverlayFS 存储库并使用 GitHub Actions 进行构建。
> > 
> > 
> > Well, root is fine now, but module doesn't work……cannot mount as rw
> 
> Which module?

Magisk_overlayfs
I had to spend more time to do a test, particularly on this version:

https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v0.7.5-MindTheGapps-13.0-RemovedAmazon.7z

——"Magisk_Overlayfs" Recompiled (yes,I recompile it by GitHub Action)module(3.2.2) doesn't work, but 3.2.1 work well. I guess the reason is that internal certain files of both modules are different, so it's not related to WSA kernel.
