### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by 1Nisal** [MustardChef/WSABuilds#361]
### Describe your request

can you make lite version with google go editions? i hope it fast with start . i dont know about how it works.

**Comment by IntNinja** [comment]
> ### Describe your request
> can you make lite version with google go editions? i hope it fast with start . i dont know about how it works.

Possible since android 12 has a go edition.

**Comment by MustardChef** [comment]
Unfortunately, since the WSABuilds repo has entered LTS Mode.
