### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DARK7BEA5T** [MustardChef/WSABuilds#363]
### Describe the bug

installed magisk version, but it aint working as it should

### Steps to reproduce the issue

i just ran run.bat .

### Expected behaviour

magisk app is install but magisk is not.
direct installed failed, and i dont have patch file.
![image](https://github.com/MustardChef/WSABuilds/assets/150522146/abeff2d6-70ae-4ea4-bd7f-4723152f8294)
![image](https://github.com/MustardChef/WSABuilds/assets/150522146/8952c4b8-0b0b-40d1-9645-927ad805130d)
![image](https://github.com/MustardChef/WSABuilds/assets/150522146/38ddf318-6e72-4e42-b3d8-eec45fd4ac27)
even tried installing with the magisk.apk file as patch.

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0_Windows_10

### Windows build number

WIN 10 22H2 19045.4291

### PC Specification

surpasses minimum requirement for win 11.
16 GB ram
256 GB ssd (+ 0.5TB HDD)
GTX 1650
Intel i7-9750H

**Comment by MustardChef** [comment]
@DARK7BEA5T Magisk literally says that it is Installed!!!

**Comment by DARK7BEA5T** [comment]
sorry,
i think i might have read zygisk as magisk.
