### ISSUE TITLE
[BUG] Apps for AndroidTV work great but open screens in new windows instead of the same one

### ISSUE THREAD

**Issue by leverageinventions** [MustardChef/WSABuilds#364]
### Describe the bug

While using an Android/Google TV app it works good but opens each screen in a separate window instead of the same app window.

### Steps to reproduce the issue

1. Install an Android TV app, in this example I used SmartTube app from https://github.com/yuliskov/SmartTube
2. Start the app
3. Enter a video or go to the setting options from the menu on the left and select General or UI.
4. Either way the next screen (which is the player if you click in a video or the settings panel in the other case) will open in a separate window instead of the same one.

### Expected behaviour

All screens should open in the same window as with all Android apps.

### Downloaded Build Of WSA

The last LTS version:
WSA_2311.40000.5.0_x64_Release-Nightly-GApps-13.0-NoAmazon_Windows_10

### Windows build number

19045.3930

### PC Specification

Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 2601 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	16.0 GB
Adapter Description	NVIDIA GeForce GTX 960M

**Comment by MustardChef** [comment]
Its an issue with how those sections are implemented and an issue with how WSA handles that. Nothing much I can do to help.

**Comment by leverageinventions** [comment]
Got it, thanks for your work
