### ISSUE TITLE
[BUG] Swipe lockscreen functionnality

### ISSUE THREAD

**Issue by Baalfrog** [MustardChef/WSABuilds#365]
### Describe the bug

Issue after activating Swipe function

### Steps to reproduce the issue

Go to advanced parameters, activate dev modus. click on manage dev parameters
look for security,  click on lockscreen and activate swipe.
Reboot the computer.

### Expected behaviour

Continue to be able to go back to manage dev parmaeters or run an app.
it seems without swipe function activated everything is working fine. after activating there is no way to go back to menu or to run apps.

### Downloaded Build Of WSA

All 2311.40000xxx revision

### Windows build number

Windows 11 23H2 (22631.3447)

### PC Specification

Lenovo Thinkbook tried with Lenovo P53 same issue (computers are enterprise managed but with local admin rights). 

### Additional context

At first congratulation for all you did ! 
My need is to launch an Android apps on a windows 11 computer with sensitive screen. 
The laucnhed app requires a lock screen then I have at least to activate Swipe modus. the issue is when activated there is no way to launch the app anymore (it was running without). 
I tried with older WSA revision but as soon as the developper option is activated it download automatically the last revision. Then no way to go further. 
I check before restarting the computer and the app works (I can go to manage developper parameters too) but as soon as the computer is restared there is no error message, just the computer starts the WSA sub system for windows and nothing happens. 
It seems the issue occurs just after activating swipe function. before evething seems ok  (except my needed software said : you have to setup a lockscreen, as I'm on a compagny which manage safety I can't activated pin code to log my windows session then the software don't allow me to continue. 
With Swipe modus activated my software is working up to a reboot (or restart). 
My goal is to allow all my team to use "Field Service" apps from Salesforce to be run from a tactile computer (greater screen and no need to buy android or apple tablets). 
is there a way to simulate the lockscreen or to correct this behaviour? 
Thanks a lot for your help :-)
Regards

**Comment by MustardChef** [comment]
A video highlighting the issue would be helpful. 
Please note that it is not possible to use a lock screen on WSA.

**Comment by MustardChef** [comment]
Unfortunately there is no workaround for apps that explicitly require a lock screen without some sort of tampering with the app.

**Comment by Baalfrog** [comment]
Hi thank you for your work and to try to. I totally understand your anwser

**Comment by shiypc** [comment]
if you accidentally enabled swipe lock screen and can't get back in, run `adb shell settings put secure lockscreen_disabled 1` in cmd and reboot. apps will work again.
