### ISSUE TITLE
[REQUEST] Unlimited G-Drive storage

### ISSUE THREAD

**Issue by DARK7BEA5T** [MustardChef/WSABuilds#366]
### Describe your request

any working Unlimited G-Drive storage module? with WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0_Windows_10
Magisk module?
i have tried a module, added it, when i reboot (required by magisk) it vanishes. idk if its some problem with module, or wsa.
if any unlimited g drive storage module works, plz share with me.

**Comment by MustardChef** [comment]
@DARK7BEA5T Make sure that you get the LTS builds.

**Comment by DARK7BEA5T** [comment]
> @DARK7BEA5T Make sure that you get the LTS builds.

LTS builds have pre-built pixel storage?

**Comment by MustardChef** [comment]
> > @DARK7BEA5T Make sure that you get the LTS builds.
> 
> LTS builds have pre-built pixel storage?

No, but it should fix the Magisk module disappearing issue so that you can use a module like Pixelify to get unlimited Google Photos storage.

**Comment by DARK7BEA5T** [comment]
i follow all the steps to uninstall, but after installation, i see those old apps again.
![image](https://github.com/MustardChef/WSABuilds/assets/150522146/37746209-0a75-442c-a10a-a84c31df1457)

**Comment by DARK7BEA5T** [comment]
What to do?
![image](https://github.com/MustardChef/WSABuilds/assets/150522146/e1aba790-859a-412f-bba4-cc11bf771c8a)

**Comment by DARK7BEA5T** [comment]
> What to do? ![image](https://private-user-images.githubusercontent.com/150522146/323104981-e1aba790-859a-412f-bba4-cc11bf771c8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzY0MzgsIm5iZiI6MTcxMzMzNjEzOCwicGF0aCI6Ii8xNTA1MjIxNDYvMzIzMTA0OTgxLWUxYWJhNzkwLTg1OWEtNDEyZi1iYmE0LWNjMTFiZjc3MWM4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwNjQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjdhYWVmYmZiNGFiNGYzZTRiOTM5ZDM5M2U0YjVhZjU5ZTEyZGVjMzY4OTBjNGIxZDBkOTc3Zjc4MGFlZjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-GOv9IXzVCLOgNXc7pNoyoMos0wRKWz0iHt_UgwPm60)

downloaded pixelify as you told, but it asks for volume . i tried increasing and decreasing windows volume, also tried "adb shell input keyevent 24" and "adb shell input keyevent 25", none of these method worked.

**Comment by MustardChef** [comment]
> What to do? ![image](https://private-user-images.githubusercontent.com/150522146/323104981-e1aba790-859a-412f-bba4-cc11bf771c8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzY0MzgsIm5iZiI6MTcxMzMzNjEzOCwicGF0aCI6Ii8xNTA1MjIxNDYvMzIzMTA0OTgxLWUxYWJhNzkwLTg1OWEtNDEyZi1iYmE0LWNjMTFiZjc3MWM4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwNjQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjdhYWVmYmZiNGFiNGYzZTRiOTM5ZDM5M2U0YjVhZjU5ZTEyZGVjMzY4OTBjNGIxZDBkOTc3Zjc4MGFlZjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-GOv9IXzVCLOgNXc7pNoyoMos0wRKWz0iHt_UgwPm60)
> 
> downloaded pixelify as you told, but it asks for volume . i tried increasing and decreasing windows volume, also tried "adb shell input keyevent 24" and "adb shell input keyevent 25", none of these method worked.

Get the non VK .zip file!!!!
