### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chuck00000** [MustardChef/WSABuilds#369]
### Describe the bug

Display size( System UI Zoom) always automatically reset to default  after turning off subsystem. This issues happens in many WSA builds until now.
![Screenshot 2024-04-22 123008](https://github.com/MustardChef/WSABuilds/assets/98159699/5cd37830-53fd-4ab1-bd61-0c34c9644db5)

### Steps to reproduce the issue

Display size( System UI Zoom) always automatically reset to default  after turning off subsystem. I have to set again.

### Expected behaviour

Display size( System UI Zoom) always automatically reset to default  after turning off subsystem. I have to set again.

### Downloaded Build Of WSA

2311.40000.5.0_x64

### Windows build number

26200

### PC Specification

null

**Comment by MustardChef** [comment]
@chuck00000 Default behaviour of WSA.
