### ISSUE TITLE
[BUG] KernelSU missing

### ISSUE THREAD

**Issue by rainman74** [MustardChef/WSABuilds#370]
### Describe the bug

Installed: WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v0.9.2-MindTheGapps-13.0-RemovedAmazon.7z

Installed: KernelSU-0.9.2.11682.apk (KernelSU_v0.9.3_11804.apk tested, too)

KernelSU is missing:
![image](https://github.com/MustardChef/WSABuilds/assets/16306963/92836dca-182f-48be-8e37-95fba0be861a)

### Steps to reproduce the issue

Install WSA
Install KernelSU.apk
Open KernelSU

### Expected behaviour

KernelSU is installed

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v0.9.2-MindTheGapps-13.0-RemovedAmazon.7z

### Windows build number

Windows 11 Build 10.0.22631.3520

### PC Specification

Windows 11 Pro
Prozessor 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz, 3504 MHz, 8 Kern(e), 16 logische(r) Prozessor(en)

**Comment by MustardChef** [comment]
@rainman74 It was a bug with KernelSU v0.9.2 which is why it does not work on WSA.
Follow: https://github.com/MustardChef/WSABuilds/issues/355#issuecomment-2041167293
Or alternatively, wait for the next LTS builds.
