### ISSUE TITLE
No connection to my UPNP devices after WSA_2305.40000.6.0_x64

### ISSUE THREAD

**Issue by hjfisch** [MustardChef/WSABuilds#371]
### Describe the bug

Cannot connect to my audioplayer with Bubbleupnp after this Release . Had the same prob with the Subsystem from the Appstore , so I'm still on WSA_2305.40000.6.0_x64 .

### Steps to reproduce the issue

Bubbleupnp is starting but could not find any player

### Expected behaviour

My player is shown and ready to connect to

### Downloaded Build Of WSA

Any after 2305.40000.6.0

### Windows build number

22631.3527

### PC Specification

Razer Blade 14

**Comment by MustardChef** [comment]
I have not tested whether UPNP works between WSA and Windows or WSA and WSA on the latest version.

Get the latest build of WSA from this repo and enable "Local Network Access" and try again.

**Comment by hjfisch** [comment]
No Luck . Since change to "Local Network Access" from "Advance Network" by MS it won't work .

**Comment by MustardChef** [comment]
I guess that you will have to continue using the older version.

This issue has been known for quite a while, but still has not been fixed and probably never will be fixed (unless someone finds an unofficial workaround).
