### ISSUE TITLE
[BUG] Failling to Start on Windows 10 21H2

### ISSUE THREAD

**Issue by Astra060** [MustardChef/WSABuilds#372]
### Describe the bug

I had version 2309 installed, I decided to upgrade. Like before, which I upgraded from 2306 to 2309, I uninstalled WSA from settings app, and extracted the folder and ran run.bat. The Installation Fails? I'm not sure what to make of it. I tried reinstalling .Net, Updated my device. Nothing. 
Error are shown in Powershell window after installation:
```
Start-Process : This command cannot be run due to the error: The parameter is incorrect.
At D:\5.Software\Windows\Windows Subsystem\Android\Install.ps1:59 char:5
+     Start-Process "wsa://com.android.vending"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Start-Process : This command cannot be run due to the error: The parameter is incorrect.
At D:\5.Software\Windows\Windows Subsystem\Android\Install.ps1:60 char:5
+     Start-Process "wsa://com.android.settings"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : I
```
I also can't run WSA Settings App, says there are runtime libraries missing, which I reinstalled and checked were fine. DLLs are: ``` VCRUNTIME140_APP.dll MSVCP140_APP.dll VCRUNTIME140_1_APP.dll ```

The Settings App does Auto-Launch after installation though, and there missing icons, and it basically does nothing.

Edit:
Forgot to Mention. It says "All Done". I also sometimes saw Package has no identity. Window closes fast so I can't copy it.

This is also shown on the errors of Powershell:
```
Deployment operation progress: D:\5.Software\Windows\Windows Subsystem\Android\AppxManifest.xml                            Processing                                                                                                              [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo] 
```

### Steps to reproduce the issue

Just run run.bat on Windows 10 21H2

### Expected behaviour

WSA should have installed like before. I tried installing older version which was installed and it still produced same errors.

### Downloaded Build Of WSA

WSA_2306.40000.4.0_x64_Release-Nightly-with-magisk-ee34f775.26105.-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10
WSA_2308.40000.3.0_x64_Release-Nightly-with-magisk-d4e552d0.26301.-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10
WSA_2309.40000.2.0_x64_Release-Nightly-with-magisk-d4e552d0.26301.-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10
WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-65207f96-canary-MindTheGapps-13.0-RemovedAmazon_Windows_10

### Windows build number

Win 10 21H2 19044.2965

### PC Specification

Laptop TUF A15
Ryzen 4800H
RTX 2060m
16GB RAM

### Additional context

I tried installing all the listed versions. This worked fine until I removed and attempted reinstall.

**Comment by MustardChef** [comment]
Please download and install the latest LTS builds (via the Pre-Release button) and before running ``Run.bat``, run the following command below:
```powershell
Get-AppxPackage -Name "MicrosoftCorporationII.WindowsSubsystemForAndroid" -AllUsers | Remove-AppxPackage -AllUsers
```

**Comment by Astra060** [comment]
> Please download and install the latest LTS builds (via the Pre-Release button), but before running `Run.bat`, run the following command below:
> 
> ```powershell
> Get-AppxPackage -Name "MicrosoftCorporationII.WindowsSubsystemForAndroid" -AllUsers | Remove-AppxPackage -AllUsers
> ```

Same as before, tried the LTS Build #1:
```
Start-Process : This command cannot be run due to the error: The parameter is incorrect.
At D:\5.Software\Windows\Windows Subsystem\Android\Install.ps1:52 char:5
                                                                                                                         Deployment operation progress: D:\5.Software\Windows\Windows Subsystem\Android\AppxManifest.xml                            Processing                                                                                                              [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]                                                                                                                              Start-Process : This command cannot be run due to the error: The parameter is incorrect.
At D:\5.Software\Windows\Windows Subsystem\Android\Install.ps1:53 char:5
+     Start-Process "wsa://com.android.vending"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

**Comment by MustardChef** [comment]
> > Try installing from the C (system) drive.
> 
> Okay this fixed it, but my System Drive, is low on space... Any fix other than Junctions?
> 
> Plus I'm extremely puzzled. Why? I hardly let OS changes on my system.

[Follow this guide](https://www.reddit.com/r/WSA/comments/11pepvi/comment/jc596pr/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) to move all the WSA data files to your D drive after installation.
