### ISSUE TITLE
[BUG] WsaSettings Missing Icons

### ISSUE THREAD

**Issue by Astra060** [MustardChef/WSABuilds#373]
### Describe the bug

Everything functions as intended, except there are no icons? They only show after the initial installation which settings app auto launches. 
![ApplicationFrameHost_IMG 3259](https://github.com/MustardChef/WSABuilds/assets/84774057/9cc595aa-2302-4ea0-bfaa-6173253c712b)

### Steps to reproduce the issue

Running the Settings Panel. Tried from both the shortcut and WSA System Control

### Expected behaviour

There should be icons in these panels like the first time panel is auto launched and running run.bat

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-81658d45.27002.-canary-GApps-13.0-NoAmazon_Windows_10

### Windows build number

Win 10 21H2 19044.2965

### PC Specification

TUF A15
Ryzen 4800H

**Comment by MustardChef** [comment]
First time I have seen something like this occur.

**Comment by Astra060** [comment]
> First time I have seen something like this occur. Does reopening the app or reinstalling fix the issue?

Truly a Mistry... uninstalled multiple time... reinstalled... used Powershell, Settings, ...
In The End:
1. Uninstalled with Bulk Crap Uninstaller for a through clean up of remaining Files
2. Installed on System Drive
3. Then created Junction to a new folder

Tnx for the quick response.
