### ISSUE TITLE
[BUG] Google Play Crashing on Launch

### ISSUE THREAD

**Issue by FroggMaster** [MustardChef/WSABuilds#374]
### Describe the bug

Play Store crashing on launch.

### Steps to reproduce the issue

- Freshly installed  WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-81658d45.27002.-canary-GApps-13.0-NoAmazon.7z
- Launched Google Play
- Google Play instantly closes

### Expected behaviour

Google Play to function

### Downloaded Build Of WSA

 WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-81658d45.27002.-canary-GApps-13.0-NoAmazon.7z
and
 WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v0.9.3-MindTheGapps-13.0-RemovedAmazon.7z

### Windows build number

23H2 Build 22631.2861

### PC Specification

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-8BB39M2
System Manufacturer	Micro-Star International Co., Ltd.
System Model	MS-7D89
System Type	x64-based PC
System SKU	Default string
Processor	13th Gen Intel(R) Core(TM) i9-13900K, 3000 Mhz, 24 Core(s), 32 Logical Processor(s)
BIOS Version/Date	American Megatrends International, LLC. 1.90, 10/26/2023
SMBIOS Version	3.6
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	MPG Z790 CARBON WIFI (MS-7D89)
BaseBoard Version	1.0
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume7
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.2506"
User Name	DESKTOP-8BB39M2\Frog
Time Zone	Pacific Daylight Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.8 GB
Available Physical Memory	20.8 GB
Total Virtual Memory	36.8 GB
Available Virtual Memory	19.9 GB
Page File Space	5.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
Virtualization-based security Services Running	Hypervisor enforced Code Integrity
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Audit
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by FroggMaster** [comment]
I uninstalled WSA from the start menu
Deleted the WSA app
Then reinstallled again, and it now seems to be working.

**Comment by fragtion** [comment]
> I uninstalled WSA from the start menu Deleted the WSA folder Then reinstalled the KernelSU version again, and it now seems to be working.

Been having constant app crashes on Magisk builds here for me too...
KernelSU version is working flawlessly, thanks for this suggestion 👍🏻
