### ISSUE TITLE
[BUG] Virtualization is enabled, but the application refuses to start

### ISSUE THREAD

**Issue by MAX1MDEV** [MustardChef/WSABuilds#375]
### Describe the bug

I install the app, the wsa window opens and it immediately writes that virtualization is not enabled through the bios. Please note that everything is enabled in bios and windows components!

### Steps to reproduce the issue

During installation.

### Expected behaviour

I'm looking forward to running wsa with no errors

### Downloaded Build Of WSA

[WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0/WSA_2311.40000.5.0_x64_Release-Nightly-MindTheGapps-13.0-RemovedAmazon.7z)

### Windows build number

Windows 11 23H2

### PC Specification

<Элемент><![CDATA[Имя ОС]]></Элемент>
<Значение><![CDATA[Майкрософт Windows 11 Домашняя для одного языка]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Версия]]></Элемент>
<Значение><![CDATA[10.0.22631 Сборка 22631]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Дополнительное описание ОС ]]></Элемент>
<Значение><![CDATA[Недоступно]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Изготовитель ОС]]></Элемент>
<Значение><![CDATA[Microsoft Corporation]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Имя системы]]></Элемент>
<Значение><![CDATA[MSI]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Изготовитель]]></Элемент>
<Значение><![CDATA[Micro-Star International Co., Ltd.]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Модель]]></Элемент>
<Значение><![CDATA[Modern 15 A5M]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Тип]]></Элемент>
<Значение><![CDATA[Компьютер на базе x64]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[SKU системы]]></Элемент>
<Значение><![CDATA[155L.1]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Процессор]]></Элемент>
<Значение><![CDATA[AMD Ryzen 5 5500U with Radeon Graphics, 2100 МГц, ядер: 6, логических процессоров: 12]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Версия BIOS]]></Элемент>
<Значение><![CDATA[American Megatrends International, LLC. E155LAMS.111, 16.10.2021]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Версия SMBIOS]]></Элемент>
<Значение><![CDATA[3.3]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Версия встроенного контроллера]]></Элемент>
<Значение><![CDATA[255.255]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Режим BIOS]]></Элемент>
<Значение><![CDATA[UEFI]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Изготовитель основной платы]]></Элемент>
<Значение><![CDATA[Micro-Star International Co., Ltd.]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Модель основной платы]]></Элемент>
<Значение><![CDATA[MS-155L]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Версия основной платы]]></Элемент>
<Значение><![CDATA[REV:1.0]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Роль платформы]]></Элемент>
<Значение><![CDATA[Мобильный]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Состояние безопасной загрузки]]></Элемент>
<Значение><![CDATA[Вкл.]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Конфигурация PCR7]]></Элемент>
<Значение><![CDATA[Для просмотра требуется повышение прав]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Папка Windows]]></Элемент>
<Значение><![CDATA[C:\WINDOWS]]></Значение>
</Data>
<Data>
<Элемент><![CDATA[Системная папка]]></Элемент>
<Значение><![CDATA[C:\WINDOWS\system32]]></Значение>

**Comment by MAX1MDEV** [comment]
OS	Windows 11 23H2 Home
Version	10.0.22631 22631
Laptop MSI Модель	Modern 15 A5M
x64
Processor AMD Ryzen 5 5500U with Radeon Graphics, 2100 Mhz

**Comment by MustardChef** [comment]
Follow: https://github.com/MustardChef/WSABuilds/blob/master/Documentation/Fix%20Guides/Post-Install%20Issues/FixVirtError.md

**Comment by MAX1MDEV** [comment]
nothing of this not helps

**Comment by MustardChef** [comment]
Official Windows?

**Comment by MAX1MDEV** [comment]
of course
"Have you run a Debloater script on the OS?". The most I have uninstalled is manually uninstalling the Windows Teams program using Windows settings

**Comment by MAX1MDEV** [comment]
Apparently, I'll be the 0.000001% that couldn't run WSA.

**Comment by MustardChef** [comment]
> nothing of this not helps

You followed every step?

**Comment by MAX1MDEV** [comment]
of course. i may screenshot my setting if you need

**Comment by MAX1MDEV** [comment]
> Apparently, I'll be the 0.000001% that couldn't run WSA.

Or do you have something no one else knows about and you can help me?

**Comment by MustardChef** [comment]
Do you have any other VM, Emulator or other virtualization software installed?

**Comment by MAX1MDEV** [comment]
> Do you have any other VM, Emulator or other virtualization software installed?

Bluestacks and virtual box, but msi not running too

**Comment by MAX1MDEV** [comment]
msi bluestack - name of app

**Comment by MAX1MDEV** [comment]
delete this app?

**Comment by MAX1MDEV** [comment]
Maybe you know how to help? I'm out of hope...

**Comment by MAX1MDEV** [comment]
![image](https://github.com/MustardChef/WSABuilds/assets/58599802/60bb6183-241a-4d96-b597-0ab040a9d15b)
![image](https://github.com/MustardChef/WSABuilds/assets/58599802/0d4736b4-4f7e-4c06-b215-1f5bb15609df)
![image](https://github.com/MustardChef/WSABuilds/assets/58599802/61e52a6e-73fa-460a-bf9b-b5c191492847)
it happens when I run wsa settings

**Comment by MAX1MDEV** [comment]
Additionally, I would like to point out that I unzip using winrar

**Comment by MustardChef** [comment]
Screenshot of the issue you are facing?

**Comment by MAX1MDEV** [comment]
> Screenshot of the issue you are facing?

I'm just noting that I unzipped the file using winrar.

**Comment by MAX1MDEV** [comment]
I found a solution and fixed it, you want me to tell you how?

**Comment by MustardChef** [comment]
> I found a solution and fixed it, you want me to tell you how?

Yes. Please.

**Comment by MAX1MDEV** [comment]
> > I found a solution and fixed it, you want me to tell you how?
> 
> Yes. Please.

You need to go to Device Manager and enable: Microsoft Hyper-V Virtualization Infrastructure Driver and Virtual Disk Enumerator (Microsoft)
![image](https://github.com/MustardChef/WSABuilds/assets/58599802/19369d68-eb57-499f-9c0f-8f7e7e2d943b)
![image](https://github.com/MustardChef/WSABuilds/assets/58599802/1c3a4fa1-4ed5-4647-aaf2-8bc459301171)

**Comment by MAX1MDEV** [comment]
I turned them on and everything worked.

**Comment by MustardChef** [comment]
Thank you for sharing.
Since the issue is now fixed, I will close this issue.
