### ISSUE TITLE
Getting Error 0x80073CFD but I should have all most recent updates installed Win 10

### ISSUE THREAD

**Issue by NebularNerd** [MustardChef/WSABuilds#38]
I'm trying to install WSA on Win 10 and getting the above error. I have followed the installation guides and the run updates including optional cumulative 22H2 updates as suggested in the `Error 0x80073CFD` page but still not having much luck.

The only update not installed is [KB5022282](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5022282) as it refuses to install saying it's not applicable. This is true as it's replaced by [KB5023773](https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=985d9c39-e589-4b8d-a209-31c1b083a07f) which is installed.

With every available update I can install I'm still falling short of the required version. If anyone has any thought that might help me get this installed that would be great.

## Screenshots:
![image](https://user-images.githubusercontent.com/8470449/227516611-5c031c8a-2d57-45fa-b8e7-3ccd9289fa45.png)

![image](https://user-images.githubusercontent.com/8470449/227516999-9c948f2e-388a-44fe-9c9d-2f39f6944db7.png)

**Comment by MustardChef** [comment]
@NebularNerd can you provide me with the logs using the command that starts with "Get-AppPackageLog" in the error displayed

**Comment by NebularNerd** [comment]
> @NebularNerd It seems like you have downloaded the Windows 11 build of WSA from releases. Please confirm that the build is indeed the ones for Windows 10. If the issue persists, can you provide me with the logs using the command that starts with "Get-AppPackageLog" in the error displayed

As always it's the simple things 🤦‍♂️ I just clicked releases, saw x64 builds and downloaded it, let me try this again using the correct Win10 download from the release page.

![doh-doh-doh-doh-doh 1](https://user-images.githubusercontent.com/8470449/227546960-b59ec0e0-5593-4f74-8d68-58369006295f.gif)
