### ISSUE TITLE
WSABuilds LTS Build #3 (03/06/24) for Windows 10 x64 | Error when installing on Windows 10 OS Build 19045.4412 [BUG]

### ISSUE THREAD

**Issue by onoakino** [MustardChef/WSABuilds#384]
### Describe the bug

Trying to install LTS build #3 for windows 10 x64 (with magisk 27 and gapps version), but I keep on getting the error below

`                    
![runBatError](https://github.com/MustardChef/WSABuilds/assets/24814387/02ff78a6-3e7d-4084-8f16-c6f62660dcb0)
      

### Steps to reproduce the issue

1. Extract the .7z archive using 7-zip (recommended) and rename the extracted folder to WSA
2. Delete the .7z archive (It is recommended to keep the .7z archive until WSA has been installed and is working properly)
3. Move the newly extracted folder to a suitable location (Documents folder is a good choice), as you will need to keep the folder on your PC to use MagiskOnWSA
4. Open the WSA folder and double-click on Run.bat

### Expected behaviour

As https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.5.0_LTS_3/WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-27.0.27000.-stable-GApps-13.0_Windows_10.7z  

is intended for Windows 10 that is running on OS version 10: 22H2 10.0.19045.2311 or higher, I should be good to go. My device OS version 10 22h2, OS build 19045.4412
![spec](https://github.com/MustardChef/WSABuilds/assets/24814387/30d86ea4-6959-497b-a162-f954ee583fe3)

### Downloaded Build Of WSA

https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2311.40000.5.0_LTS_3/WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-27.0.27000.-stable-GApps-13.0_Windows_10.7z

### Windows build number

Windows 10 Version 22H2 (OS Build 19045.4412)

### PC Specification

..

**Comment by MustardChef** [comment]
Are you sure you are installing the Windows 10 Build. I have checked if the Windows 10 Builds and found nothing wrong with them.

**Comment by onoakino** [comment]
100% sure. The error, it seems, is that the installer is expecting a Windows 11, but finding that the OS is a Windows 10. I downloaded from [here](https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2311.40000.5.0_LTS_3) which are the LTS builds for Win10.

**Comment by MustardChef** [comment]
Could you send me a screenshot of the AppxManifiest.xml file.

**Comment by onoakino** [comment]
Sorry I couldn't anymore as I already have deleted the file, which, in hindsight, I shouldn't have for the purpose of troubleshooting.  But anyway, you might be right. I might have downloaded an incorrect build. I installed the nightly release with gapps and just sideloaded magisk and all is well. Closing this ticket now. Thanks!
