### ISSUE TITLE
[BUG] Magisk is in the image instead of KernelSU

### ISSUE THREAD

**Issue by 3bagorion33** [MustardChef/WSABuilds#385]
### Please provide a clear and concise description of the changes you would like to see made to the documentation.

I just downloaded the file WSA_2311.40000.5.0_x64_Release-Nightly-with-KernelSU-v1.0.0.0-MindTheGapps-13.0-RemovedAmazon.7z, did a clean install by uninstalling WSA from the start menu. After installation, the KernelSU program is missing, while Magisk is present.

**Comment by MustardChef** [comment]
Which release did you download from?

**Comment by MustardChef** [comment]
I will have a look, thank you.

**Comment by 3bagorion33** [comment]
After I downloaded KernelSU.apk from assets and installed it via ADBInstaller, KernelSU manager informed me that KernelSU is not installed.

**Comment by MustardChef** [comment]
Cannot reproduce this.
Downloaded the same .zip file and it shows that KernelSU is working and Magisk Manager is nowhere to be seen.

**Comment by Schefflin** [comment]
Indeed, nothing was wrong.
![屏幕截图 2024-06-05 171724](https://github.com/MustardChef/WSABuilds/assets/136178603/157dc94e-ee0f-49ce-87ea-8aa0e1a88bc7)

**Comment by 3bagorion33** [comment]
Could you check MD5 of archive?
bba05e70851cf52adb7a4b1b0bfa2640

**Comment by MustardChef** [comment]
It is indeed: ``bba05e70851cf52adb7a4b1b0bfa2640``.

**Comment by 3bagorion33** [comment]
![изображение](https://github.com/MustardChef/WSABuilds/assets/18649079/891e3685-bd0c-4cf8-a738-4e8b054025a7)

**Comment by 3bagorion33** [comment]
Ok, after restarting WSA it shows now
![изображение](https://github.com/MustardChef/WSABuilds/assets/18649079/5b61802b-daf8-4978-9936-091150a68e02)
Magic))

**Comment by 3bagorion33** [comment]
I tried a clean installation without Internet and got this error again.

**Comment by SherlockChiang** [comment]
> I tried a clean installation without Internet and got this error again. When I turned on the internet, the error disappeared. Is the kernel with KernelSU downloaded from the Internet?

same as you

**Comment by Schefflin** [comment]
> I tried a clean installation without Internet and got this error again. When I turned on the internet, the error disappeared. Is the kernel with KernelSU downloaded from the Internet?

@3bagorion33 @SherlockChiang I don't know what you exactly mean but I suggest you uninstall it and delete installation file and cleanly install WSA_LTS2 if no problem then overwrite installation to update to WSA_LTS3.

**Comment by SherlockChiang** [comment]
> > I tried a clean installation without Internet and got this error again. When I turned on the internet, the error disappeared. Is the kernel with KernelSU downloaded from the Internet?
> 
> @3bagorion33 @SherlockChiang I don't know what you exactly mean but I suggest you uninstall it and delete installation file and cleanly install WSA_LTS2 if no problem then overwrite installation to update to WSA_LTS3.

Thank you for your advice, but it really happens when I shut down my network......
Pretty amazing
And now I have successfully installed the latest distribution❤
