### ISSUE TITLE
[BUG] Infinite loading

### ISSUE THREAD

**Issue by MuhammedEmirArtan** [MustardChef/WSABuilds#386]
### Describe the bug

It says Starting WSA but its infinite, I looked to Task Manager and found that Vmmem firstly uses 500 MB, then 900, then it rises up to 2 GB, and it dissappears, new Vmmem appears and this is a loop.

### Steps to reproduce the issue

1- Open WSA
2- Start File Manager

### Expected behaviour

WSA starts and I can use the file manager

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-27.0.27000.-stable-GApps-13.0_Windows_10.7z

### Windows build number

19044.2604 (W10 LTSC 2021, needed updates installed)

### PC Specification

Intel i5-2310
4 GB DDR3 (WSA uses 2 GB)
AMD Radeon HD 5450
GIGABYTE H61M-S2-B3

### Additional context

I was using WSA with no problems some time ago with this setup.

**Comment by MustardChef** [comment]
Your PC is simply too weak for WSA. 
4GB RAM is simply not enough for WSA.
Your 2nd Generation i5 CPU is almost 13 years old hardware.

Maybe try some [older versions](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/WSABuilds/OldBuilds.md) of WSA, as you stated that WSA previously worked for you.
