### ISSUE TITLE
[BUG] WSA Not Installing

### ISSUE THREAD

**Issue by IM-SUJON** [MustardChef/WSABuilds#387]
### Describe the bug

![Screenshot 2024-06-06 131720](https://github.com/MustardChef/WSABuilds/assets/171910585/30dba166-5ad9-4da1-a0f7-e23d7c886957)
Can somebody help me to fix this issus.

### Steps to reproduce the issue

I follow all steps that menteoned in github properly

### Expected behaviour

when i trying to install it got an error

### Downloaded Build Of WSA

WSA_2311.40000.5.0_arm64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0.7z

### Windows build number

22631.3672

### PC Specification

Model: Dell Latitude 7390 2 IN 1
Processor: Intel Core i5 8 Gen
Ram: 8 GB
SSD: 256 GB
Windows: 11 Pro

**Comment by MustardChef** [comment]
> ### Describe the bug
> ![Screenshot 2024-06-06 131720](https://private-user-images.githubusercontent.com/171910585/337160345-30dba166-5ad9-4da1-a0f7-e23d7c886957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjYyNzYsIm5iZiI6MTcxNzY2NTk3NiwicGF0aCI6Ii8xNzE5MTA1ODUvMzM3MTYwMzQ1LTMwZGJhMTY2LTVhZDktNGRhMS1hMGY3LWUyM2Q3Yzg4Njk1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwOTI2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzhhZGI5NDA2YTZmNTNkMjdiZTE2MjE5Yjg2ZTlkYTg5YjVhYzA1NjAyY2IxNzNjOGE5MWY3ODA0MWMxZjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-5WIlWTFdE5-BV6e9pksCg2cWz_BFrgyWyIchDmVp7s) Can somebody help me to fix this issus.
> 
> ### Steps to reproduce the issue
> I follow all steps that menteoned in github properly
> 
> ### Expected behaviour
> when i trying to install it got an error
> 
> ### Downloaded Build Of WSA
> WSA_2311.40000.5.0_arm64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0.7z
> 
> ### Windows build number
> 22631.3672
> 
> ### PC Specification
> Model: Dell Latitude 7390 2 IN 1 Processor: Intel Core i5 8 Gen Ram: 8 GB SSD: 256 GB Windows: 11 Pro
> 
> ### Additional context
> _No response_

If you would have read the Logs, you would have realised that you needed to download the x64 builds of WSA.

Delete all the current WSA files and get you builds from here: https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2311.40000.5.0_LTS_3

**Comment by IM-SUJON** [comment]
> > ### Describe the bug
> > ![Screenshot 2024-06-06 131720](https://private-user-images.githubusercontent.com/171910585/337160345-30dba166-5ad9-4da1-a0f7-e23d7c886957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjYyNzYsIm5iZiI6MTcxNzY2NTk3NiwicGF0aCI6Ii8xNzE5MTA1ODUvMzM3MTYwMzQ1LTMwZGJhMTY2LTVhZDktNGRhMS1hMGY3LWUyM2Q3Yzg4Njk1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwOTI2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzhhZGI5NDA2YTZmNTNkMjdiZTE2MjE5Yjg2ZTlkYTg5YjVhYzA1NjAyY2IxNzNjOGE5MWY3ODA0MWMxZjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-5WIlWTFdE5-BV6e9pksCg2cWz_BFrgyWyIchDmVp7s) Can somebody help me to fix this issus.
> > ### Steps to reproduce the issue
> > I follow all steps that menteoned in github properly
> > ### Expected behaviour
> > when i trying to install it got an error
> > ### Downloaded Build Of WSA
> > WSA_2311.40000.5.0_arm64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0.7z
> > ### Windows build number
> > 22631.3672
> > ### PC Specification
> > Model: Dell Latitude 7390 2 IN 1 Processor: Intel Core i5 8 Gen Ram: 8 GB SSD: 256 GB Windows: 11 Pro
> > ### Additional context
> > _No response_
> 
> If you would have read the Logs, you would have realised that you needed to download the x64 builds of WSA.
> 
> Delete all the current WSA files and get your builds from here: https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2311.40000.5.0_LTS_3 Hopefully this fixes your issue.

Thanks Sir for helping & it works. Actually im not expert at coding or bug fixing. And also sorry for my bad english.
