### ISSUE TITLE
[REQUEST] custom build

### ISSUE THREAD

**Issue by babaric-dev** [MustardChef/WSABuilds#388]
### Describe your request

I want a custom build with:
- Magisk stable
- GApps
- Remove Amazon Playstore

Thanks in advance.

Btw, why this rather straightforward combo isnt offered in releases?

**Comment by MustardChef** [comment]
Use: https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0_LTS_3/WSA_2311.40000.5.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z

**Comment by MustardChef** [comment]
All LTS builds with Google Play Store have Magisk Stable (unless stated otherwise) to allow Google services to function correctly.

**Comment by babaric-dev** [comment]
I see. Thanks for your quick response. I truly appreciate your work to this project.
