### ISSUE TITLE
[BUG] Magisk Modules are not installing

### ISSUE THREAD

**Issue by xXRealXxx** [MustardChef/WSABuilds#391]
### Describe the bug

Any time I install any Magisk module, it just won't appear in the modules tab in the Magisk app, even after a reboot, no matter how many times I try to install it.

### Steps to reproduce the issue

- open magisk
- install any module
- module doesn't appear
- and the module doesn't work

### Expected behaviour

modules should show up in the modules tab and they should work

### Downloaded Build Of WSA

the latest stable one at the time of writing for Windows 10: WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0_Windows_10

### Windows build number

22H2

### PC Specification

CPU: Ryzen 7600X
GPU: RX 7800 XT
RAM: 32 GB DDR5 @ 6000MHz
Mobo: Asus Rog Strix B650E-E Gaming Wifi
SSD: Kingston KC3000 2TB

**Comment by MustardChef** [comment]
Use the latest LTS builds.
