### ISSUE TITLE
[BUG] Some apps bug out on the latest pre-release build

### ISSUE THREAD

**Issue by xXRealXxx** [MustardChef/WSABuilds#392]
### Describe the bug

Google Play is just stuck on an infinite load screen (the play logo shows, but it doesn't load any further). This happens after logging in.
Jaumo just shows the app logo and force closes on its own after like 15 seconds.
Badoo opens up and runs properly, but after a short amount of time (again, like 15 seconds) it force closes.
This didn't happen on the latest stable build. 

### Steps to reproduce the issue

For Google Play bug:
- Log in to Google Play on initial setup.
- Try running Google Play.
- See how it gets stuck on an infinite load.

For Jaumo:
Just install the app and try to open it.

For Badoo: 
install the app, go through the log in process and permission stuff, and see how it keeps force closing itself.

### Expected behaviour

The mentioned apps should work properly, without not loading in or force closing.

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-27.0.27000.-stable-GApps-13.0_Windows_10

### Windows build number

22H2

### PC Specification

CPU: Ryzen 7600X
GPU: RX 7800 XT
RAM: 32 GB DDR5 @ 6000MHz
Mobo: Asus Rog Strix B650E-E Gaming Wifi
SSD: Kingston KC3000 2TB

### Additional context

Why am I doing this? I want to use the disable secure flag lsposed module on WSA.
Hiding the Magisk app and using the denylist doesn't affect these bugs at all. 

Update: the latest KernelSU pre-release build works flawlessly.

**Comment by MustardChef** [comment]
Did you clear the Data and Cache of Google Play Services and Google Play Store and try again?

**Comment by xXRealXxx** [comment]
> Did you clear the Data and Cache of Google Play Services and Google Play Store and try again?

Yap, that didn't fix it. And I can only delete the cache of Play Services. There's a manage storage button there instead of delete storage, but that doesn't open anything, it just goes back a step in the settings.

**Comment by xXRealXxx** [comment]
The Facebook Andoird app also crashes after a few seconds, so I can't even log in to test that out. Seems like some bug is making a lot of apps keep crashing

**Comment by xXRealXxx** [comment]
Update: the latest KernelSU pre-release build works flawlessly.
