### ISSUE TITLE
[REQUEST] Add Bluetooth Support

### ISSUE THREAD

**Issue by KadimAlpha** [MustardChef/WSABuilds#397]
### Describe your request

Hey all, 
First of all great job keeping this ecosystem alive despite Microsoft's negligence. 
I wasn't sure if this is the place to do it but I'm shooting my shot lol. 
Is it possible to add support for bluetooth to allow apps that require it to access the PC's bluetooth adapter? Prime example for me is I'm trying to run a POS app that isn't available natively on windows, and I need it to connect to a bluetooth card reader.  
This would make a world of difference.

**Comment by MustardChef** [comment]
Not possible for me to fulfil your request as I do not have the expertise.
