### ISSUE TITLE
[SECURITY VULNERABILITY] In your codebase are some references of the cdn com polyfill com io service

### ISSUE THREAD

**Issue by PriNova** [MustardChef/WSABuilds#399]
### Describe the bug

Two of your html files are using the cdn.polyfill.io service which is known to inject malicious code.

MagiskOnWSA/docs/Issues.html

MagiskOnWSA/DLL/docs/Issues.html

### Steps to reproduce the issue

https://x.com/WeldPond/status/1805973940642119900

### Expected behaviour

Use the polyfill service from cloudflare

### Downloaded Build Of WSA

n/a

### Windows build number

n/a

### PC Specification

n/a

**Comment by MustardChef** [comment]
Corresponding files have been deleted. Please also notify the creator of the HTML Files of this vulnerability, so that they can take action (https://github.com/YT-Advanced/WSA-Script).

**Comment by PriNova** [comment]
Done.

Thank you for your lightning fast reaction.

**Comment by MustardChef** [comment]
Since this issue has been resolved, I shall now close this issue.
Thanks again for bringing this to my attention.
