### ISSUE TITLE
Can't instaill 2211

### ISSUE THREAD

**Issue by RottenLeader** [MustardChef/WSABuilds#4]
This is the error log

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.
(Exception from HRESULT: 0x80073CF9)
error 0xCE: Creating the package metadata directory G:\WSA_2211.40000.10.0_x64_Release-Nightly-with-magisk-831a398b.252
06.-canary-MindTheGapps-13.0-RemovedAmazon\WSA_2211.40000.10.0_x64_Release-Nightly-with-magisk-831a398b(25206)-canary-M
indTheGapps-13.0-RemovedAmazon\microsoft.system.package.metadata failed.
NOTE: For additional information, look for [ActivityId] aca6291c-2225-0000-bd9d-fcad2522d901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID aca6291c-2225-0000-bd9d-fcad2522d901
At line:1 char:1
+ Add-AppxPackage -Register "G:\WSA_2211.40000.10.0_x64_Release-Nightly ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (G:\WSA_2211.400...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Remove amazon ........,

**Comment by MustardChef** [comment]
Solved
Problem: The MagiskOnWSA files was not extracted/decompressed/unzipped properly, hence corrupting the contents. 
Solution: MagiskOnWSA was reextracted and the Run.bat script was run once again, allowing WSA to install without problem
