### ISSUE TITLE
Change UUID / ID

### ISSUE THREAD

**Issue by filzek** [MustardChef/WSABuilds#41]
Hi,

Can you show how we can change the uuid/id os the WSA android to test developed applications.

We need to use WSA for testing and we are unable to change the UUID, if we use the Android Studio wenm can set the UUiD upon load, but in WSa we cannot.

Please let us know how to do it!

Thanks

**Comment by MustardChef** [comment]
@filzek By UUID, do you mean Device information such as "Build Number" "Device Name" "Device Specification" "Device Model"

**Comment by filzek** [comment]
Android ID / Device ID

Tô simulate different device, so once we change it it is being recognize as another phone, so the app in development can disable the paid functions as the device is not the same ordered, this kind of things.

So it's an idea to pack on it.

**Comment by MustardChef** [comment]
Well, there is no easy way to change these. Utilizing Root is the only option that I can see to achieving this, unless Microsoft adds official means through which this can be achieved.

**Comment by MustardChef** [comment]
> Android ID / Device ID
> 
> Tô simulate different device, so once we change it it is being recognize as another phone, so the app in development can disable the paid functions as the device is not the same ordered, this kind of things.
> 
> So it's an idea to pack on it.

@filzek It has been many months however, you can check out https://github.com/YT-Advanced/WSA-Script, where the devs have included an option to be able to edit build.props of WSA before builing using the MagiskOnWSAScript.

**Comment by YT-Advanced** [comment]
@MustardChef We are including, so please wait

**Comment by YT-Advanced** [comment]
@filzek I'm here to annouce that we have added the feature to change from Pixel 5 to another Pixel version.
Note: We cannot change the Build ID because WSA may fail to start
