### ISSUE TITLE
[REQUEST] I didn't see any issues or find anything about it, but is there a way to add mic support for apps?  Or am I missing something to get it working?

### ISSUE THREAD

**Issue by angelwind76** [MustardChef/WSABuilds#411]
### Describe your request

I installed WSA so my children can use Messenger Kids since it's only available on mobile.  The problem is the mic (and possibly camera, they don't have one) doesn't work in the apps.  Is this something that can be worked on or does it already have support and I'm having issues?

**Comment by MustardChef** [comment]
@angelwind76 WSA claims to have Microphone and Camera support according to the official documentations. I myself have not tested the Microphone. Please could you confirm that the Microphone and Camera Privacy setting are set to allow WSA access.

**Comment by angelwind76** [comment]
Funny enough, I downloaded the Discord app, got the mic working through there, then Messenger Kids started working.  So weird workaround, but it does work now. :)

**Comment by MustardChef** [comment]
Very weird, but great to hear that the issue is now solved.
