### ISSUE TITLE
[REQUEST] Install on all Windows users

### ISSUE THREAD

**Issue by dareoon** [MustardChef/WSABuilds#415]
### Describe your request

I'm trying to use it on a PC with two accounts, but the installation fails due to a conflict with the other user. 
Would it be possible to add the installation to all users?

**Comment by MustardChef** [comment]
May or may not be possible. But this is out of the scope of this project. 
I have not seen anyone succeed with installing WSA on both user. 
Maybe look at packaging the WSABuilds files into MSIX files and self signing it (then installing the certificate for both user).
