### ISSUE TITLE
Cannot go to Main Menu after while watching a Video

### ISSUE THREAD

**Issue by Aadesh001** [MustardChef/WSABuilds#42]
On Apps like 'JioCinema' and 'Disney+Hotstar', while watching a video in fullscreen mode, if you click on Back button in the App UI, nothing happens. On JioCinema, restarting the application works but on D+Hotstar, you are greeted with a blank screen (reinstalling resolves this, but it happens again).

Windows 11 22H2 22621.1413 OS Build
Latest WSA Build.

**Comment by MustardChef** [comment]
> On Apps like 'JioCinema' and 'Disney+Hotstar', while watching a video in fullscreen mode, if you click on Back button in the App UI, nothing happens. On JioCinema, restarting the application works but on D+Hotstar, you are greeted with a blank screen (reinstalling resolves this, but it happens again).
> 
> Windows 11 22H2 22621.1413 OS Build Latest WSA Build.

I am not the best person to ask for help. but nonetheless could you record a video of the problem/issue.

**Comment by Aadesh001** [comment]
Here is JioCinema's example. (Ignore the ad)
Uploading doc_2023-03-31_17-04-03.mp4…

**Comment by Aadesh001** [comment]
Here's JioCinema's example (Ignore the ad)
https://user-images.githubusercontent.com/71982868/229109862-8b5aea5c-a643-4ed1-800e-05d28d14b303.mp4

**Comment by Aadesh001** [comment]
> @Aadesh001 have you tried using the arrow on the top left hand side, next to the app name

Yes, I did that later the video as well (after relaunching)

**Comment by MustardChef** [comment]
> > @Aadesh001 have you tried using the arrow on the top left hand side, next to the app name
> 
> Yes, I did that later the video as well (after relaunching)

Seems like a problem with the app. I highly recommend you to report this issue to the app developers.

**Comment by Aadesh001** [comment]
> > > @Aadesh001 have you tried using the arrow on the top left hand side, next to the app name
> > 
> > Yes, I did that later the video as well (after relaunching)
> 
> Seems like a problem with the app then. I highly recommend you to report this issue to the app developers. 

Oh okay. I checked two apps because of this reason but problem persisted on both of them so I thought this was a WSA issue

**Comment by MustardChef** [comment]
> > > > @Aadesh001 have you tried using the arrow on the top left hand side, next to the app name
> > > 
> > > Yes, I did that later the video as well (after relaunching)
> > 
> > Seems like a problem with the app then. I highly recommend you to report this issue to the app developers. 
> 
> Oh okay. I checked two apps because of this reason but problem persisted on both of them so I thought this was a WSA issue

If you want, you can report this to the [Microsoft  WSA Github Repo](https://github.com/microsoft/WSA)

**Comment by Aadesh001** [comment]
Will they allow non-official build with Play Store apps?

**Comment by MustardChef** [comment]
> Will they allow non-official build with Play Store apps?

You can try with the official version and if you have the same issue then report it.

**Comment by Aadesh001** [comment]
> > Will they allow non-official build with Play Store apps?
> 
> You can try with the official version and if you have the same issue then report it.

Okay thank you!

**Comment by MustardChef** [comment]
Since I cannot help you with this issue as it is an issue with either the app or WSA itself, I will now close this issue. Please reopen this issue, if you have anymore questions or have an update regarding this matter.
