### ISSUE TITLE
[BUG]Issue with Running WSA When VBS is Disabled on Windows

### ISSUE THREAD

**Issue by JSTT05** [MustardChef/WSABuilds#423]
### Describe the bug

WSA won't open at all when VBS is disabled. Is there any way to change that?

### Steps to reproduce the issue

Disable VBS (Virtualization-Based Security) on Windows.
Attempt to launch WSA (Windows Subsystem for Android).
Observe that WSA fails to open.

### Expected behaviour

WSA should open and function normally, even with VBS disabled

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-GApps-13.0-NoAmazon

### Windows build number

win11 22631 3958

### PC Specification

![image](https://github.com/user-attachments/assets/2efcd9db-e021-41b4-90b6-da0b8ff0a5f7)

**Comment by MustardChef** [comment]
WSA needs VBS. It cannot run without it. Sorry.
