### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 26Ssr** [MustardChef/WSABuilds#433]
### Describe the bug

after I run the run .bat, I get the error.
![微信图片_20240819111953](https://github.com/user-attachments/assets/8afb235c-6962-41bb-a7a4-c012e258e7ed)

### Steps to reproduce the issue

after I run the run .bat, I get the error.

### Expected behaviour

open it 

### Downloaded Build Of WSA

WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0_Windows_10

### Windows build number

win10

### PC Specification

![微信图片_20240819112357](https://github.com/user-attachments/assets/327e1dac-fc02-4714-8c0b-c90b6f70cf77)

**Comment by MustardChef** [comment]
Please update your Windows OS and make sure that you have downloaded from the Windows 10 build releases.
