### ISSUE TITLE
[REQUEST] Custom ROMS?

### ISSUE THREAD

**Issue by AlexDev404** [MustardChef/WSABuilds#434]
### Describe your request

Since the WSA provided is an edited version of the already-provided WSA by Microsoft, and is stored in a regular disk image, wouldn't it be technically possible to port a version of a custom ROM, such as [LineageOS](https://lineageos.org/) for WSA?

It would be a great addition since it's inevitable that WSA will continue to support new Android apps after its shutdown, since the Android Operating System will continue to evolve while WSA stays pinned on only one version.

So even if this possibility to switch ROMS is not added now, it's about time we start thinking about solutions to prevent this sort of thing from happening.

**Comment by MustardChef** [comment]
Out of scope of this project. This may or may not be possible.
