### ISSUE TITLE
[REQUEST] Allow vmos & wireless debugger

### ISSUE THREAD

**Issue by mufthakherul** [MustardChef/WSABuilds#435]
### Describe your request

Please Allow vmos or alternative apps to access a virtual android in wsa. Enable wireless debugger too.

![Screenshot 2024-08-26 030107](https://github.com/user-attachments/assets/af43b2f6-f8b7-416c-a94f-8dcaeb3d3320)
![Screenshot 2024-08-26 030044](https://github.com/user-attachments/assets/4d2f29ec-88a6-4096-9394-d55c2ca97503)

**Comment by MustardChef** [comment]
Out of the scope of the project.
