### ISSUE TITLE
[BUG] Failed to merge resources, WSA Seetings will always be in English

### ISSUE THREAD

**Issue by paaavann** [MustardChef/WSABuilds#445]
### Describe the bug

I dont know what happned here, I am on 24h2 and when i try to run.bat I get this.

![image](https://github.com/user-attachments/assets/640a80d3-a59e-4dcd-92f4-ddebc1bf3a48)

### Steps to reproduce the issue

Run the run.bat and wait for few seconds

### Expected behaviour

Creating pri from dumps....
Start-Process : This command cannot be run due to the error: This version of %1 is not compatible with the version of
Windows you're running. Check your computer's system information and then contact the software publisher.
At E:\SubSystem\WSA_2407.40000.0.0_arm64\MakePri.ps1:43 char:28
+ ... wFromDump = Start-Process -PassThru -NoNewWindow makepri.exe -Args "n ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

You cannot call a method on a null-valued expression.
At E:\SubSystem\WSA_2407.40000.0.0_arm64\MakePri.ps1:45 char:9
+         $ProcNewFromDump.WaitForExit()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

E:\SubSystem\WSA_2407.40000.0.0_arm64\MakePri.ps1 : Failed to create resources from priinfos
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,MakePri.ps1

WARNING: Failed to merge resources, WSA Seetings will always be in English
Press any key to continue

### Downloaded Build Of WSA

WSA_2407.40000.0.0_arm64_Release-Nightly-with-magisk-b38ab2a7.27004.-canary-GApps-13.0-NoAmazon

### Windows build number

26120.1542 (24H2)

### PC Specification

![image](https://github.com/user-attachments/assets/28a51974-e821-4667-a114-cf9d5c4e6659)

**Comment by MustardChef** [comment]
@paaavann Get the correct release! Your system is an "x64-based PC" as evident from the System Information screenshot, so you must get the WSA builds with the matching architecture type.

**Comment by nerlins** [comment]
Not gonna lie. Somehow this whooped my butt for a few minutes, as well...
