### ISSUE TITLE
[BUG]版本错乱 Version is out of order

### ISSUE THREAD

**Issue by YanYiGe2023** [MustardChef/WSABuilds#446]
### Describe the bug

我下载了[https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2407.40000.0.0/WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z](url)预期上它应该没有magisk，没有Amazon，包含Google，但事实上我下载安装后它有magisk

I downloaded [https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2407.40000.0.0/WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z](url) Expected it should have no magisk, no Amazon, including Google, but in fact it had magisk after I downloaded and installed it

我想在wsa上玩PUBG M（虽然很明显这是个馊主意），但之前我确实成功启动过，但今天安装的不行，后来我意识到可能PUBG发现了magisk，所以卡在启动页面

I wanted to play PUBG M on wsa (although obviously it was a bad idea), but I did successfully launch it before, but it didn't work to install today, and later I realized that maybe PUBG found magisk, so it got stuck on the launch page

### Steps to reproduce the issue

安装[https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2407.40000.0.0/WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z](url)，右下角提示“刷入系统更新”

Installation[https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2407.40000.0.0/WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z](url), the lower right corner prompts "Flash in system update"

### Expected behaviour

没有magisk，正常启动游戏

### Downloaded Build Of WSA

https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2407.40000.0.0/WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z

### Windows build number

Windows11 23H2 22631.4169

### PC Specification

系统制造商	HUAWEI
处理器	AMD Ryzen 7 4800H with Radeon Graphics，2900 Mhz，8 个内核，16 个逻辑处理器
内存       16GB

*这不重要，此PC满足Windows11的要求*

System manufacturer HUAWEI
Processor AMD Ryzen 7 4800H with Radeon Graphics, 2900 Mhz, 8 cores, 16 logic processors
RAM 16GB

*It doesn't matter, this PC meets the requirements of Windows 11*

**Comment by MustardChef** [comment]
Please use these builds instead: 
https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2311.40000.5.0.
