### ISSUE TITLE
[BUG] error 0x80073D28

### ISSUE THREAD

**Issue by MurderBear980** [MustardChef/WSABuilds#447]
### Describe the bug

i get this error 0x80073D28: Cannot register the
                                       MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe package due to
                                       the following error: The package installation failed because administrator
                                       privileges are required. Please contact an administrator to install this
                                       package.

### Steps to reproduce the issue

paste into powershell with admin ____  Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml

then paste this Get-AppPackageLog -ActivityID <udid>

### Expected behaviour

gives you logs of the errors

### Downloaded Build Of WSA

WSA_2407.40000.0.0_x64_Release-Nightly-with-magisk-b38ab2a7.27004.-canary-GApps-13.0-NoAmazon

### Windows build number

22631

### PC Specification

64-bit operating system, x64-based processor

**Comment by MustardChef** [comment]
You can only install WSA on an Administrator account/user.
