### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Oas238** [MustardChef/WSABuilds#448]
### Describe the bug

I create 3 new  gmails Its banned my 3 Gmail Accounts i dont know why please take a look on it 

### Steps to reproduce the issue

My 3 accounts of gmail is banned whenever i login its shows error that authenrication is failed

### Expected behaviour

Please dont block gmails

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-GApps-13.0-NoAmazon

### Windows build number

Version 23H2 (OS Build 22631.4169)

### PC Specification

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
OS Manufacturer	Microsoft Corporation
System Manufacturer	Dell Inc.
System Model	OptiPlex 7010
System Type	x64-based PC
Processor	Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, 3201 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. A08, 19/09/2012
SMBIOS Version	2.7
BIOS Mode	UEFI
Hardware Abstraction Layer	Version = "10.0.22621.2506"
Installed Physical Memory (RAM)	12.0 GB
Total Physical Memory	11.9 GB
Available Physical Memory	4.58 GB
Total Virtual Memory	13.2 GB
Available Virtual Memory	6.08 GB
Page File Space	1.26 GB

**Comment by MustardChef** [comment]
Don't use WSA to create new Gmail Account!!

**Comment by Oas238** [comment]
> Don't use WSA to create new Gmail Account!! By using WSA, you have possibly triggered some sort of security/anti-spam system which may have caused the accounts to become banned.


Can i use my previous gmail account that i have created with my Phone ?
