### ISSUE TITLE
"Install.ps1" is not found.

### ISSUE THREAD

**Issue by thisisjin** [MustardChef/WSABuilds#45]
"Install.ps1" is not found.
Press any key to exit
![image](https://user-images.githubusercontent.com/22115417/229403923-d9e38d6c-790b-4ba5-b1b7-3885724e5504.png)

**Comment by MustardChef** [comment]
@thisisjin Join the Discord, so I can help.

**Comment by MustardChef** [comment]
> "Install.ps1" is not found. Press any key to exit ![image](https://user-images.githubusercontent.com/22115417/229403923-d9e38d6c-790b-4ba5-b1b7-3885724e5504.png)

@thisisjin thisisjin Make sure that you have downloaded and extracted the zip file without anything being corrupted. If you still get this issue, rename the folder and then try rerunning the "Run.bat" file. If you still have issues, comment here

**Comment by PCPlodPC** [comment]
I presume you've solved the issue by now, but in case you haven't it _looks_ like to me that you have a simple install path problem. I've made that mistake several times by just forgetting. You need to run install.ps1 from the installation directory which I am _assuming_ is NOT the System32 directory. The local syntax should be (under Powershell - Admin) .\install.ps1

**Comment by MustardChef** [comment]
> I presume you've solved the issue by now, but in case you haven't it _looks_ like to me that you have a simple install path problem. I've made that mistake several times by just forgetting. You need to run install.ps1 from the installation directory which I am _assuming_ is NOT the System32 directory. The local syntax should be (under Powershell - Admin) .\install.ps1

Hmm, great catch.

**Comment by MustardChef** [comment]
@thisisjin Well, since there is no response, I will assume that this issue is fixed and hence I will close this issue. Feel free to open this, if you still have this issue.
