### ISSUE TITLE
[BUG] Cannot Install WSA on Win 11. Please Help!

### ISSUE THREAD

**Issue by alasoul** [MustardChef/WSABuilds#475]
### Describe the bug

I have already attempted to re-install and uninstall the default WSA but I didn't initially. Perhaps, that's what the issue is.

Please let me know.

Thanks!
![game1732426927](https://github.com/user-attachments/assets/38c4b945-afe6-4451-9a54-8759cae9ab92)

### Steps to reproduce the issue

Install steps to running the run.bat file

### Expected behaviour

![game1732426927](https://github.com/user-attachments/assets/28406323-cdcd-47b4-8cf2-3cffebc9d78d)

### Downloaded Build Of WSA

[WSA_2311.40000.5.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z](https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0_LTS_3/WSA_2311.40000.5.0_x64_Release-Nightly-GApps-13.0-NoAmazon.7z)

### Windows build number

22631.4460

### PC Specification

Processor	AMD Ryzen Z1 Extreme, 3301 Mhz, 8 Core(s)

RAM                 16GB

**Comment by alasoul** [comment]
I also want to add that I can't find the MicrosoftCorporationII.WindowsSubsytemForAndroid folder it's pointing to in the error log... since I guess I already uninstalled the original one

**Comment by Mysticc28** [comment]
How did you solve this issue? I'm facing the same thing
