### ISSUE TITLE
[BUG] Working Apps Freeze on Startup Suddenly

### ISSUE THREAD

**Issue by codychen98** [MustardChef/WSABuilds#481]
### Describe the bug

=
I used Neo Backup to back up SmartLife, CloudEdge, and Midea Air app from my Android arm64 phone, then restore them in my Windows WSA. It was working perfectly for a while, and then suddenly it stopped working out of no where. Only these 3 smart home apps stopped working, all other apps working just fine. I ran out of ideas, any help will be greatly appreciated, thank you!

Here is what I tried to resolve the issue:
1. I have a full macrium reflect back up from previously, I restored the entire system to the time when I know for sure everything is working, but didn't work anymore.
2. I followed "WSA Stopped Working!.md" guide exactly, and tried the same steps twice, same issue.
3. I followed "Uninstallation.md" guide to completely uninstall, then reinstall without using previous userdata.vhdx or neo backup to restore, with everything as new, then download smartlife from playstore instead of neo backup restore, same issue.
4. Tried other WSA magisk builds, same issue.

### Steps to reproduce the issue

Just click on the app icon for any of the 3 apps, they just stay at loading the app forever, when I click on the "X' Icon to exit app, it freezes for few seconds, then exit app.

### Expected behaviour

Load into the App without freezing.

### Downloaded Build Of WSA

 WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-81658d45.27002.-canary-GApps-13.0-NoAmazon.7z 

### Windows build number

23H2 22631.4460

### PC Specification

OS Name	Microsoft Windows 11 Pro for Workstations
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	CODY
System Manufacturer	ASUS
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	AMD Ryzen 7 5800X 8-Core Processor, 4476 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 4702, 10/20/2023
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	ROG CROSSHAIR VIII HERO (WI-FI)
BaseBoard Version	Rev X.0x
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.2506"
User Name	CODY\Cody
Time Zone	Eastern Standard Time
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	63.9 GB
Available Physical Memory	46.0 GB
Total Virtual Memory	67.9 GB
Available Virtual Memory	40.5 GB
Page File Space	4.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, Mode Based Execution Control
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

### Additional context
I don't think it's a windows version issue, since my macrium reflect backup restored to previous window update that I know for sure WSA is working perfectly for all Apps, I haven't touched anything in BIOS for years either.

_No response_

**Comment by MustardChef** [comment]
Update to the latest Non-LTS and LTS Builds.
