### ISSUE TITLE
[Feature Request] Magisk Delta builds

### ISSUE THREAD

**Issue by akhil-rana** [MustardChef/WSABuilds#5]
[Magisk Delta](https://github.com/huskydg/magisk-files/) seems to pass safetynet on emulators and x86 android systems.

**Comment by MustardChef** [comment]
Yes, I can certainly build WSA with Magisk Delta for you and upload it.  However, I will need to test it first, before uploading builds on it in Github Releases, since I do not know whether or not this bypasses Safetynet on WSA.

**Comment by MustardChef** [comment]
> [Magisk Delta](https://github.com/huskydg/magisk-files/) seems to pass safetynet on emulators and x86 android systems.

I have uploaded WSA builds with Magisk Delta:
https://github.com/MustardChef/WSABuilds/blob/master/custombuilds/MagiskDelta/README.md

**Comment by akhil-rana** [comment]
WSA is working alright with magisk delta.

But unfortunately I'm not able to pass safetynet. Tried several things. Will update here if something changes.
