### ISSUE TITLE
[REQUEST] No magisk/gapps build for Windows 10

### ISSUE THREAD

**Issue by datsideofthemoon** [MustardChef/WSABuilds#57]
Hello, need a clean no magisk/gapps wsa build for Windows 10. Looked for history of releases and can't find.

**Comment by MustardChef** [comment]
> Hello, need a clean no magisk/gapps wsa build for Windows 10. Looked for history of releases and can't find.

Yes, I can upload this. I will update you when this has been completed.

**Comment by YT-Advanced** [comment]
> > Hello, need a clean no magisk/gapps wsa build for Windows 10. Looked for history of releases and can't find.
> 
> Yes, I can upload this. I will update you when this has been completed.

Why you don't use my powershell to automatic patch DLL and XML file for Windows :D

**Comment by datsideofthemoon** [comment]
> > > Hello, need a clean no magisk/gapps wsa build for Windows 10. Looked for history of releases and can't find.
> > 
> > 
> > Yes, I can upload this. I will update you when this has been completed.
> 
> Why you don't use my powershell to automatic patch DLL and XML file for Windows :D

Don't know. At start I found WSAPatch but did not understand how to apply it, so looked for WSABuilds. Please explain what is WSA-Script and what i need from Install.ps1

**Comment by MustardChef** [comment]
> > > > Hello, need a clean no magisk/gapps wsa build for Windows 10. Looked for history of releases and can't find.
> > > 
> > > 
> > > Yes, I can upload this. I will update you when this has been completed.
> > 
> > 
> > Why you don't use my powershell to automatic patch DLL and XML file for Windows :D
> 
> Don't know. At start I found WSAPatch but did not understand how to apply it, so looked for WSABuilds. Please explain what is WSA-Script and what i need from Install.ps1

Uploaded

**Comment by YT-Advanced** [comment]
> > > > Hello, need a clean no magisk/gapps wsa build for Windows 10. Looked for history of releases and can't find.
> > > 
> > > 
> > > Yes, I can upload this. I will update you when this has been completed.
> > 
> > Why you don't use my powershell to automatic patch DLL and XML file for Windows :D
> 
> Don't know. At start I found WSAPatch but did not understand how to apply it, so looked for WSABuilds. Please explain what is WSA-Script and what i need from Install.ps1

Nope, I don't mention you :))
