### ISSUE TITLE
[BUG] KernelSU Issues

### ISSUE THREAD

**Issue by AbdElrahmanShaker446** [MustardChef/WSABuilds#58]
### Describe the bug | 描述一下这个错误

can't give root permissions with kernelSu after latest WSA package installation ( WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-kernelsu-vX.X.X-MindTheGapps-XX.X-RemovedAmazon.zip) 
 
Superuser page keeps refreshing and not showing apps to give root access !

### Steps to reproduce the issue | 重现该问题的步骤

it is always there can't reproduce !

### Expected behaviour | 预期的行为

should show the apps to give root permissions 

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2303.40000.5.0_x64_Release-Nightly-with-kernelsu-v0.5.4-MindTheGapps-13.0-RemovedAmazon.zip

### Windows build number | Windows构建号

latest dev insider version (23440.1000)

### PC Specification | 个人电脑规格

اسم نظام التشغيل	‏‏Microsoft Windows 11 Pro Insider Preview
الإصدار	10.0.23440 البناء 23440
وصف آخر لنظام التشغيل 	غير متوفر
الشركة المصنعة لنظام التشغيل	Microsoft Corporation
اسم النظام	DESKTOP-VIN7BV0
الشركة الصانعة للنظام	HP
طراز النظام	HP ProBook 450 G5
نوع النظام	x64-based PC
SKU للنظام	3VJ45ES#BH5
المعالج	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz، 1992 ميغاهرتز، 4 الأساس (الأساسيات)، 8 المعالج (المعالجات) المنطقي
إصدار/تاريخ BIOS	HP Q85 Ver. 01.23.00, 29/11/2022
نسخة إدارة النظام من BIOS	3.1
إصدار وحدة التحكم المضمّنة	2.65
وضع BIOS‏ 	UEFI
الشركة المُصنعة للوحة الأساسية	HP
منتج اللوحة الأساسية	837D
إصدار اللوحة الأساسية	KBC Version 02.41.00
دور النظام الأساسي	جوال
حالة التمهيد الآمن	مغلق
تكوين PCR7	ترقية مطلوبة للعرض
دليل Windows	C:\WINDOWS
دليل النظام	C:\WINDOWS\system32
جهاز التشغيل	\Device\HarddiskVolume1
الإعدادات المحلية	المملكة العربية السعودية
الطبقة المجردة للأجهزة	الإصدار = "10.0.23440.1000"
اسم المستخدم	DESKTOP-VIN7BV0\Aboody Shaker
منطقة زمنية	مصر - التوقيت الرسمي
الذاكرة الفعلية المثبتة (RAM)	‏‏8.00 غيغابايت
إجمالي الذاكرة الفعلية	‏‏7.89 غيغابايت
الذاكرة الفعلية المتوفرة	‏‏977 ميغابايت
إجمالي الذاكرة الظاهرية	‏‏15.9 غيغابايت
الذاكرة الظاهرية المتوفرة	‏‏2.67 غيغابايت
مساحة ملف ترحيل الصفحات	‏‏8.00 غيغابايت
ملف الصفحات	C:\pagefile.sys
حماية DMA kernel	مغلق
الأمان المستند إلى الظاهرية	‏‏قيد التشغيل
الأمان المستند إلى الظاهرية يتطلب خصائص الأمان	
الأمان المستند إلى الظاهرية متوفر على خصائص الأمان	‏‏دعم الظاهرية الأساسية, ‏‏حماية DMA, UEFI Code Readonly, SMM Security Mitigations 1.0, عنصر التحكم في التنفيذ الذي يستند إلى الوضع
تم تكوين خدمات الأمان المستند إلى الظاهرية	‏‏تكامل رمز Hypervisor المفروض
تشغيل خدمات الأمان المستند إلى الظاهرية	‏‏Credential Guard, ‏‏تكامل رمز Hypervisor المفروض
نهج التحكم في تطبيق Windows Defender	‏‏تم فرضه
نهج وضع المستخدم للتحكم في تطبيق Windows Defender	‏‏‎‎تدقيق
دعم ‏‏تشفير الأجهزة	ترقية مطلوبة للعرض
تم اكتشاف hypervisor. لن يتم عرض الميزات المطلوبة لـ Hyper-V.

**Comment by MustardChef** [comment]
> ### Describe the bug | 描述一下这个错误
> 
> can't give root permissions with kernelSu after latest WSA package installation ( WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-kernelsu-vX.X.X-MindTheGapps-XX.X-RemovedAmazon.zip) 
>  
> Superuser page keeps refreshing and not showing apps to give root access !
> 
> ### Steps to reproduce the issue | 重现该问题的步骤
> 
> it is always there can't reproduce !
> 
> ### Expected behaviour | 预期的行为
> 
> should show the apps to give root permissions 
> 
> ### Downloaded Build Of WSA | 已下载的WSA版本
> 
> WSA_2303.40000.5.0_x64_Release-Nightly-with-kernelsu-v0.5.4-MindTheGapps-13.0-RemovedAmazon.zip
> 
> ### Windows build number | Windows构建号
> 
> latest dev insider version (23440.1000)
> 
> ### PC Specification | 个人电脑规格
> 
> اسم نظام التشغيل	‏‏Microsoft Windows 11 Pro Insider Preview
> الإصدار	10.0.23440 البناء 23440
> وصف آخر لنظام التشغيل 	غير متوفر
> الشركة المصنعة لنظام التشغيل	Microsoft Corporation
> اسم النظام	DESKTOP-VIN7BV0
> الشركة الصانعة للنظام	HP
> طراز النظام	HP ProBook 450 G5
> نوع النظام	x64-based PC
> SKU للنظام	3VJ45ES#BH5
> المعالج	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz، 1992 ميغاهرتز، 4 الأساس (الأساسيات)، 8 المعالج (المعالجات) المنطقي
> إصدار/تاريخ BIOS	HP Q85 Ver. 01.23.00, 29/11/2022
> نسخة إدارة النظام من BIOS	3.1
> إصدار وحدة التحكم المضمّنة	2.65
> وضع BIOS‏ 	UEFI
> الشركة المُصنعة للوحة الأساسية	HP
> منتج اللوحة الأساسية	837D
> إصدار اللوحة الأساسية	KBC Version 02.41.00
> دور النظام الأساسي	جوال
> حالة التمهيد الآمن	مغلق
> تكوين PCR7	ترقية مطلوبة للعرض
> دليل Windows	C:\WINDOWS
> دليل النظام	C:\WINDOWS\system32
> جهاز التشغيل	\Device\HarddiskVolume1
> الإعدادات المحلية	المملكة العربية السعودية
> الطبقة المجردة للأجهزة	الإصدار = "10.0.23440.1000"
> اسم المستخدم	DESKTOP-VIN7BV0\Aboody Shaker
> منطقة زمنية	مصر - التوقيت الرسمي
> الذاكرة الفعلية المثبتة (RAM)	‏‏8.00 غيغابايت
> إجمالي الذاكرة الفعلية	‏‏7.89 غيغابايت
> الذاكرة الفعلية المتوفرة	‏‏977 ميغابايت
> إجمالي الذاكرة الظاهرية	‏‏15.9 غيغابايت
> الذاكرة الظاهرية المتوفرة	‏‏2.67 غيغابايت
> مساحة ملف ترحيل الصفحات	‏‏8.00 غيغابايت
> ملف الصفحات	C:\pagefile.sys
> حماية DMA kernel	مغلق
> الأمان المستند إلى الظاهرية	‏‏قيد التشغيل
> الأمان المستند إلى الظاهرية يتطلب خصائص الأمان	
> الأمان المستند إلى الظاهرية متوفر على خصائص الأمان	‏‏دعم الظاهرية الأساسية, ‏‏حماية DMA, UEFI Code Readonly, SMM Security Mitigations 1.0, عنصر التحكم في التنفيذ الذي يستند إلى الوضع
> تم تكوين خدمات الأمان المستند إلى الظاهرية	‏‏تكامل رمز Hypervisor المفروض
> تشغيل خدمات الأمان المستند إلى الظاهرية	‏‏Credential Guard, ‏‏تكامل رمز Hypervisor المفروض
> نهج التحكم في تطبيق Windows Defender	‏‏تم فرضه
> نهج وضع المستخدم للتحكم في تطبيق Windows Defender	‏‏‎‎تدقيق
> دعم ‏‏تشفير الأجهزة	ترقية مطلوبة للعرض
> تم اكتشاف hypervisor. لن يتم عرض الميزات المطلوبة لـ Hyper-V.	
> 
> 
> ### Additional context | 额外的背景
> 
> _No response_

Hello, and thank you for opening an issue. I will check whether or not I have the same issue. But most likely, this is as a result of an issue with KernelSU or the MagiskOnWSA script itself.

**Comment by AbdElrahmanShaker446** [comment]
ok thanks for your replay, tell me if there anything i can do

**Comment by MustardChef** [comment]
> ok thanks for your replay, tell me if there anything i can do 

@AbdElrahmanShaker446 The latest update of WSA with WSA 2304.40000.5.0 should have KernelSU fixed. Please try it!

**Comment by AbdElrahmanShaker446** [comment]
@MustardChef yeah it works fine now thanks for hard wok i appreciate it

**Comment by MustardChef** [comment]
> @MustardChef yeah it works fine now thanks for hard wok i appreciate it

Look out for future updates
