### ISSUE TITLE
unable to detect target image

### ISSUE THREAD

**Issue by funinfun** [MustardChef/WSABuilds#6]
have the error"
!unable to detect target image
i!nstallation failed

after using PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1
![error](https://user-images.githubusercontent.com/123567250/214591314-15178866-bf34-47c0-80c5-2d6942699494.jpg)

**Comment by MustardChef** [comment]
@funinfun Magisk is included in the Windows Subsystem For Android builds (from this repo) already. There is no need to use 'Direct Install' to try and install/reinstall it.

**Comment by MustardChef** [comment]
@funinfun Join the [Discord](https://discord.gg/2thee7zzHZ) if you have any more questions. You can alternatively, reopen this issue if you feel like the issue has not been adressed sufficiently enough.
