### ISSUE TITLE
Project Enhancement: WSABuilds Manager App

### ISSUE THREAD

**Issue by MustardChef** [MustardChef/WSABuilds#65]
### Implemented Features

- [ ] CLI Interface
- [ ] GUI Interface
- [ ] Auto Detect and Display System Information --> OS Version, Name of User, Username, Virtualization + Virtual Machine Platform + Windows Hypervisor Platform Enabled Checker (Ghost Toolbox Style)
- [ ] Auto Detect Currently Installed WSA Version
- [ ] Auto Detect Windows Version and allow user to download builds directly, without using a browser
- [ ] Change Location of WSA Installation
- [ ] Auto Updating
- [ ] Manual Updates
- [ ] Give status on whether WSA is running or not
- [ ] Start WSA
- [ ] Stop WSA
- [ ] WSA Compatibility Checker
- [ ] Access Android Settings
- [ ] Setup FTP/ File Transfer
- [ ] Install APKs (Very Primative Function)

**Comment by YT-Advanced** [comment]
In this summer, I will start a project like this ones
