### ISSUE TITLE
The RPC server is unavailable when trying to set up MagikWSA on Win10  19043.2130

### ISSUE THREAD

**Issue by LOuroboros** [MustardChef/WSABuilds#7]
Hi!

I came across this project by chance, looking for a way to execute the msixbundle package of WSA on Windows 10 somehow on Google.

I was surprised when I found it since I never thought it was actually going to happen. However, I tried it and it doesn't seem to be working :/

I downloaded the latest Windows 10 build [from here](https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2211.40000.11.0) and uncompressed the contents of the .zip in a folder called "WSA" in a directory of my choice that I wouldn't need to mess with just as instructed.

Then I ran the Run.bat file, and I came across this error:

> Installing MagiskOnWSA...
> Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied. (Exception from HRESULT: 0x80073CFD)
> 
> Deployment operation progress: C:\Users\lun0s\Documents\WSA\AppxManifest.xml
> Initialized
> 
> + CategoryInfo          : NotSpecified: (C:\Users\lun0s\...ppxManifest.xml:String) [Add-AppxPackage], Exception
> + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Then I checked the Notes, and tried out the suggestions to get a more serviceable error message.

I typed in `Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml`, grabbed the UUID *(`c9836f0b-30c8-0001-6d58-85c9c830d901`)* and then I typed `Get-AppPackageLog -ActivityID c9836f0b-30c8-0001-6d58-85c9c830d901`.
The result was this:

> Get-WinEvent : The RPC server is unavailable
> At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Appx\Appx.psm1:90 char:20
> + ...    "ActivityId" { Get-WinEvent -log Microsoft-Windows-Appx* -oldest |
> +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Get-WinEvent], EventLogException
>     + FullyQualifiedErrorId : System.Diagnostics.Eventing.Reader.EventLogException,Microsoft.PowerShell.Commands.GetWinEventCommand

So I proceeded to open `services.msc`. The Remote Procedure Call (RPC) service is up and running normally.

The Remote Procedure Call (RPC) Locator service is not, but enabling and starting it didn't help as Run.bat still finished with an error.

I double checked and my Windows install is sitting on an NTFS partition in my C: drive. 

Fwiw, I also have the Virtual Machine Platform, WSL and the Windows Hypervisor Platform all enabled. The first 2 for work, and the last one I enabled it on a whim and never turned it off.

I looked up potential solutions and came across [this forum post](https://social.technet.microsoft.com/Forums/en-US/69fba4e0-a248-4d1c-9e0d-80071a2a446d/getwinevent-the-rpc-server-is-unavailable?forum=ITCG) where it's suggested to make sure the firewall makes exceptions to not block the RPC, so I enabled every Inbound Rule that involved the RPC like I show in the picture down below, but that didn't work either:

![mmc_20230126_023000430](https://user-images.githubusercontent.com/4485172/214765159-4f2305a4-f3fc-49ff-9c0c-b9b4b2193867.png)

Anyone knows what's happening?

I'm going to try to update my installation of Windows 10 later today, to see if that fixes the problem.

**Comment by MustardChef** [comment]
What build of Windows 10 do you have, please send a screenshot of `winver`

**Comment by MustardChef** [comment]
It looks like you are using a version that is too old

**Comment by LOuroboros** [comment]
> What build of Windows 10 do you have, please send a screenshot of `winver`. Please check if your Windows 10 Build number is Windows™ 10: 22H2 10.0.19045.2311 or higher as stated in [Requirements](https://github.com/MustardChef/WSABuilds#requirements)

Ouch. I missed that completely. My bad, sorry 🙏 

I did mention the exact build number of my Windows installtion in the title of this Issue ticket though.

Then hopefully, updating my installation of Windows 10 like I said I would should solve it.

I'm too busy to do it right now, so I'll give it a go later today and report back my findings. For the time being, I'm going to close this Issue ticket 👍

**Comment by MustardChef** [comment]
> > What build of Windows 10 do you have, please send a screenshot of `winver`. Please check if your Windows 10 Build number is Windows™ 10: 22H2 10.0.19045.2311 or higher as stated in [Requirements](https://github.com/MustardChef/WSABuilds#requirements)
> 
> Ouch. I missed that completely. My bad, sorry 🙏
> 
> I did mention the exact build number of my Windows installtion in the title of this Issue ticket though.
> 
> Then hopefully, updating my installation of Windows 10 like I said I would should solve it.
> 
> I'm too busy to do it right now, so I'll give it a go later today and report back my findings. For the time being, I'm going to close this Issue ticket 👍

My mistake, I did not see the build number in the title. Feel free to reopen this issue if you find yourself facing an issue.
🙏
