### ISSUE TITLE
Changing Release Notes Format

### ISSUE THREAD

**Issue by MustardChef** [MustardChef/WSABuilds#71]
- [ ] Making Release Notes Smaller
- [x] Making the differences between the different WSA .zip/.7z files clear

**Comment by sathmali** [comment]
hello ,is there anyone is working on this project .l would love to contribuate

**Comment by MustardChef** [comment]
> hello ,is there anyone is working on this project .l would love to contribuate

Yes of course. All contributions are welcome. You can open a PR with any improvements, changes, fixes etc. and I will be happy to merge.
