### ISSUE TITLE
[BUG] ADB Not Working

### ISSUE THREAD

**Issue by wowitsjack** [MustardChef/WSABuilds#75]
### Describe the bug | 描述一下这个错误

ADB doesn't work. Project is useless.

### Steps to reproduce the issue | 重现该问题的步骤

Try and use ADB.

### Expected behaviour | 预期的行为

A connection. Instead it just hangs, then dies. This is useless.

### Downloaded Build Of WSA | 已下载的WSA版本

Latest

### Windows build number | Windows构建号

22H2

### PC Specification | 个人电脑规格

modern good pc

### Additional context | 额外的背景

i am a embedded system dev, i know adb inside and out, and this is broken beyond words

**Comment by MustardChef** [comment]
> ### Describe the bug | 描述一下这个错误
> 
> ADB doesn't work. Project is useless.
> 
> ### Steps to reproduce the issue | 重现该问题的步骤
> 
> Try and use ADB.
> 
> 
> 
> ### Expected behaviour | 预期的行为
> 
> A connection. Instead it just hangs, then dies. This is useless.
> 
> ### Downloaded Build Of WSA | 已下载的WSA版本
> 
> Latest
> 
> ### Windows build number | Windows构建号
> 
> 22H2
> 
> ### PC Specification | 个人电脑规格
> 
> modern good pc
> 
> ### Additional context | 额外的背景
> 
> i am a embedded system dev, i know adb inside and out, and this is broken beyond words

 Windows 10 22H2? or 11 22H2?

Furthermore, please provide more information on the issue with ADB, such as screenshots.

**Comment by MustardChef** [comment]
@wowitsjack If the issue is regarding the  
Target Machine Actively Refused Connection then follow this fix guide (https://github.com/MustardChef/WSABuilds/blob/master/Fixes/TargetMachineActivelyRefusedConnection.md)

**Comment by MustardChef** [comment]
@wowitsjack Is the issue fixed?
