### ISSUE TITLE
[BUG]2304.40000.5.0无法安装

### ISSUE THREAD

**Issue by Danjuanlab** [MustardChef/WSABuilds#87]
### Describe the bug | 描述一下这个错误

Start-Process : 由于出现以下错误，无法运行此命令: 指定的可执行文件不是此操作系统平台的有效应用程序。。
所在位置 D:\WSA_2304.40000.5.0_arm64_Release-Nightly-with-kernelsu-v0.5.7-MindTheGapps-13.0-RemovedAmazon\MakePri.ps1:3
3 字符: 13
+             Start-Process -PassThru -WindowStyle Hidden makepri.exe - ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process]，InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

### Steps to reproduce the issue | 重现该问题的步骤

不论是下载magisk还是kernelsu的版本都无法在win11电脑上安装。但是之前的2303.40000.5.0安装包可以正常安装

### Expected behaviour | 预期的行为

1

### Downloaded Build Of WSA | 已下载的WSA版本

WSA_2304.40000.5.0_arm64_Release-Nightly-with-kernelsu-v0.5.7-MindTheGapps-13.0-RemovedAmazon

### Windows build number | Windows构建号

22000.1936

### PC Specification | 个人电脑规格

AMD 2700X  32g内存 amd580显卡

**Comment by MustardChef** [comment]
@Danjuanlab 

请把你所面临的错误的完整日志和截图给我。
Please could I have the full log and screenshot of the error that you are facing.

**Comment by Danjuanlab** [comment]
> @Danjuanlab
> 
> 请把你所面临的错误的完整日志和截图给我。 Please could I have the full log and screenshot of the error that you are facing.

It was my mistake and I didn't notice that I was downloading the arm version of the system.
