### ISSUE TITLE
升级LSPosed后WSA无法启动，有什么办法拯救？

### ISSUE THREAD

**Issue by bzkmsjy** [MustardChef/WSABuilds#88]
### Describe the bug | 描述一下这个错误

在Magisk中将LSPosed 1.8.6.6888升级到6898后，WSA无法启动，似乎是最新版LSPosed不兼容WSA，请问这种情况如何拯救？如果是安卓手机的话可以进入recovery卸载Magisk，或者删除data目录下的LSPosed模块再重启，WSA做不到这样，请问有别的方法拯救我的WSA吗？除了完全重装

### Steps to reproduce the issue | 重现该问题的步骤

无

### Expected behaviour | 预期的行为

无

### Downloaded Build Of WSA | 已下载的WSA版本

最新版本

### Windows build number | Windows构建号

22621.1702

### PC Specification | 个人电脑规格

无

### Additional context | 额外的背景

无

**Comment by bzkmsjy** [comment]
@MustardChef 我尝试了这个方法，WSA依旧无法启动，安装kernelSU的版本也无法启动，可能还是需要删除/data/adb/modules下的文件才行

**Comment by MustardChef** [comment]
> @MustardChef 我尝试了这个方法，WSA依旧无法启动，安装kernelSU的版本也无法启动，可能还是需要删除/data/adb/modules下的文件才行

不幸的是，你将不得不清洁地安装WSA。


我现在将关闭这个问题。如果你有任何进一步的问题或疑问，请随时重新打开。
