### ISSUE TITLE
[REQUEST] cifs.ko in kernekl modules

### ISSUE THREAD

**Issue by BenWaw** [MustardChef/WSABuilds#92]
Can somebody tell me where I can find cifs.ko module compatible with this kernel or implement it to core? I want to mount smb share directly into file system using cifsMenager but I need cifs.ko in kernel to do it.

**Comment by MustardChef** [comment]
@BenWaw Thank you for your request. I feel that the best place to request this is in the [Microsoft WSA Github](https://github.com/microsoft/WSA). Sorry for not being of much help, and I wish that your request is heard in the appropriate place and that the cifs.ko module is implemented into the official WSA Android Kernel.
